### ISSUE TITLE
Providing type hints for IDEs and linters

### ISSUE THREAD

**Issue by TaaviE** [Flask-Middleware/flask-security#140]
It would be really nice if code could slowly start utilizing Python's type hints as specified by [this PEP](https://www.python.org/dev/peps/pep-0484/) to possibly catch a few bugs but just to simplify development when using a good IDE.

**Comment by jwag956** [comment]
I agree - but I think it's best to wait until we drop 2.7 support so we don't have to use the 'comment' style type hints.
My guess is by end of year folks like flask and werkzeug will do that - once they do, I will as well - then we can start on that process.

Up to know - both flask and werkzeug are continuing to issue new feature releases that are still compatible with 2.7

**Comment by TaaviE** [comment]
Though to be fair the user base of this package is probably not using Python 2.7 meaning dropping Python 2.7 will probably hurt noone. If it saves development time that could be used elsewhere I'd say it's worth it.
