### ISSUE TITLE
request: Please have FS reject an authentication if the user hasn't been active in n days

### ISSUE THREAD

**Issue by openbrian** [Flask-Middleware/flask-security#218]

**Comment by jwag956** [comment]
I am not sure this rises to a generally useful feature - however - I believe you can do this today pretty easily.

First - make sure you have the TRACKABLE feature enabled - that will track the last datetime that the user logged in.

Extend the LoginForm:

```
    class MyLoginForm(LoginForm):
      def validate(self):
        if not super(MyLoginForm, self).validate():
            return False

        # I think this will already be set  - self.user = _datastore.get_user(self.email.data)
        # Now add whatever additional checks:
        if self.user.last_login_at < (datetime.datetime.utcnow() - datetime.timedelta(days=n)):
           # set a nice message
           self.email.errors.append("Sorry we don't like you anymore")
           return False
```

**Comment by openbrian** [comment]
It's required for PCI (See PCI DSS 8.1.4 Remove/Disable inactive user accounts within 90 days) and for NIST 800-53 Moderate and High (See control AC-2(3) ACCOUNT MANAGEMENT | DISABLE INACTIVE ACCOUNTS The information system automatically disables inactive accounts after [Assignment: organization-defined time period].)

So it's useful to those websites.  Would you be interested in a PR?

**Comment by jwag956** [comment]
Interesting - there is a subtle difference between not allowing authentication and 'disabling' accounts. For example - things like forgot-password might still work if the account is active.
These regulations are always difficult to parse - but 'cant log in' doesn't really mean the same thing as 'account disabled'.

Just thinking here - would this be better as a scheduled admin action - once a day/hour check each user record and change active to False for those that haven't logged in?

I am always interested in PRs that help FS become more standards compliant. However - lets agree first - before you spend a bunch of time.

In the past - FS hasn't really been an 'admin' interface (such as even having activate/deactivate, list, etc) functions - which I consider to be 'admin'. That would be a pretty big shift...
