### ISSUE TITLE
Improving mobile usability by specifying custom HTML attributes on forms

### ISSUE THREAD

**Issue by TaaviE** [Flask-Middleware/flask-security#256]
Twilio recently published an article about 2FA, login forms and how to make them nicer to use. I think Flask-Security could implement a few of these things to make it easier for people.

Article: https://www.twilio.com/blog/html-attributes-two-factor-authentication-autocomplete

List of improvements in the article that could be implemented:
- [ ] Use of `inputmode` to hint browser to use a numeric keyboard on TOTP fields if possible
- [ ] Use of `pattern` to trigger numeric-only keyboard on iPhones and provide users instant validation
- [ ] Use of `autocomplete="one-time-code"` to have iPhones auto-suggest TOTP codes sent over SMS
- [ ] Use of `autocomplete` to hint new password, username and password fields. For browsers and password managers to suggest autocompletion

**Comment by jwag956** [comment]
That's a great idea - I use autocomplete in my login form - while I don't think many folks use the bundled Flask-Security forms - they would be a great example.
