### ISSUE TITLE
Allow login only for certain roles

### ISSUE THREAD

**Issue by callejerog** [Flask-Middleware/flask-security#267]
Scenario: I have two instances of the same app, one is public and another one private.
The public one is reserved only for certain users (having the same role).

Once the user is logged I can use @roles_accepted on my own views.
Would be great something similar, to be applied to the whole login mechanism, allowing login only for certain roles.

It could be probably achieved calling a user's method in login view before logging the user.
This method could be defaulted to "return True" (at Mixin level?), leaving the capability of overriding it.

**Comment by callejerog** [comment]
I solved this way:

`class CustomLoginForm(LoginForm):
	def validate(self):
		response = super(CustomLoginForm, self).validate()
		if response:
			if not self.user.can_login():
				self.password.errors.append('Cannot access. Call assistance')
				response = False
		return response`

**Comment by jwag956** [comment]
Your workaround seems clean and simple - and so far it doesn't seem like this feature is generally useful.
