### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by j-walker23** [Flask-Middleware/flask-security#315]
Sorry for opening an issue for this.

I just wanted to say thanks for taking this over. Flask security has been a sore spot for me trying to advocate in keeping our stack in python, and due to your work, this is going to help me immensely.

Really appreciate it, thank you so much!

Ok, now what this ticket is specifically about. Seeing a "Pallets" ref in your docs made me think of it.

I support some libs through scheduled donations through Pallets, and considering how valuable you taking this over is to this community, you should set up taking that same kind of "Show Support" option for us to thank you.

**Comment by jwag956** [comment]
You are very welcome - and thanks for the kind words. I would love feedback (you can email be directly if you want) about the features you are using, what is annoying, inconsistent, etc. Of course PRs are also welcome - but if you don't have time for that - dropping me a line or opening an issue (even if it is small or a idea for how to improve docs etc) - please do so.

My next step - hopefully in a week or so is to move this repo to a github organization - it will still be me for now - but that offers a lot more flexibility down the road

3.4 was a huge release with lots of features - 4.0 will be a drop py2.7 and maybe some other old stuff release - probably in a couple months....

**Comment by j-walker23** [comment]
I will definitely do that. Thanks again for all the work.
Get that support link up, i'll be your first supporter!
