### ISSUE TITLE
feature: add hook for email from address

### ISSUE THREAD

**Issue by louking** [Flask-Middleware/flask-security#318]
I have possibly different email from addresses I want to use with my application, depending on information in my database.

Right now I believe I have to catch the request, change app.config['SECURITY_EMAIL_SENDER'] to what's in my database for this request, then set the config back at the end of the request.

I'm not sure how common this use case is, but for me it'd sure be more convenient if there was a hook I could configure to do the database lookup.

**Comment by jwag956** [comment]
So all the views that send email do so by calling the 'send_mail' hook which is settable at FS configuration time.
So I think it would be easy to define your own send_mail. What isn't documented well is that as part of the context (the fourth argument) is **kwargs and will have the key 'user' which will have the user model - from there you can easily grab whatever field you need.

**Comment by louking** [comment]
Oooh, thanks. I missed that. I noticed in your 4.0.0 plans you'll be removing dependency on flask-mail. Do you know what you will be replacing it with? Maybe I should use the new package in my custom send_mail function?

**Comment by jwag956** [comment]
Hopefully that will work for you - feel free to reopen/open another issue if you still have problems.

Flask-Mail is basically abandoned - but still works - so removing the dependency will likely mean refactoring send_mail a bit and providing a default implementation that still uses Flask-Mail - but if you want something different - it won't be required (today - utils::send_mail actually required Flask-Mail for the Message object. Flask-Emails/python-email is an alternative.

I hope to figure out a nice way to combine the send_mail method override with the send_mail_task method option and wrap them both up in a class that can be extedended/overridden.....
