### ISSUE TITLE
How to intregate with flask-admin

### ISSUE THREAD

**Issue by lbiaggi** [Flask-Middleware/flask-security#329]
Hello I'm trying to integrate flask-security-too with flask-admin and can't login keeps reporting invalid password.

Tried to adapt the code from this [example](https://github.com/flask-admin/flask-admin/tree/master/examples/auth)

**Comment by acidjunk** [comment]
I'm using it with Flask-Admin and loging via Admin + API endpoints in a side project. If I remember correctly, most work was in templating the forms: https://github.com/acidjunk/improviser/tree/master/improviser/templates/security

Hope it helps.

**Comment by jwag956** [comment]
I sent a PR to flask-admin a while back showing how to integrate with Flask-Security-Too - including a more complete example:

https://github.com/flask-admin/flask-admin/pull/1928

**Comment by lbiaggi** [comment]
Thanks! I will close this issue
