### ISSUE TITLE
SAML Support

### ISSUE THREAD

**Issue by fxaeberhard** [Flask-Middleware/flask-security#350]
First of all congrats on the great job! We want to implement SAML login, any thoughts on how to? Do you think it should be integrated to the library in some way? I will anyway post the result of our work here.

**Comment by jwag956** [comment]
Thank you - I have not looked into it - there are a few packages I quickly found:
https://pypi.org/project/flask-saml2/

seems to be up to date. I have a item in my queue to make sure integrating with packages like Flask-Dance is easy - this might be similiar. My guess is that you will need to plug in prior to the request_loader - which alas today there is no easy way to do w/o simply copying a bunch of code and replacing the entire login_manager (which you can do). Please post questions and possible solutions here - as I said - I am not sure the actual SAML code should be in FS - however providing the hooks is something I am very interested in doing.

**Comment by jwag956** [comment]
Closing this - if you have more information or implementations to share - that would be great - also if you had to make modifications to Flask-Security - I would be interested in that as well.
