### ISSUE TITLE
Reason for not including bcrypt in setup?

### ISSUE THREAD

**Issue by mvhconsult** [Flask-Middleware/flask-security#356]
Now the user needs to install this manually. Any reason for it?
If so, please add to the documentation for installation.

**Comment by jwag956** [comment]
While bcrypt is the default - it is not required - different password hash schemes require additional packages to be installed - as documented in https://flask-security-too.readthedocs.io/en/stable/configuration.html#core SECURITY_PASSWORD_HASH.
