### ISSUE TITLE
Doc: how to use basic authentication

### ISSUE THREAD

**Issue by chiu0602** [Flask-Middleware/flask-security#359]
flask-security supports basic authentication but I cannot find out the way to use it. Can anyone tell me how to work it out? Thanks!

**Comment by jwag956** [comment]
In general, when asking questions it is best practice to put what you have tried (are you using curl?) is your server based on an example?

**Comment by chiu0602** [comment]
Currently my code works with using HTTPBasicAuth library, to make the basic auth dialog come up. 

```
from flask import Flask, redirect, request
from flask_compress import Compress
from flask_security import Security, SQLAlchemyUserDatastore, hash_password
from flask_security.utils import verify_password
from flask_sqlalchemy import SQLAlchemy
from flask_socketio import SocketIO
from flask_httpauth import HTTPBasicAuth
... 

def create_app():
   ... 
    from auth_model import Role, User
    user_datastore = SQLAlchemyUserDatastore(db, User, Role)
    security.init_app(app, user_datastore)

    @auth.verify_password
    def _(username, password):
        user = user_datastore.get_user(username)
        if user:
            return verify_password(password, user.password)
        return False
... 

@view_bp.route('/')
@auth.login_required
@auth_required('basic')
@roles_accepted('admin', 'operator')
def main():
    return render_template(
        'index.html',
    )`

```

**Comment by jwag956** [comment]
Your endpoint is annotated with @login_required - have you successfully logged in? You might first try just annotating with @auth_required('basic') and see if that works. And I assume you know there is no reason for you to defined a verify_password method - Flask-Security has that.

I don't know of a HttpBasicAuth library - are you using requests HttpBasicAuth module as your client?

**Comment by chiu0602** [comment]
You are right, it seems `@auth_required('basic')` not working and I have to use "HTTP Basic Auth" to fulfill my need. So back to my question, how can I use basic auth with using Flask-Security?

**Comment by jwag956** [comment]
auth_required('basic') is what you want - as I mentioned - you have auth.login_required - have you successfully gone through the login form/page/endpoint? That form does not use basic auth of course - it has a specific form you have to submit with username and password. Your response from your API request should have either errors in it OR a redirect. If you are getting a redirect to the the login form - that means you haven't actually logged in. Remember, unless you are using JSON API - you will always get a 200 or 301 response - you have to look at the contents.

**Comment by chiu0602** [comment]
If I don't use "HTTP Basic Auth" and config with `@auth_required('session')`, a simple page for login appears when I go to the URL. But when I use `@auth_required('basic')`, the page is forbidden to load.
If you think simply `@auth_required('basic')` works, please verify and let me know, thanks.

**Comment by jwag956** [comment]
Please try turning off CSRF for the login page:

CSRF_IGNORE_UNAUTH_ENDPOINTS=True

**Comment by jwag956** [comment]
So lets separate this into a couple phases. First - Just use the decorator @auth_reaquired('basic') and remove login.required and the @roles_accepted.
The unit test we have has the endpoint:

```
 @app.route("/http")
    @auth_required('basic')
    def http():
        return "HTTP Authentication"
```

And the client (this is a Flask test client:

```
def test_http_auth(client):
    response = client.get(
        "/http",
        headers={
            "Authorization": "Basic %s"
            % base64.b64encode(b"joe@lp.com:password").decode("utf-8")
        },
    )
    assert b"HTTP Authentication" in response.data
```

let's see if that works - then move on to more complex scenarios.

**Comment by chiu0602** [comment]
Your code works with using api call, but:
1. When I access the link through a browser, it redirect me to a login page, not "basic auth" dialog triggered by browser
2. If I login through the page with correct credential, it will loop going http://domain/login?next=%2Fhttp and finally browser telling "too many redirect"
3. If I login through pages with HTTPBasicAuth login (which browser basic auth dialog triggered), then no error when going to link "http://domain/next"

Please try to use browser to go to the link instead of triggering a http request by code.

**Comment by jwag956** [comment]
Got it  - thanks for the detailed testing. Yes - I can reproduce.

**Comment by chiu0602** [comment]
@jwag956 thanks a lot for your patience, cheers~

**Comment by jwag956** [comment]
#362

**Comment by chiu0602** [comment]
@jwag956 many thanks for your rapid, accurate fix!
