### ISSUE TITLE
Hashed emails

### ISSUE THREAD

**Issue by paulgessinger** [Flask-Middleware/flask-security#360]
In the interest of having as little data on the user as possible, I was wondering if it made sense to have an option to not store emails at all, but only keep a hash of it. That way, lookup via email and login should still be possible with a user provided email that's only in memory until the request is over. Password recovery would also be possible, since the user has to provide the email to lookup the account anyway.

Is my understanding correct that this is something that would have to be implemented at the level of this library (as opposed to flask-login, I guess)?

Is this something that you think is feasible?

**Comment by paulgessinger** [comment]
Looking at the code a bit, maybe this can even be implemented already in the user model in client code, since the recover workflow seems to already use the email from the form directly, after validation. That would be perfect.

**Comment by jwag956** [comment]
Interesting idea - yes - it would have to be implemented in the UserModel. It would take some careful going through code to find places that assume email (a quick scan showed that confirmable needs email to re-send the confirmation email).

In 4.0 (the master branch) I have spent some time removing many of the places that used to require/assume email - so for example I have tests that show you can have an email column (for registration/confirmation) but not use it for login (use phone or username).

So we are getting closer!

**Comment by JimDabell** [comment]
A typical hash would not be suitable.  `jim@example.com` and `jim@EXAMPLE.COM` are the same email address but have different hashes.  You would have to normalise at least the case.

**Comment by paulgessinger** [comment]
Hm is it expected that your login email address is case-insensitive? I guess you could easily normalize though.

**Comment by jwag956** [comment]
Just search for 'email case sensitive' and you can read buckets of comments about this.
Flask-Security does a case-insensitive match on email.

I am going to close this - I don't think it is a good idea - there are lots of reasons applications would want to communicate with their users to inform them of security concerns etc. If you are worried about data-at-rest - you should encrypt your DB (which is easy if you are using AWS etc).

Note also that in 4.0 with the advent of unified signin - we have removed all old vestiges of requiring email to sign in - so you can have the user's email - but use a username (or phone number) for them to sign in.

**Comment by paulgessinger** [comment]
Well I didn't say you shouldn't be able to store clear text emails sure. But if you don't absolutely need to send email that is not triggered by a user action, not having it in clear text should be the default. And hashing it is actually a much better idea than encrypting the database. 

If I understand correctly, with the changes for 4.0 you would be able to implement this on the user model level? Basically what this requires is a way for the email to be retrieved from the request form content rather than a database field in e.g. the confirmation flow.
