### ISSUE TITLE
Using SQLAlchemySessionUserDatastore with flask_sqlalchemy_session fails at find_user or find_role

### ISSUE THREAD

**Issue by AndrewOwenMartin** [Flask-Middleware/flask-security#361]
I'm fairly new to this project, so apologies if I've missed something, but I think I've found an error when trying to use the datastore `datastore.SQLAlchemySessionUserDatastore` with the `flask_sqlalchemy_session` extension.

The problem is that `SQLAlchemySessionUserDatastore` inherits from `SQLAlchemyUserDatastore` which assumes the use of the `Flask-SQLAlchemy` extension.

This difference is partially handled by `SQLAlchemySessionUserDatastore` making a fake `db` object, to hold the `session`. The problem arises in `SQLAlchemyUserDatastore` as both `SQLAlchemyUserDatastore.find_user` and `SQLAlchemyUserDatastore.find_role` expect to find a `query` attribute on `role_model` and `user_model`. As far as I'm aware, the models will only have `query` attributes when using `Flask-SQLAlchemy` extension.

The errors raised are `AttributeError: type object 'User' has no attribute 'query'` in `SQLAlchemyUserDatastore.find_user` or `AttributeError: type object 'Role' has no attribute 'query'`in `SQLAlchemyUserDatastore.find_role`

I tried to workaround this by manually adding `query` attributes to the models after declaring the datastore.

```
user_datastore = flask_security.SQLAlchemySessionUserDatastore(
    my_session, models.User, models.Role
)

user_datastore.user_model.query = my_session.query(models.User)
user_datastore.role_model.query = my_session.query(models.Role)
```

This seemed to work, I could log a user in without errors.

I'll be happy to make a similar change in the `SQLAlchemySessionUserDatastore` class (I'll do it in a way to avoid modifying the model class itself), write some tests, and submit a pull request if this seems suitable.

**Comment by jwag956** [comment]
Thanks for your detailed issue - there are lots of unit tests for SQLAlchemySessionUserDatastore so I am a bit surprised. Let me look into it before you spend more time on it.

**Comment by johnrevert** [comment]
Would it be best to remove the suggestion from the documentation then?

**Comment by jwag956** [comment]
good idea! Done.
