### ISSUE TITLE
Allow redirects on subdomains

### ISSUE THREAD

**Issue by willcroft** [Flask-Middleware/flask-security#366]
Is there interest in a feature to extend `utils.validate_redirect_url` such that redirects are allowed across subdomains, but still on the same top-level domain? It appears the subdomain config only allows for registering the blueprint on a specific subdomain, but not whitelisting the domain for redirects.

A use case is to have a flask-security based authentication at `auth.domain.tld` with allowable redirects to `app.domain.tld`, `app2.domain.tld` etc.

A basic refactor could allow for same-domain checks, while a more extensive one might allow a user-defined ruleset.

**Comment by jwag956** [comment]
Seems reasonable - it might take a bit of fiddling since underneath all this is Werkzeug's 'build' method.

I would want to think long and hard about different TLD - so starting with just allowing subdomains seems like a nice idea.

interested in submitting a PR?

**Comment by willcroft** [comment]
Yes, agreed on validating different TLDs! Definitely a larger can of worms.

Happy to submit a PR. 

I was just playing around with some ideas in anticipation, and it seems to me that if you're already using `Flask(subdomain_matching=True)` to init your app, then we'd also have `app.config['SERVER_NAME']` set and available to Flask. Does it make sense to perhaps require this config option when introducing allowable subdomain redirects, such that the logic to split apart a subdomain, check valid TLDs etc, actually isn't required, and we instead verify that the redirect parameter matches a subdomain on `app.config['SERVER_NAME']`? It's also the same config value that `SESSION_COOKIE_DOMAIN` will fall back to if not explicitly set which, again, you'd presumably be using if working with a separate subdomain for auth.

This is definitely a delicate change though, so welcome thoughts on the approach before submitting any code.

**Comment by jwag956** [comment]
You are ahead of me on this line of thinking... looking forward to your PR. I do like to always leverage Flask/Werkzeug concepts.

**Comment by willcroft** [comment]
@jwag956—PR submitted, tests and CI passing. Looking forward to your feedback!

I am also happy to update `CHANGES.rst` but unsure in which release you'd consider including this.
