### ISSUE TITLE
basic authentication for json request

### ISSUE THREAD

**Issue by chiu0602** [Flask-Middleware/flask-security#368]
I have some AJAX endpoints (with basic auth) for my webpage (the webpage don't have basic auth because it is running vue development mode with proxy)

When the page is loaded, request with following header is made:
```
GET /api/sc_list HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Referer: http://localhost:8080/
Pragma: no-cache
Cache-Control: no-cache
```
With using `Flask-Security`, error 401 is returned without browser basic auth dialog triggered.
Here is the response header:
```
HTTP/1.1 401 UNAUTHORIZED
X-Powered-By: Express
server: gunicorn/20.0.4
date: Tue, 28 Jul 2020 11:13:54 GMT
connection: close
content-type: application/json
content-length: 111
cache-control: no-store, no-cache
pragma: no-cache
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```
With using `Flask-HTTPAuth` (setup same as #359), browser basic auth dialog appeared.
```
HTTP/1.1 401 UNAUTHORIZED
X-Powered-By: Express
server: gunicorn/20.0.4
date: Tue, 28 Jul 2020 11:11:28 GMT
connection: close
content-type: text/html; charset=utf-8
content-length: 19
www-authenticate: Basic realm="Authentication Required"
cache-control: no-store, no-cache
pragma: no-cache
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```
For both response, same request header is sent by browser.
At this point, I don't know which is correct behavior, but `Flask-HTTPAuth` favor my development.
Should `WWW-Authenticate` should also be sent for this case?
Thanks

**Comment by jwag956** [comment]
That is correct - and something I did on purpose. If sending JSON then most likely you have some JS generating from your UI application. The last thing you want is a pop-up that isn't styled, and your application has no way to intercept/handle routing etc.

That said - part of the reason that was an issue was due to the default behavior of @auth_required() - which used to include "basic" which meant that any endpoint protected that way would get the pop-up. With the fixes in 3.4.4 that is no longer the case - so I can remove the 'force' json to not return header..

**Comment by chiu0602** [comment]
I agree that JSON response should not show browser auth dialog.

So I am curious to know how `Flask-HTTPAuth` response if request header only accept json
```
GET /api/sc_list HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: application/json                        <-- remain only  application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Referer: http://localhost:8080/
```
The response
```
HTTP/1.1 401 UNAUTHORIZED
X-Powered-By: Express
server: gunicorn/20.0.4
date: Wed, 29 Jul 2020 05:01:28 GMT
connection: close
content-type: text/html; charset=utf-8
content-length: 19
www-authenticate: Basic realm="Authentication Required"
cache-control: no-store, no-cache
pragma: no-cache
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```
Should "Accept" header strictly be followed? The way `Flask-HTTPAuth` to handle is not correct?

I am not a security expert, I don't have idea for a proper way that able to fulfill my need. @jwag956 you've marked this as bug, what is the bug and how will you fix it? Thanks.

**Comment by chiu0602** [comment]
Now I found that I can set basic auth on my dev environment, the problem is just how can I avoid publishing the credential to production.
```
axios.defaults.headers.common = {
  'Authorization': `Basic ${ btoa(username + ':' + password) }`,
};
```
If `Flask-Security` don't have bug, please close this issue.

Thanks a lot!

**Comment by jwag956** [comment]
A couple things - first is more subjective - I am not certain why you would want to send basic auth on every request - it is much more secure when building a web app to use sessions - which Flask and Flask-Security seamlessly support. Any other mechanism requires you to understand in detail how browsers will store your credential and what if any security issues that implies. From a pure security perspective (and ease of programming) I would highly encourage you to not use Basic Auth and use cookie based sessions.

The second part - which I believe is a bug (I have to look into it a bit more) is that in 3.3 I put in code that explicitly NEVER sends a WWW-Authenticate header if the caller wants json - I need to re-evaluate that decision.

**Comment by chiu0602** [comment]
1. My program requires basic auth for every request.
My program is spa, written in vue. After the code is transcompiled, it will be copied to web server, all the static files are secured with basic auth. Similarly, the ajax api calls are protected by basic auth too.
During my development on the spa, a localhost server is started (by vue cli) and I can update the vue spa, vue config able to let me have proxy settings redirect my ajax api calls to the real web server. But the vue server don't let me fill the auth info. No auth info in my case, ajax calls with 401 and have no way to prompt for me to fill in the credentials. And this could be fixed with introducing [vue env variables](https://cli.vuejs.org/guide/mode-and-env.html).
My final product will run on browser kiosk mode, showing content with no user interaction, that's why my spa not using cookie.

2. I see, I agree with you, the response header should not subject to the `content-type` ([HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)).

Thank you.

**Comment by jwag956** [comment]
While orthogonal to the bug itself - I don't really see why you would want to use basic auth - if this will be in un-attended mode than if I am understanding- somewhere you will hard-code in the username/password in the kiosk. You can use those credentials in an AJAX call from your vue client. This is what I do with my vue-based SPA (although I do have a login page of course). I don't see any advantage to basic auth... what am I missing?

**Comment by chiu0602** [comment]
My product is web server, with a client running browser (kiosk mode) showing a dashboard. That client will not have user interaction (and put in a safe place physically). After reboot, it is expected the browser will launch automatically. In this case, using cookie is not a good solution because it will be expired.
Furthermore, the server can be reached by others, we want only privileged users able to access the web server. That's why basic auth is used.

**Comment by jwag956** [comment]
My thought is that you need to store the credentials for that instance of the kiosk somewhere. I realize that just having the browser store it is simple. But your Vue UI can also store them in localStorage. On reboot and your UI comes up - it retrieves them from localStorage and logs in using the JSON Flask-Security login form. That will return a valid session cookie and you are good to go.

**Comment by chiu0602** [comment]
Nothing will be simpler than below command, isn't it?
`chrome --kiosk <username>:<password>@<url>`
