### ISSUE TITLE
Why CSRF only for non-mutating requests?

### ISSUE THREAD

**Issue by NMO13** [Flask-Middleware/flask-security#373]
The doc states [here](https://flask-security-too.readthedocs.io/en/stable/patterns.html): **Be careful NOT to include the csrf-token in non-mutating requests (such as GETs).**

I don't understand why. Why should GET requests not be protected by CSRF tokens as well?

**Comment by jwag956** [comment]
Read: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html

In particular:
Make sure that the token is not leaked in the server logs, or in the URL. CSRF tokens in GET requests are potentially leaked at several locations, such as the browser history, log files, network appliances that log the first line of an HTTP request, and Referer headers if the protected site links to an external site.

Unless the GET request modifies state, there is no reason to send a CSRF token.
