### ISSUE TITLE
MongoEngineUserDatastore should use a list for storing Role permissions

### ISSUE THREAD

**Issue by robobenklein** [Flask-Middleware/flask-security#374]
The following should work:

```python
class Role(db.Document, RoleMixin):
    name = db.StringField(max_length=255, unique=True)
    description = db.StringField(max_length=2048)
    permissions = db.ListField(db.StringField(), default=[])
```

However `permissions` is always set to a string, by the default UserDatastore implementation. Thus it causes an error whenever the permissions are set or changed. (cannot set a ListField to a string)

This works:

```python
class Role(db.Document, RoleMixin):
    name = db.StringField(max_length=255, unique=True)
    description = db.StringField(max_length=2048)
    # permissions = db.ListField(db.StringField(), default=[])
    permissions = db.StringField(default="")
```

However it's quite unintuitive and should either be documented as such or (IMO) the behaviour should be changed such that the MongoEngine ListField() is used properly.

Flask-Security-Too-3.4.4 https://github.com/Flask-Middleware/flask-security/blob/3.4.x/flask_security/datastore.py#L313-L322

**Comment by jwag956** [comment]
I don't really see a reason to use a list - they are always all loaded - and this keeps the implementation the same for all.
In 4.0/master - I have updated the quickstart to show it as a 255 character string field.
