### ISSUE TITLE
CSRF token not signed

### ISSUE THREAD

**Issue by NMO13** [Flask-Middleware/flask-security#375]
I read [here](https://flask-security-too.readthedocs.io/en/stable/patterns.html#using-a-cookie) that the CSRF token can be sent by a cookie. I need to go this way since I have an Angular frontend. This works basically. With the response I get a cookie csrf-token: a6ce883869b4fc7cf4d65dae20a36ede2c79ac2a. But I think this is the unsigned token. When I send this token with the next request, I get the error `'The CSRF token is invalid.'` Makes sense because I suppose `data` needs to be a signed token.
`    
    s = URLSafeTimedSerializer(secret_key, salt='wtf-csrf-token')

    try:
        token = s.loads(data, max_age=time_limit)` 
Or what do I do wrong?

**Comment by jwag956** [comment]
I am not sure what you are doing wrong - make sure you are receiving and sending the session cookie as well. When you say you are getting the CSRF cookie - what name is the cookie? that is important (as noted in the docs) since the various frontends use different default cookie names. So - for debugging - please note the session cookie being sent/received, the name of the CSRF cookie, and the name of the HTTP header that Angular is sending with the csrf-token

**Comment by NMO13** [comment]
Ok first I have to say that I did something wrong. I first tried to send the CSRF token with a cookie that I appended by myself.

     resp = make_response(render_template('register.html', form=MyForm()))
     resp.set_cookie('csrf-token', session['csrf_token'])
     return resp

I commented this code but I think my browser cached the request therefore I came to the wrong conclusion that flask-security sends it that way.
But now I don't get any CSRF-cookie at all although I set `app.config["SECURITY_CSRF_COOKIE"] = {"key": "XSRF-TOKEN"}`. When I look in the source code of flask-security I don't find any usage of the `"SECURITY_CSRF_COOKIE"`. So my new question: Is it really possible to send a CSRF token by cookie?

**Comment by jwag956** [comment]
Yes it works - I and others us it in our applications.
If you use developer tools (chrome) to view network and cookies - it will not cache things - which makes it easier to debug.
For better or worse - the code inside Flask-Security references configuration variables without the 'SECURITY_' prefix - if you search for CSRF_COOKIE you will find a bunch of references.

Note that the CSRF cookie is ONLY sent on first login response - the state of whether the CSRF_COOKIE has been sent is stored in the session cookie - so make sure you delete all your app cookies (localhost presumably) and try again.

**Comment by NMO13** [comment]
Ok it works now, thank you.
One last question: Can I login with something different than email? The user authentication seems to be hardcoded to email in the LoginForm: `self.user = _datastore.get_user(self.email.data)`

**Comment by jwag956** [comment]
Look at the new unified sign-in features in 3.4
