### ISSUE TITLE
Migrate to flask-babel

### ISSUE THREAD

**Issue by TitaniumHocker** [Flask-Middleware/flask-security#381]
**Hello!**

Thank you for maintaining this fork!
Seems like features of flask-babelex was ported to flask-babel:
https://github.com/python-babel/flask-babel/releases/tag/v2.0.0
Are you planning to migrate for using flask-babel instead of flask-babelex(its archived now)?

**Comment by jwag956** [comment]
I hadn't seen that - been waiting months for this - great news and yes - I'll get it in as part of 4.0
