### ISSUE TITLE
How to use the CSRF protection correctly?

### ISSUE THREAD

**Issue by xemedo** [Flask-Middleware/flask-security#386]
I have an Angular frontend and use flask as a backend API. So I make requests with plain JSON data and don't use WTForms.
I am using CSRF tokens to protect my endpoints. I am not a CSRF expert, therefore I was playing around with the CSRF protection in order to understand it better.
I activate CSRF using:

        app.config["SECURITY_CSRF_COOKIE"] = {"key": "XSRF-TOKEN"}

That works ok, the CSRF token is sent to the browser as a cookie as soon as I log in.

 I found out that my angular frontend is attaching this cookie as HTTP header on every subsequent request:
![image](https://user-images.githubusercontent.com/63723565/92729712-06da9b80-f373-11ea-9180-29a593e5c46c.png)

But isn't every malicious website able to extract the CSRF token now and append it to a malicious request? I wrote an HTML file that should simulate a malicous website:

 ```
<body>
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript">
    	$( document ).ready(function() {
    	        csrf_token = document.cookie.match("XSRF-TOKEN");
    	        csrf_token = csrf_token["input"].split("=")[1];
    		$("button").click(function(){
		    	$.ajax({
			  	url: "http://localhost:5000/api/v1/webapp/time",
			  	type:'POST',
			  	contentType: "application/json",
			  	xhrFields: {
    				withCredentials: true
    				},
				dataType: "json",
				 headers: {
				    "X-XSRF-TOKEN":csrf_token
			        },
	   			success: function(){
					alert("ok");
			   	},
			   	error: function(jqXHR, textStatus, error){
					//alert(textStatus);
				}
			});
		});
	});
    </script>
    
    <button></button>

</body>
```
The javascript reads the CSRF token from the webbrowser's cookie store. As soon as the victim clicks on the button, the CSRF token is  appended to the malicious request. So its very easy to bypass the CSRF protection.
What am I missing here?

**Comment by jwag956** [comment]
You have it correct - the key is that you served that malicious page from site - some some other site.
The relevant background on this is here:

https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#use-of-custom-request-headers
