### ISSUE TITLE
How to change flash message category "error" to "danger"

### ISSUE THREAD

**Issue by dixanic976** [Flask-Middleware/flask-security#387]
Bootsrap4 has no error alert.. only [danger](https://getbootstrap.com/docs/4.5/components/alerts/#examples).

Login manger has a **login_message_category** option. 

How to do it in flask-security ? 

I'm new to this library. It will be helpful to use with bootstrap4 if _message_category_ match with _alert category_.

**Comment by jwag956** [comment]
There isnt any way - and there are more than one category - error, success, info.

It would be pretty easy I would think to map from one to the other - if you are using forms - then the relevant template is _messages.html - that is the one that is doing the 'flashing'...

**Comment by dixanic977** [comment]
OK. Let me explain a bit more. As a jinja and bootstrap user, what i want to do is this.

```
{% for category, message in messages %}
<div class="alert alert-{{ category }}" role="alert">
  {{ message  }}
</div>
{% endfor %}
```

But problem is that default flash msg categories doesn't actually match with bootstrap alert categories. So i have to use if else in jinja. Just like handling "error" now. If error then danger... Something like that. 

So my request is to match those flash msg categories with bootstrap alert categories by default or give us a option to set it in config. That's all.

**Comment by TitaniumHocker** [comment]
@dixanic977 You can just create jinja filter/function/macro/context processor to map default categories to Bootstrap CSS classes categories and use it instead of standard `messages` or `get_flashed_messages`.
