### ISSUE TITLE
Resend confirmation email

### ISSUE THREAD

**Issue by NMO13** [Flask-Middleware/flask-security#388]
When a user registers with his mail address and `SECURITY_SEND_REGISTER_EMAIL=True` the user gets an email with a link for confirmation. What if the user deletes this email and needs to resend the confirmation email? How can a confirmation email be sent again?

**Comment by TitaniumHocker** [comment]
You can resend confirmation email on this route - `/confirm`.

**Comment by NMO13** [comment]
Yes thanks!
