### ISSUE TITLE
Question: translations

### ISSUE THREAD

**Issue by TitaniumHocker** [Flask-Middleware/flask-security#389]
**Hello!**

Here is some statement in documentation:
> All messages, form labels, and form strings are localizable.

I'd like to clarify. The translation has not been made, but it can be done with `pybabel` tool or something like this?
If so, is there any docs or guide how to do it?

**Comment by TitaniumHocker** [comment]
Found translations, figured out how to use it.

**Comment by jwag956** [comment]
Flask-Security ships with many translations - some more complete than others - you can see those in the translations directory. Feel free to use those, improve on them or add a new one.

Yes - this is all done via babel.

please read: file:///Users/jwag/fs/flask-security/docs/_build/html/contributing.html#updating-translations for some basic info about translations.

**Comment by TitaniumHocker** [comment]
I found that translations only work in forms, not for headings and menu:

![изображение](https://user-images.githubusercontent.com/37049574/92982794-92097d80-f4a8-11ea-88a8-87fda9af7f4a.png)

Here is my locale selector:
```python
@babel.localeselector
def get_locale(*args, **kwargs):
    return 'ru'
```
And here is attributes of my configuration object for flask app:
```python
    LANGUAGES = ['ru']
    BABEL_DEFAULT_LOCALE = 'ru'
```

What I'm doing wrong?

**Comment by jwag956** [comment]
What version of Flask-Security are you using?

**Comment by TitaniumHocker** [comment]
```bash
root@0ed92e08ed63:/var/code# pipenv run python -m pip list | grep -i security
Flask-Security-Too      3.4.4
root@0ed92e08ed63:/var/code# pipenv run python -c 'from flask_security import __version__ as v; print(v)'
3.4.4
```

**Comment by jwag956** [comment]
Hmm-  yes I can reproduce - had some bug in the past in this area - let me look further into it.

**Comment by jwag956** [comment]
Ok - using 3.4.4 and Flask-BabelEx I am not seeing this issue. Using master (soon to be 4.0) I do see the same as you report.
Still digging....

Question - did you initialize Babel? can you show the config/initialization code?

**Comment by TitaniumHocker** [comment]
Hmm, I'm using `Flask-BabelEx`:
```bash
root@f82a88aa8e77:/var/code# pipenv run python -m pip list | grep -Pi '(security|babel)'
Babel                   2.8.0
Flask-BabelEx           0.9.4
Flask-Security-Too      3.4.4
```

I'm creating `Babel` from `flask_babelex` instance in my _extensions.py_ file without any arguments, like this:
```python
from flask_babelex import Babel

babel = Babel()

@babel.localeselector
def get_locale(*args, **kwargs):
    return 'ru'
```
And then calling `init_app` method in application factory:
```python
from flask import Flask
from config import DevelopmentConfig
from .extensions import babel

def make_app():
    app = Flask(__name__)
    app.config.from_object(DevelopmentConfig)
    babel.init_app(app)

    # ... Some more code

    return app
```
This is a highly simplified example.

I can provide you access to repo of this app(it's private) if you want to see details.

**Comment by jwag956** [comment]
Ok - this is and has been a confusing area - something Flask-Babel/Ex never really figured out (or I never figured out!)
Try initializing babel with:
babel.init_app(app, default_domain=security.i18n_domain)
where 'security' is the result of initializing Flask-Security - see if that fixes things.

This isn't ideal - since it means that all your forms will default to Flask-Security domain - but at least we'll know the issue.
From what research/testing I have done - this is a fundamental problem with Flask-BabelEx - not really supporting 3rd party libraries.

I started a solution - by exporting _fsdomain() as a Jinja function that forces using the Flask-Security domain - but haven't yet  converted all templates over to that.

**Comment by TitaniumHocker** [comment]
Only app instance can be provided to ``init_app`` method, so I set this argument on creation of `Babel` instance, but nothing changed.

**Comment by TitaniumHocker** [comment]
I also found something interesting, don't know is it normal or not.
In my _extensions.py_:
```python
security = Security()
breakpoint()
babel = Babel(default_domain=security.i18n_domain)
```
and:
```bash
(Pdb) security
<flask_security.core.Security object at 0x7feefbd9a1f0>
(Pdb) security.i18n_domain
(Pdb) security.i18n_domain is None
True
(Pdb)
```

**Comment by TitaniumHocker** [comment]
Sorry, I forgot to call `init_app` in app factory after this.
Translations started working:
![изображение](https://user-images.githubusercontent.com/37049574/92988214-07d60f00-f4d2-11ea-85f4-6f7c4e8d5abc.png)

**Comment by TitaniumHocker** [comment]
> (Sorry about the paste of code without colors, not sure how to do so here)

Use this:
```
\```python
from code import Code
# your code here
\```
```
without `\` symbol.

**Comment by jwag956** [comment]
Hmm - I think this is a bug.... Note that 'subject' isn't part of the template - so doesn't get translated with the body.
Looks like flask_security::utils.py::send_mail is just passing the subject through w/o calling gettext to translate it.

If you just have one language you can of course change the configuration parameter e.g. EMAIL_SUBJECT_PASSWORD_NOTICE... that doesn't work for multiple languages.

**Comment by jazzmaister** [comment]
Looks like a bug indeed. I will be forcing language on the email subject for now, but I ultimately need it to be multilingual, so will be looking forward to the update.
Thanks!
