### ISSUE TITLE
Proposal: redirect to /confirm page after "mail not confirmed yet" error message

### ISSUE THREAD

**Issue by SnaKyEyeS** [Flask-Middleware/flask-security#391]
Currently - to my knowledge - there is no way to automatically redirect the user after he gets a "you need to confirm your mail address" message.

As I see it, there would be some sort of an option to enable automatic redirect to the /confirm endpoint after the users tries to login with an unconfirmed mail address (eventually with a mail prefill as well).
To ensure non-changing behavior with the current Flask-Security version, it could be set to a "non-redirect" by default.

I would gladly look into implementing this feature/option myself if you think it is a pertinent/good idea ! :-)

**Comment by jwag956** [comment]
Note quite sure I understand - there is no /confirm form/endpoint - and if there was - what would it do? The confirmation email link has a very long token in it - which I suppose could be cut-n-pasted but not sure the value.

Could you give some more background on your use case? Like - what would the new 'confirmation' form look like? would it accept the token or just have text?
Currently, lack of confirmation is considered an error and the calling form is sent back to the client.

**Comment by SnaKyEyeS** [comment]
Sorry, I meant the send_confirmation endpoint. It would simply be an option to setup a « post_requires_confirmation_view » when someone tries to login. 

So, instead or returning an error to the client as you say, it would redirect to the send_confirmation page, eventually with a pre-filled email field.

**Comment by jwag956** [comment]
Seems a reasonable improvement - I will point out the the current 'menu' already has a 'Confirm Account' button which takes you to that page - so you would flash('Email needs confirmation') then redirect?

Sure - put up a PR. (don't forget tests!).

**Comment by jwag956** [comment]
closed by #393
