### ISSUE TITLE
How to use different names for User and Role classes?

### ISSUE THREAD

**Issue by PhiPie** [Flask-Middleware/flask-security#395]
Congrats for doing an excellent job here.

I'm using SQL Server as database. There are some limits in SQL server to create a tables like "user" and role as these are reserved words. So, how can I use different names for User and Role classes so that I could have different tables in my database for these classes? Let's say flask_Users and flask_Roles instead of User and Role.

Many Thanks

**Comment by jwag956** [comment]
What ORM are you using? things like SQLAlchemy lets you specify the table name independent of the class name..

**Comment by PhiPie** [comment]
I haven't tested with SQL Server yet. But, I know that in SQL server I'm not able to create tables like user and role. 

In example fsqlalchemy1, I tried to use different name for User table as follow:

class User(db.Model, fsqla.FsUserMixin):
    __tablename__ = 'FlaskUsers'
    blogs = db.relationship("Blog", backref="User", lazy="dynamic")
    pass

But then, I got the following errors in browser:

sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'roles_users.user_id' could not find table 'user' with which to generate a foreign key to target column 'id'

**Comment by jwag956** [comment]
I believe the backref wants a tablename - not a class name!

**Comment by PhiPie** [comment]
I changed the User class as follow:

class User(db.Model, fsqla.FsUserMixin):
    __tablename__ = 'FlaskUsers'
    blogs = db.relationship("Blog", backref="FlaskUsers", lazy="dynamic")
    pass

But, now I'm getting following error in browser:

sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship User.blogs - there are no foreign keys linking these tables. Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.

It seems the issue is coming from this line:

fsqla.FsModels.set_db_info(db)

Which refers the code below in class FsModels:

def set_db_info(cls, appdb):
        """ Initialize Model.
        This needs to be called after the DB object has been created
        (e.g. db = Sqlalchemy())
        """
        cls.db = appdb
        cls.roles_users = appdb.Table(
            "roles_users",
            Column("user_id", Integer(), ForeignKey("user.id")),
            Column("role_id", Integer(), ForeignKey("role.id")),
        )

The ForeignKey is using table "user", which doesn't exist. Because I've changed the table for User class from "user" to "FlaskUser".

**Comment by jwag956** [comment]
Good catch - for now you'll need to create your own models (you can cut and paste fsqlalchemy). I'll look into supporting custom class names (should be pretty easy).

**Comment by PhiPie** [comment]
Thanks for looking into supporting custom class names. That would be perfect.

I copied the models from fsqla.py and fsqla_v2.py to the example fsqlalchemy1. It is working now with "FlaskUsers" as table name for User model, instead of "user". But, any name can be chosen for User model's table name. Just need to replace "FlaskUsers" with new name. Not a good practice though, as User model's table name is hardcoded. But at least it works now with any table name, and this is exactly what I was looking for.

I'm attaching the full code for the updated example fsqlalchemy1 with models from fsqla and fsqla2.


[flask-security-example-fsqlalchemy.txt](https://github.com/Flask-Middleware/flask-security/files/5336994/flask-security-example-fsqlalchemy.txt)
