### ISSUE TITLE
Two authentication mechanisms for different user sets

### ISSUE THREAD

**Issue by albatros69** [Flask-Middleware/flask-security#406]
Hello,
I have a particular use case for an application: I have a set of normal users (about a dozen, with login/pwd authentication) who perform all kind of actions in the application (CRUD and so on).
But I also need some other users (~100) to perform one-off actions like filling forms. For this set of users, I would like to use passwordless authentication, asking them to scan a qr-code (containing the URL and the token in a GET attribute) and then fill in the form. The token would be valid for a couple of hours.

Would this be something I can do with flask_security? Currently, the two sets of users are in two different tables in the database.

**Comment by jwag956** [comment]
I think FS can handle that.

First - it will be much simpler if there is a single user table - using either a Role or additional column to differentiate the 2 groups of users. Role would also help protecting various API endpoints.

FS as of 3.4 has a new feature called unified signin - which provides a single form (and configuration) that allows for a variety of identity/passcode options including email/password, phone/code, username/code, where code can be a magic link delivered via email, a SMS code or an authenticator code.

Now - today you can't configure some users to use one mechanism and other a different mechanism. That could be handled by subclassing UnifiedSigninForm and checking the user role/column against the self.authn_via field (that records how the user authenticated).

Now, if you don't want to use SMS or authenticator apps or email links and want to write your own - that might not be a good fit...

**Comment by albatros69** [comment]
Thanks for your answer. I will start my development with FS and dive deeper into this UnifiedSignin functionality.

One remaining question though (and I don't ask for a commitment here, but a ballpark estimate): when do you plan to release 4.0? I'm asking because I'm banging my head around the Babel/BabelEx conflict and I see this is addressed in this version.

**Comment by jwag956** [comment]
There is a 4.0.0rc1 up on pypi which should be more than solid enough for development. I have just one more potential backwards compat change I want to consider - otherwise it is done.

Please use this issue for continued questions - if you find any bugs - feel free to file them as separate issues.

**Comment by albatros69** [comment]
Thanks a lot for your support: I just picked up 4.0RC1 from PyPi and started the integration!

I will start the implementation, and I will keep you updated about the potential issues in separate github entries, should this happen.

**Comment by jwag956** [comment]
Hope all is going well - I am working to wrap up and push official 4.0 in the next few days (hopefully!).
