### ISSUE TITLE
Inconsistent behavior from create_user()

### ISSUE THREAD

**Issue by eric-gunn** [Flask-Middleware/flask-security#412]
When `UserForm` is populated via web form, validated, and then a new dict is created using data from `UserForm`, the new dict is passed to `user_datastore.create_user()` to unpack and create a new user. When this is done in the Flask app, the roles list for the user has two `null` items:

Dict passed to `user_datastore.create_user()`:
```python
{
    'email': 'bob.smith@example.com',
    'first_name': 'Bob',
    'last_name': 'Smith',
    'password': '$2b$12$QGSlkF99yO8mpeq9fMZmHua905gF3FZHCjTQSeMwqEbBajS9qtxx6',
    'roles': ['admin', 'superuser-admin'],
    'user_roles': ['admin', 'superuser-admin']
}
```

`new_user()`:
```python
@app.route('/user', methods=['POST'])
@auth_required()
def new_user():
    user_form = UserForm()

    if user_form.validate_on_submit():
        print(user_form.data)
        team = user_form.data['team']
        team_role = user_form.data['team_role']
        print(team_role)
        admin_role = '{}-admin'.format(team)
        print(admin_role)
        
        if team_role == 'admin':
            rl = [team_role, admin_role]
        else:
            rl = [team_role]

        print(rl)

        u = {
            'email': user_form.data['email'],
            'first_name': user_form.data['first_name'],
            'last_name': user_form.data['last_name'],
            'password': hash_password('ChangeMe123!'),
            'roles': rl,
            'user_roles': rl
        }
        print(u)
        user_datastore.create_user(**u)
```

Resulting data in Mongo:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/15822356/100547883-cb8f9080-322e-11eb-889b-e74aa8f1af81.png">

**When the user is created in Python REPL, however, with the _same_ dict, the user is created as expected with `user_datastore.create_user()`:**

Python REPL:
```
>>> from app import *
>>> u = {'email': 'bob.smith@example.com', 'first_name': 'Bob', 'last_name': 'Smith', 'password': '$2b$12$QGSlkF99yO8mpeq9fMZmHua905gF3FZHCjTQSeMwqEbBajS9qtxx6', 'roles': ['admin', 'superuser-admin'], 'user_roles': ['admin', 'superuser-admin']}
>>> user_datastore.create_user(**u)
<User: User object>
>>> 
```
Resulting data in Mongo:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/15822356/100547926-1d381b00-322f-11eb-9a6b-4553bf6cdd9c.png">

Hopefully I'm missing something obvious. Hoping someone can help.

### Reference classes

Role class:
```python
class Role(db.Document, RoleMixin):
    name = db.StringField(max_length=80, unique=True)
    description = db.StringField(max_length=255)
    permissions = db.StringField(max_length=255)
```

User class:
```python
class User(db.Document, UserMixin):
    email = db.StringField(max_length=255)
    password = db.StringField(max_length=255)
    first_name = db.StringField(max_length=255)
    last_name = db.StringField(max_length=255)
    active = db.BooleanField(default=True)
    fs_uniquifier = db.StringField(max_length=255)
    confirmed_at = db.DateTimeField()
    roles = db.ListField(db.ReferenceField(Role), default=[])
    user_roles = db.ListField(default=[])
```

UserForm class:
```python
class UserForm(FlaskForm):
    first_name = StringField('Name', validators=[DataRequired()])
    last_name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    team_role = SelectField('Role', validators=[DataRequired()], choices=[('', 'Select role'), ('admin', 'Admin'), ('user', 'User')], default=[''])
    teams = [role['name'] for role in mdb.role.find() if role['name'] not in exclude and role['name'][-5:] != 'admin']
    teams.insert(0, 'Select team')
    team = SelectField('Team', validators=[DataRequired()], choices=teams, default=['Team'])
```

**Comment by jwag956** [comment]
Hmm - I think the issue is that create_user (which calls _prepare_create_user_args internally) is actually modifying the
list that is passed in - changing them to role objects.
So your examples aren't quite the same - I'll bet the REPL version will fail if you pass the SAME list in for both roles and user_roles.

Arguably not very friendly - I'll add some documentation.

**Comment by eric-gunn** [comment]
@jwag956 wouldn't the lists already be the same, since the dict that contains the list is the same? The `print(u)` statement near the end of the `new_user()` function is what output the dict I copy/pasted into the REPL. The dict `u` is the dict that was also passed into the `create_user()` function in the app. If the `create_user()` function modifies the list in the containing dict `u` in the app, why wouldn't that be the case for the `create_user()` function in the REPL? After starting the REPL, I ran `from app import *`, so I assume the `create_user()` functions are the same. What makes the examples different, and why does the REPL example perform as expected, while the app instance doesn't? I understand that `create_user()` modifies the role lists that are passed in, but I don't understand why that doesn't happen in the REPL, given the same dict passed to the same function.

**Comment by jwag956** [comment]
I might not have been clear - or I am confused! But in the REPL case - you have 2 distinct lists with identical contents - with the other case - you have ONE instance of the list.

Try adding a user_roles = r1.copy()

**Comment by eric-gunn** [comment]
Ah, I understand. I'll give that a shot tomorrow and follow up.

**Comment by eric-gunn** [comment]
@jwag956 you're quite correct. The difference wasn't obvious to me before, but makes sense. That being said, is there a method that will return a list of roles that a User has? I created `user_roles` as a quick fix, but I wonder if there's a more elegant solution. Thanks for the help!
