### ISSUE TITLE
3.4.5 security advisory

### ISSUE THREAD

**Issue by Avamander** [Flask-Middleware/flask-security#427]
In order to speed up updating flask-security as a dependency, could you please publish a security advisory on GitHub?

**Comment by Avamander** [comment]
@jwag956 https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory

**Comment by jwag956** [comment]
WIll do - have you done this?is it worth asking github to assign a CVE? or just publish it?

**Comment by Avamander** [comment]
> have you done this?

Not using GitHub.

> is it worth asking github to assign a CVE? 

Yes.

> or just publish it?

Publish it for now, update it when you get a CVE. This potentially helps reduce the time it takes for the information to reach the correct people.

**Comment by jwag956** [comment]
Done (for both).

**Comment by Avamander** [comment]
@jwag956 I got a dependabot alert today, so it worked. :tada:
