### ISSUE TITLE
commit in login messing with tests

### ISSUE THREAD

**Issue by openbrian** [Flask-Middleware/flask-security#430]
I see in def login() in views.py there's a call like this
```
after_this_request(_commit)
```
This COMMIT is messing with transactions for my automated testing.  Do you really need it?

My unittest tests are organized like this.  Each test class is a transaction, and each test is a nested transaction.  All of them eventually get rolled back to clean the database.

1. setUpClass() -- db.session.begin_nested() -- SAVEPOINT sa_savepoint_1
    1. setUp() db.session.begin_nested() -- SAVEPOINT sa_savepoint_2
    2. login -- RELEASE sa_savepoint_2 !?!?!!?!?
    3. do stuff
    4. assert stuff
    5. tearDown() -- db.session.rollback() - ROLLBACK to SAVEPOINT sa_savepoint_1 ?!?!!?
    6. setUp()
    7. ...
    8. tearDown()
    9. setUp()
    10. ...
    11. tearDown()
2. tearDownClass() -- db.session.rollback()

**Comment by jwag956** [comment]
Are you asking whether FS needs to write to the DB - yes!

I think you  are making things very complex - use in-memory sqlite DB and initialize it on every test - that way you get reproducability.

**Comment by openbrian** [comment]
Can you just do a session.flush() and not a commit?

**Comment by openbrian** [comment]
I removed the commit and all tests pass except for those in test_trackable.  authenticate() is one call with the client, and datastore.find_user() is in a separate app_context().  I see why FS needs to commit *for the test to work*.  That's just a consequence of using Flask's test_client().  A unit test could be performed without an application context, if the tracking code in util.py (lines 118 - 128) were factored out into its own method.  Let me know if you would consider a PR.

IMHO the global variables and application context in Flask is a disservice to proper unit testing.

Regardless of testing, in an application, FS is committing a transaction it didn't start.  It's an unfortunate side effect.
