### ISSUE TITLE
3.4.5 regression: cannot test different users in incognito window

### ISSUE THREAD

**Issue by louking** [Flask-Middleware/flask-security#431]
I test different user/role behavior using chrome incognito window. I recently upgraded to flask-security-too 3.4.5 from 3.3.3.

I noticed that I can only log in to one user now in the incognito window. Logging into other users throws me back to the login view. Not sure what is special about that user but looking at the database I notice it is the only user with `fs_uniquifier` set. Not sure if that is relevant, of course, and I didn't debug enough to figure out how this field is supposed to get set.

I reverted to 3.3.3 and was able to log in to any user in the incognito window.

Please let me know if I can supply additional information to help resolve this.

**Comment by jwag956** [comment]
fs_uniquifier (in 3.4.4) was added as an optional alternate id (w.r.t. Flask-Login). If you have fs_uniquifier in your user model then it will be used for ALL users. So if your user doesn't have one - it won't be able to log in.
When you create your user for the first time - it will set the fs_uniquifier.
Any chance you are reusing a DB with old users in it?

**Comment by louking** [comment]
Yes there are old users in the database. That will be the case when I upgrade my production application as well. I'm not clear how this field got created or if an upgrade script was run behind the scenes which missed the existing users.

I want to mention that I created a user after the upgrade to 3.4.5 but that user doesn't have fs_uniquifier set. Not sure how the other user did get it set.

I also might mention is that my users are in a separate database from my application, per

```
class RealDb(Config):
    def __init__(self, configfiles):
        if type(configfiles) == str:
            configfiles = [configfiles]

        # connect to database based on configuration
        config = {}
        for configfile in configfiles:
            config.update(getitems(configfile, 'database'))
        dbuser = config['dbuser']
        password = config['dbpassword']
        dbserver = config['dbserver']
        dbname = config['dbname']
        # app.logger.debug('using mysql://{uname}:*******@{server}/{dbname}'.format(uname=dbuser,server=dbserver,dbname=dbname))
        db_uri = 'mysql://{uname}:{pw}@{server}/{dbname}'.format(uname=dbuser, pw=password, server=dbserver,
                                                                 dbname=dbname)
        self.SQLALCHEMY_DATABASE_URI = db_uri
        # https://flask-sqlalchemy.palletsprojects.com/en/2.x/binds/
        userdbuser = config['userdbuser']
        userpassword = config['userdbpassword']
        userdbserver = config['userdbserver']
        userdbname = config['userdbname']
        userdb_uri = 'mysql://{uname}:{pw}@{server}/{dbname}'.format(uname=userdbuser, pw=userpassword, server=userdbserver,
                                                                 dbname=userdbname)
        self.SQLALCHEMY_BINDS = {
            'users': userdb_uri
        }
```

**Comment by louking** [comment]
and for completeness flask-security is set up here

https://github.com/louking/members/blob/e005d9ed46149cf4e7d196b9a67572eb4cd6c1e9/members/__init__.py#L132-L135

**Comment by jwag956** [comment]
Once you add fs_uniquifier to your usermodel - all future users will have that value automatically filled in.

In the release notes for 3.3.0 it goes into detail about the schema AND data migration that needs to occur (look for DB Migration heading) which gives details if you are using alembic for managing schema upgrades.

Someone had to add fs_uniquifier to your UserModel! (peeking at your code a bit - looks like it was added to loutilities here:
https://github.com/louking/loutilities/commit/29154fe27258a5f745c384a99337de70dd7753b0)

**Comment by louking** [comment]
Uh, ok. I'm that "someone" of course. :)

It looks like fs_uniquifier was added when I started using flask-security for single sign-on support back in March 2020. But only one user has it set which is the user who gets automatically created when the database got set up. I definitely created a user yesterday after I migrated to 3.4.5, and that user doesn't have fs_uniquifier set, so I must be creating users incorrectly, but logins for users without fs_uniquifier being only stopped working now. so I didn't realize my code was broken.

I'll do some research by reading the 3.3.0 release notes and let you know what I find. What's the best way to go back and forth on this? Continue here in this issue? On stackoverflow? By email?

**Comment by louking** [comment]
It looks like I'm just shoving the data into the database, i.e., not using the methods defined in https://flask-security-too.readthedocs.io/en/stable/api.html#datastores, which is probably the problem. I guess I have to refactor my use of User, Role to use these methods.

**Comment by jwag956** [comment]
Right - use user_datastore.create_user() to add users - this will insulate you from other changes possibly. As part of backwards compatibility, FS makes some decisions based on whether a feature/column is available - so adding columns can change behavior (there is another one in 4.0 that is similar - fs_token_uniquifier)

We can just use this issue thread until you have things under control.

**Comment by louking** [comment]
I think I got my User definition from https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-sqlalchemy-application-with-session

Shouldn't the `User.fs_uniquifier` be shown with `nullable=False`? That would remove the need to set that in the migration.

And shouldn't (or couldn't) UserMixin have had all the attributes needed? (But that wouldn't be backwards compatible, so I'm not recommending it now).

**Comment by louking** [comment]
I'm also not using `create_role()`, `add_role_to_user()`, `activate_user()` and their converse methods. I see the current code just manipulates the database which is what my code does. How concerned are you that these methods may add additional value (similar to [fs_uniquifier initialization](https://github.com/Flask-Middleware/flask-security/blob/9c874d9fbff0d08f6b6af9e769a7fcec82e4dd4c/flask_security/datastore.py#L147)) so I need to modify my code to use these methods for role / activation manipulation?

**Comment by louking** [comment]
I got this working using `create_user()`, via https://github.com/louking/loutilities/commit/78cee3ab41d4e9f0ec4f72ecd7838c94cfa3a5f9 and https://github.com/louking/members/commit/8866d254d8ce3ebcc556dcfbc80d051f62944ed9. Please feel free to close this issue unless you have more information for me regarding my last two comments.

**Comment by jwag956** [comment]
Glad you got it working - and I think using the API is a better approach - although it isn't clear when a change like this will happen again!

The Quickstart documentation setting fs_uniquifier nullable=false was updated in the 4.0 docs (soon to be released).

The usermixin can't actually specify attributes since FS supports many different backend DBs - each of which has a different way of expressing columns.

activate and roles are pretty simple - however I still think using the API is a better choice.

Your commit looks fine to me.

Thanks for using Flask-Security-Too!

**Comment by louking** [comment]
> The usermixin can't actually specify attributes since FS supports many different backend DBs - each of which has a different way of expressing columns.

Oh that's right. Thanks for your patience. 

Will look at API for role management as well, will be lower on my priority list but if I create an issue it'll get done eventually.
