### ISSUE TITLE
''Specified user does not exist": email validation fails

### ISSUE THREAD

**Issue by virajut** [Flask-Middleware/flask-security#442]
This error is the result of having `SECURITY_EMAIL_VALIDATOR_ARGS` with default option.

**Steps to reproduce:** 

1. Register a user with the email id having custom domain
2. Try to login with that email id
3. It throws an error ''Specified user does not exist"

The cause of this is the email_validator package which is being used for email validation. By default, It checks whether email is deliverable to the entered email address or not and it's not something you would want to in all the cases like when you're doing development from local machine, when you're using fake email address just for the testing purpose. In such cases, It is hard to figure out what is going wrong with the email and you will have to check the `email_validator` package functionality in order to come to the conclusion that we need to set a parameter in order to bypass that check. Which would be setting up `SECURITY_EMAIL_VALIDATOR_ARGS = { "check_deliverability" : False }`. 

Wouldn't it be a good option to set `{ "check_deliverability" : False }` as a default option instead of `None` or having those parameters described on the documentation page?

**Comment by jwag956** [comment]
Good point and in FS tests it in fact does set that variable. I'll add it to the docs in a few places.
Thanks for pointing that out.

**Comment by jwag956** [comment]
In your step 1 - how did you 'register' the user - using /register, CLI, or directly calling user_datastore.create_user?

**Comment by virajut** [comment]
It was by directly calling `user_datastore.create_user`

**Comment by jwag956** [comment]
Added documentation in #467
