### ISSUE TITLE
Redirect logged-in user from /reset to /change  view

### ISSUE THREAD

**Issue by nhoening** [Flask-Middleware/flask-security#446]
I might be missing that this is a security feature.

But I'd like to send a reset link to users to suggest they change their password (maybe I believe their password might have been compromised). Actually I have a view for that purpose where I replace their password with a random string and then send them the reset link.

But if the user has an active session, the reset link gets redirected (302) to the base URL.

If you tell me it's a security feature I could not think of by myself, I'm satisfied :)

**Comment by jwag956** [comment]
Well - since all time - the /reset endpoint is for non-authenticated users only and the /change endpoint is for authenticated users to change their password. I don't think it's a security issue - changing it would require some careful  study of the view.

I can see how this might be useful.

**Comment by nhoening** [comment]
Thanks, that helps to understand. Of course, I don't know when a user will use the link, so my feature requires that I log them out (which is probably also something I can do server-side)

**Comment by nhoening** [comment]
I suggest a change which would make my problem go away. Feel free to close if there is a good reason not to pursue.

**Comment by jwag956** [comment]
I am still thinking about this - in most sites I know - if they want you to change your password - they require that at next login, and presumably they can (in emergencies) forcibly log you off (but that is really rude).
Just sending someone a reset password link and asking them to click on it would be considered by many people to be spam - we all try to train folks NOT to click on links in emails - especially ones that would change credentials!

It would seem a more interesting feature would be a 'require change password at next login' or more generally - support different password aging schemes. FS already has a way for the admin to forceably log out and revoke all sessions, password, tokens etc.

**Comment by nhoening** [comment]
Yes, I did discover and use  `user_datastore.reset_user_access(user)` recently - very nice!

The feature you describe sounds great, but a bigger work item than the small change I propose here. I suggest opening a new ticket for that and closing this one, with my proposed change or without :)

**Comment by jwag956** [comment]
As suggested - I am going to close this particular issue - and will consider adding a more generic password aging etc mechanism in the future.
