### ISSUE TITLE
ValueError: Flask-Babel or Flask-BabelEx is installed but not initialized

### ISSUE THREAD

**Issue by TheDavidFactor** [Flask-Middleware/flask-security#447]
I'm attempting a drop in replacement of Flask-Security with Flask-Security-Too, I expect there to be a bunch of stuff I have to work thorugh. My issue with the error message in the subject is that I have neither Flask-Babel nor Flask-BabelEx installed so this error message is incorrect. That is all.

Now that you are aware of the issue, carry on.

BTW, awesome project thanks for picking up the Flask-Security baton.

**Comment by jwag956** [comment]
Thank you .. Hmmm - I can't reproduce that - are you sure you don't have either of them in your site-packages?

**Comment by TheDavidFactor** [comment]
I'm using pipenv and neither were listed in Pipfile.lock, also I was able to install Flask-Babel and it installed and was then available. However, dumb me, I didn't think to try an import of either package before installing Flask-Babel so I can't be 100% sure. I'm closing this and apologize for not having better troubleshooting information.
