### ISSUE TITLE
Idea: Extending "SPA"-like behavior for Mobile Apps?

### ISSUE THREAD

**Issue by chr0nikler** [Flask-Middleware/flask-security#449]
Hi. To get right to the point, I posted my problem [regarding my password reset woes on SO](https://stackoverflow.com/questions/66255958/how-to-set-password-reset-url-to-a-mobile-deeplink-using-flask-security)

But the broader topic for discussion is how to use FlaskSecurity as a JSON-base service when interfacing with a mobile app. Now, on the whole, it's not so different: mobile service makes requests just like an SPA (or any UI service) would would make. But there are some pain points where the decisions made in FlaskSecurity are made strictly around the idea that it is serving or servicing a browser based application. I feel like there's an opportunity to increase flexibility (like how behavior with `spa` was provided) that could make it more amenable to mobile applications. Password reset is my immediate sticking point, where I can't deeplink into the mobile app immediately, nor can I decide when token validation occurs, but you all know more about the ecosystem and have better judgement for how this may fit into the broader scheme.

**Comment by acidjunk** [comment]
I remember I had a discussion with Chris about token vs cookie. And switched to cookie based auth after that. For my webapp this works ok (better/safer/easier).

I'm now also working on a mobile app: but It seems quite difficult to use Cookie based auth with React native (expo). You basically have to implement it yourself; store it and append it to future outgoing requests.

https://forums.expo.io/t/how-can-i-use-cookies-without-eject/917/8

**Comment by TitaniumHocker** [comment]
First of all read [this](https://flask-security-too.readthedocs.io/en/stable/spa.html) and [that](https://flask-security-too.readthedocs.io/en/stable/patterns.html#csrf).

**Comment by jwag956** [comment]
Always interested in making FS more useful. You are correct that FS originally was written around browser and forms, then extended to handle JSON (even though internally it is still form based), then extended some more to handle the flexible routing requirements of a (browser-based) SPA. I'll look into this more - however I want to at least point out to some of the commenters here that there are different things in FS called token which can be confusing.

90% of FS API is simple request/response that uses either a cookie or authentication token for authentication. @acidjunk - our discussion was around browser based access where sessions and CSRF are important (whether using forms or SPA). However for mobile apps I wouldn't think that applies - (mobile web servers of course YES). So using an authentication token for auth should be fine.

There are 2 places - confirmation and reset password that of course have a different workflow - the user initiates a request and an email is sent which contains a signed and timed token containing the identity of the caller. Those are completely designed around standard email readers and URL redirection to a web server. However I think @chr0nikler FS can do what you want - I will answer that over on SO.

**Comment by chr0nikler** [comment]
@jwag956 thank you for answering my SO post extremely quickly and sufficiently. 

The way I see it, a mobile app is at the far end of the spectrum in terms of what a Flask app with FS might try to service, but as long as ` default_want_json` does the job of just returning json instead of redirects, I think that's good enough.

@jwag956 curious how you would specifically go about the two flows you mentioned then? Allow for just link configuration, or some higher logic about what kind of email is being sent? The only issues I see here right now are the email flows

**Comment by jwag956** [comment]
Quick thinking - first - there is no reason not to allow for customization of the URLs sent in the email - I think its as easy as sending the 'token' into the template along with the computed link - if an app needs to fashion their own URL - they can create their own template and done.

At a higher level - in 3.4 I introduced a unified signin feature that replaces email/password with identity/passcode - so it is easy to have say username, phone number as identity, and passcode - either password, magic link (code via email) code via SMS or code via authenticator app. This allows for not even having a stored passwords, and alternative identities.
The one place where this feature isn't quite complete is that registration/confirmation/reset still all rely on email as the core part of the workflow. I need to think about this more w.r.t. how to change this - for example it would be pretty easy to replace confirmation email with a confirmation 'code'.  I haven't seen many examples of account recovery just using a phone...

**Comment by chr0nikler** [comment]
>Quick thinking - first - there is no reason not to allow for customization of the URLs sent in the email - I think its as easy as sending the 'token' into the template along with the computed link - if an app needs to fashion their own URL - they can create their own template and done.

Agreed, 💯 
> I haven't seen many examples of account recovery just using a phone...

Same. I know I'm unique in this instance, and would actually prefer to move to a "reset password" flow within the app that is instigated once identity is recognized via a code received via text, if its needed at all (e.g, the experience is web and mobile). I saw the unified experience, and I definitely think that's the way to go.
