### ISSUE TITLE
SECURITY_EMAIL_SUBJECT_xxx customized subject gives "TypeError: unhashable type: '_LazyString' "

### ISSUE THREAD

**Issue by amkrtchyan-tmp** [Flask-Middleware/flask-security#450]
Recently i have upgrade my app to flask_security_too 4.0.0. 
In my app I am using localization. All local messages works fine except customized subject messages.

For example in my app config i am using:
`
...
from flask_babelex import lazy_gettext as _l
...

SECURITY_EMAIL_SUBJECT_REGISTER = _l("Some custom subject")
...
`
When app sending registration confirmation email i am getting following exception:

`
TypeError: unhashable type: '_LazyString'
....
`
When i am changing my code to this:
`
...
from flask_babelex import gettext as _
...

SECURITY_EMAIL_SUBJECT_REGISTER = _("Some custom subject")
...

`
I am not getting any exception, but email subject is not translated.

In version flask-security-too 3.4.4 email subject translations works fine.

**Comment by jwag956** [comment]
Thanks for upgrading to 4.0.0.

Specifically I made a change to 'fix' email subject  not getting translated! Prior to 4.0 the subject wasn't xlated by FS at all - now it is as part of building the email message.

 Each of the EMAIL_SUBJECT_XXX config variables are now extracted and are part of the default .pot file shipped with FS - so should already be being translated (except that most languages haven't had their xlations updated recently).

So - as part of building the email - it now calls <domain>.gettext on the string - so don't pass in a gettext! Try just passing in a string. Where <domain> is the what babel returns based on I18N_DOMAIN configuration (default: flask_security).

So I think what should work - if you are OK with the default SUBJECT - just add the translation to the appropriate .po file.
If you want a custom subject - I will need to look into that - I might have made that much more difficult.

**Comment by amkrtchyan-tmp** [comment]
Thank you Chris for quick reply. 
Yes, default subject messages are showing translated.
For now I will manage with default subject messages before then.
Thanks again :-)
