### ISSUE TITLE
Is signup and login with username instead of email possible? 

### ISSUE THREAD

**Issue by aquatic7** [Flask-Middleware/flask-security#466]
Is it possible to do so email is not required at all, if I want a user to signup and login with username instead?

**Comment by jwag956** [comment]
Simple answer - yes I believe so - however it isn't a out of the box supported option.

There are 2 slightly different models - registering with email and username, but login with just username or
not have any email at all.

Without email at all then of course confirmation and recovery (lost password) aren't available. (someday maybe we can add confirm with SMS).

If you don't want email at all - you will need to define your own RegisterForm and set that at app initialization time. Of course you need your own Registration template as well.

Then - change USER_IDENTITY_ATTRIBUTES and remove email and add username (See the documentation)

At this point you have 2 options - use the standard LoginForm - and even though the field says 'email' enter the 'username. Or use the newer unified sign in feature that already has generalized the form as 'identity'....

Ok - that should get you started!

**Comment by aquatic7** [comment]
@jwag956 how do I change USER_IDENTITY_ATTRIBUTES and remove email and add username? 
I can't see in documentation (https://flask-security-too.readthedocs.io/en/stable/configuration.html#SECURITY_USER_IDENTITY_ATTRIBUTES) how to do this? Or.. maybe I just don't understand it.

**Comment by jwag956** [comment]
something like this:
```
    SECURITY_USER_IDENTITY_ATTRIBUTES = [
        {"email": {"mapper": uia_email_mapper}},
        {"username": {"mapper": uia_username_mapper}},
    ]
```

(you can remove 'email') And you define uia_username_mapper as so (be sure pip install bleach):

```
def uia_username_mapper(identity):
    # we allow pretty much anything - but we bleach it.
    return bleach.clean(identity, strip=True)
```

**Comment by jwag956** [comment]
Built-in support for username has been added. Note that email is still required for registration.

pr: #504

**Comment by hrishikeshrt** [comment]
I think there needs to be changes to the login form as well? Currently, even if `USERNAME_ENABLE` is True, it still forces one to enter an email address while trying to log in. (Validator demands a valid e-mail address).

Prior to this, I was using 

```python
app.config['SECURITY_USER_IDENTITY_ATTRIBUTES'] = [
    {'email': {'mapper': uia_email_mapper}},
    {'username': {'mapper': uia_username_mapper}}
]
```
with a custom `uia_username_mapper` and custom login and registration forms,

```python
class CustomRegisterForm(RegisterForm):
    username = StringField('Username', [Required()])

    def validate(self):
        if user_datastore.find_user(username=self.username.data):
            self.username.errors = ["Username already taken"]
            return False

        if not super(CustomRegisterForm, self).validate():
            return False

        return True


class CustomLoginForm(LoginForm):
    email = StringField('Username or Email', [Required()])

```

Was hoping I can get rid of those things now.
Shall I send a pull request for this? Looks like a change to LoginForm should fix things?

**Comment by jwag956** [comment]
So - you should be able to get rid of your CustomRegistrationForm - right?
As for the login form - historically, although the field name is 'email' you have been able to type in an email or whatever else you want, and FS will query the DB based on the IDENTITY_ATTRIBUTES. So some 'identity' is required - but your users can just type in their username and it should work (you probably already have your own template).
Note that the new 'unified signin' feature make this more generic by calling it an 'identity' - which can be configured to be an email, username, phone number etc.

So - I am not sure why you are seeing an email validation error?

**Comment by hrishikeshrt** [comment]
If I use `CustomLoginForm`, then it would work yes. If I get rid of both however, the default `LoginForm` contains

```python
    email = EmailField(get_form_field_label("email"), validators=[email_required])
```
which forces the field to be verified as a valid `email`.
Since now there is first class support for login with username, when that option is set the LoginForm should treat is as a StringField instead of EmailField.

**Comment by jwag956** [comment]
Ahh yes - good point. It was recently changed to EmailField to have html5 input validators - which are a great help on mobile devices - so in the normal case I wouldn't want to change that. So we probably need something like the RegisterForm where we add a new field and only look at it if USERNAME_ENABLED is set.

If you want to take a crack at that - go ahead - otherwise I'll try to get to it in the next couple weeks.

I have created a new issue to track this: #512
