### ISSUE TITLE
Rescuing from 2FA lowers security

### ISSUE THREAD

**Issue by sr-verde** [Flask-Middleware/flask-security#479]
**What is the current situation?** A user that has Two Factor Authentication activated may loose their smartphone used as second factor. To regain access to their account, they can use a token sent via email to login.

**Why is that bad?** An attacker that gets access to a mail inbox, can take over the account without knowing the password and without access to the second factor (the smartphone). The attacker would first use the password-reset function and then use the rescue 2FA function.

**How can that be solved?** One should not send any tokens to sign in via email. Instead, after activating 2FA, the user should get a list of rescue tokens and the prompt to save them securely. With one of that rescue tokens, they can get access to their account in case of loosing their smartphone.

**Comment by jwag956** [comment]
Interesting point - there appear to be several ways other websites handle this - some with recovery tokens - other - such as AWS with 'alternative methods' (such as phone).

Will take some research to figure out the best way forward. One easy idea would be to at least allow a configuration that doesn't send a rescue email and just sends an email to 'support'..... We already have an admin method and CLI to reset user access.

**Comment by sr-verde** [comment]
Yes, I first came up with the idea of just deactivate it. But that can lead to high effort at the customer support.

A second method is a good and valid point (you can e.g. choose SMS instead of auth app). But mail is always bad because it is a bad second factor because of the described behavior above (and because of password reuse; if one user choose same password for mail and flask app, then there is no second factor anymore).

I think tokens would be the first solution because you will always want to offer that for users who registered only one method.
