### ISSUE TITLE
user_datastore.find_user with SQLAlchemy always case-insensitive

### ISSUE THREAD

**Issue by Wormfriend** [Flask-Middleware/flask-security#481]
I just realised that the find_user function is always case-insensitive due to the usage of sqlalchemies filter_by-function. At this point I don't know if this is supposed to be a feature of the filter_by function or a bug. Nevertheless the case_insensitive kwarg is in my opinion misleading in this case.

PS: Please don't kill me if I the error is on my side. ;) Enjoy your weekend!

**Comment by jwag956** [comment]
Can you provide some test or document that says filter_by is lower case ?.
What is true is that now that FS is normalizing email using email_validator package that the domain part of an email will always be lower cased. And of course - the default configuration of USER_IDENTITY_ATTRIBUTES specified that the entire email be lower case.

**Comment by Wormfriend** [comment]
I just found out it has something to do with [Identifier Case-sensitivity](https://mariadb.com/kb/en/identifier-case-sensitivity/) in mariadb. Sorry for the inconvenience and the false alarm. Thank you for your quick response anyways.
