### ISSUE TITLE
version 4.0.1 (still) doesn't accept tokens created with version 3.4.5

### ISSUE THREAD

**Issue by kuba-lilz** [Flask-Middleware/flask-security#483]
This is related to #461 that I thought I solved with pull request #463

I tried flask security 4.0.1 today, sending to it api tokens created with version 3.4.5, and endpoints decorated with 
`@flask_security.auth_token_required` 
failed to authenticate, returning
```
{
  "meta": {
    "code": 401
  },
  "response": {
    "error": "You are not authenticated. Please supply the correct credentials."
  }
}
```

In issue #461 I was advised to modify UserMixin.verify_auth_token to handle both old and new token formats.
Putting some debugging statements into flask security, I noticed that while for successful calls using tokens made with 4.0.1 UserMixin.verify_auth_token gets called, with old tokens UserMixin.verify_auth_token doesn't seem to get invoked.

Any chance there is some function earlier in the stack that also needs to be modified?

**Comment by kuba-lilz** [comment]
core.py:_request_loader
seems to hard code fs_token_uniquifier indices on lines 465~468.
Perhaps these need the same treatment as #463 applied to UserMixin.verify_auth_token?

**Comment by jwag956** [comment]
Yup - needs same change - guess we need an additional end-to-end test...

**Comment by kuba-lilz** [comment]
I can write the fix, but could you please point me to a test I could reference?
I tried searching for `auth_token_required` in tests, and only
`tests/test_common::test_authenticated_loop` and `tests/test_common::test_session_query` come up - my understanding is they test logic adjacent to `auth_token_required`, but not really the decorator itself, am I right?

**Comment by jwag956** [comment]
Thanks - that would be great - conftest.py sets up an endpoint for testing @auth_token_required - look at test_common::test_token_auth_via_header_valid_token

instead of just getting the auth_token from logging in - use the same code you did before to create a 3.4.5 compatible token.

**Comment by kuba-lilz** [comment]
Are pip requirements files correct? I tried creating a fresh conda environment and then run tests on master branch, but run into missing `flask-login` module exception - and `flask-login` indeed doesn't seem to be defined in requirements files.

Here's an excerpt from my shell history, plus relevant outputs
```zsh
  978  conda create --name flask_security python=3.8
  979  conda activate flask_security
  980  which python
  981  pip install -r ./requirements/tests.txt
  982  which pytest
  983  pytest ./tests
```

```zsh
pytest ./tests
ImportError while loading conftest '/Users/kuba/Downloads/flask-security/tests/conftest.py'.
tests/conftest.py:24: in <module>
    from flask_security import (
flask_security/__init__.py:14: in <module>
    from .changeable import admin_change_password
flask_security/changeable.py:14: in <module>
    from flask_login import COOKIE_NAME as REMEMBER_COOKIE_NAME
E   ModuleNotFoundError: No module named 'flask_login'
```

**Comment by jwag956** [comment]
Well - Flask-Login is part of dependencies when installing Flask-Security - so I suppose for tests all those should be listed?

**Comment by kuba-lilz** [comment]
Ah, silly me, I assumed that if I installed flask-security with setup.py, then tests would be run against system-wide flask-security, instead of code in working directory, but after some quick checks I see I was wrong. My bad!
