### ISSUE TITLE
peewee too slow

### ISSUE THREAD

**Issue by Lorenzoag** [Flask-Middleware/flask-security#503]
I'm working on a project and I was using version 3.4.4, today I want to update to version 4.0.1 and when running tox it takes too long, I try to download it to version 4.0.0 and it continues just as slow only when I download it to version 3.4.5 fixed the problem.

These are the times it gives me at the end of the test.

v4.0.1
================================================= test session starts =================================================
platform win32 -- Python 3.9.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
cachedir: .tox\py39\.pytest_cache
rootdir: D:\PYTHON\Proyectos\siscova
plugins: cov-2.10.1
collected 3 items

tests\test_auth.py .                                                                                             [ 33%]
tests\test_company.py .                                                                                          [ 66%]
tests\test_main.py .                                                                                             [100%]

----------- coverage: platform win32, python 3.9.5-final-0 -----------
Name    Stmts   Miss  Cover
---------------------------
---------------------------
TOTAL     135      0   100%

5 files skipped due to complete coverage.
Coverage HTML written to dir .chtml

====================================== 3 passed, 2 warnings in 134.66s (0:02:14) ======================================
_______________________________________________________ summary _______________________________________________________
  py39: commands succeeded
  congratulations :)

v3.4.5
================================================= test session starts =================================================
platform win32 -- Python 3.9.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
cachedir: .tox\py39\.pytest_cache
rootdir: D:\PYTHON\Proyectos\siscova
plugins: cov-2.10.1
collected 3 items

tests\test_auth.py .                                                                                             [ 33%]
tests\test_company.py .                                                                                          [ 66%]
tests\test_main.py .                                                                                             [100%]

----------- coverage: platform win32, python 3.9.5-final-0 -----------
Name    Stmts   Miss  Cover
---------------------------
---------------------------
TOTAL     135      0   100%

5 files skipped due to complete coverage.
Coverage HTML written to dir .chtml

============================================ 3 passed, 2 warnings in 7.14s ============================================
_______________________________________________________ summary _______________________________________________________
  py39: commands succeeded
  congratulations :)

**Comment by jwag956** [comment]
Not a lot of info to go on. What does this have to do with peewee?
With that much time - it is likely that something is timing out.
One thing - in your conftest.py (or whatever you use to set up tests) - make sure to turn off email validation:

app.config["SECURITY_EMAIL_VALIDATOR_ARGS"] = {"check_deliverability": False}

**Comment by Lorenzoag** [comment]
Let's see, peewee is the orm that I use, since I updated it started to get slow and it always had to do with access to the DB so I assumed it had to do with that, I also read the other questions and since I did not see anyone speaking I thought that was a particular case. Yesterday I tried the configuration you suggested and it worked for me, the problem is that I work without connection and that is why it was delaying me, thanks for the prompt response.
