### ISSUE TITLE
LoginForm requires valid email even if USERNAME_ENABLED is True

### ISSUE THREAD

**Issue by jwag956** [Flask-Middleware/flask-security#512]
I think there needs to be changes to the login form as well? Currently, even if `USERNAME_ENABLE` is True, it still forces one to enter an email address while trying to log in. (Validator demands a valid e-mail address).

Prior to this, I was using 

```python
app.config['SECURITY_USER_IDENTITY_ATTRIBUTES'] = [
    {'email': {'mapper': uia_email_mapper}},
    {'username': {'mapper': uia_username_mapper}}
]
```
with a custom `uia_username_mapper` and custom login and registration forms,

```python
class CustomRegisterForm(RegisterForm):
    username = StringField('Username', [Required()])

    def validate(self):
        if user_datastore.find_user(username=self.username.data):
            self.username.errors = ["Username already taken"]
            return False

        if not super(CustomRegisterForm, self).validate():
            return False

        return True


class CustomLoginForm(LoginForm):
    email = StringField('Username or Email', [Required()])

```

Was hoping I can get rid of those things now.
Shall I send a pull request for this? Looks like a change to LoginForm should fix things?

_Originally posted by @hrishikeshrt in https://github.com/Flask-Middleware/flask-security/issues/466#issuecomment-899093294_

**Comment by jwag956** [comment]
This is due to the LoginForm having EmailField - which translates info an html5 email input.

**Comment by hrishikeshrt** [comment]
_Originally posted by @jwag956 in https://github.com/Flask-Middleware/flask-security/issues/466#issuecomment-900613170_

> Ahh yes - good point. It was recently changed to EmailField to have html5 input validators - which are a great help on mobile devices - so in the normal case I wouldn't want to change that. So we probably need something like the RegisterForm where we add a new field and only look at it if USERNAME_ENABLED is set.

I agree that `EmailField` is useful.
I am not sure if I am a fan of the current solution of adding the username field anyway in the `RegisterFormMixin`. 
Perhaps I don't completely understand it. However, I felt like having another `RegisterForm` something like `UsernameRegisterForm` similar to the current `ConfirmRegisterForm`.
Then again, duplicating entire structure for one option might be ugly too.

For `LoginForm`, similarly `UsernameLoginForm` could be created which duplicates `LoginForm` except the type of `email` field, which now becomes `StringField`.

I have some more concerns regarding the (lack of) username restrictions. I'll raise this in a separate issue. But mentioning here as it is relevant for what I want to say about the "Email or Username" field, which could have conditional validators, e.g. if '@' is detected, it assumes it to be an email and then forces it to be a valid email. (This is possible only if usernames do not contain '@' etc.)

**Comment by jwag956** [comment]
So I didn't see a way to 'dynamically' add a field based on configuration - seems like WTForms is pretty much just declarative.
But having an extra field on the form doesn't seem an issue - we properly verify on validation that the field is (or isn't) allowed.

Having dynamic validators also doesn't seem possible - but in reality - I would think that most applications, if they want to support username or email would have their own template that actually has 2 fields - but I can see that is confusing and requires a bunch of extra template code.

As to why I didn't add a new RegisterUsernameForm - as opposed to always adding the field - probably since there are already 2 register forms so this would make it 4 and it is already confusing to people that we have 2!

**Comment by jwag956** [comment]
Just thinking here - but it might be easiest to simply modify the template - after all - we really have just one form data item - so possibly we can just check whether USERNAME_ENABLED is set in the template and modify the args to remove the email input type..... haven't looked into how hard that would be.

**Comment by hrishikeshrt** [comment]
Another line of thought, `RegisterForm` and `LoginForm` (perhaps others as well eventually) can be created by an application factory kind of an approach (namely, a function that returns a class)?

Dynamic creation of classes is possible using `type()` function.

With three arguments, type() returns a type object (class). 
```python
MyClass = type('MyClass', (object,), {})
```

Reference: https://docs.python.org/3/library/functions.html#type
