### ISSUE TITLE
(Lack of) Username Restrictions

### ISSUE THREAD

**Issue by hrishikeshrt** [Flask-Middleware/flask-security#513]
I am not sure if it is ideal to allow "anything with bleach it" as a username. 
This would allow usernames such as `...` or `a@b` and so on. 

I generally prefer a regex condition as follows,

```python
def uia_username_mapper(identity):
    pattern = r'^(?!_$)(?![0-9_.])(?!.*[_.]{2})[a-zA-Z0-9_.]+(?<![.])$'
    return identity if re.match(pattern, identity) else None
```
Please express your opinions on such a regex. 
This would prevent usernames starting with digits, dots, underscores, having consecutive underscores or dots or having any other special characters. 

If there is a specific reason to not impose any restriction, perhaps it could be `SECURITY_USERNAME_CLEAN_ONLY` kind of a setting? Which would let users easy access to "stricter" checks.

Also, perhaps a configuration that allows administrators to configure and disallow certain usernames (like "root", "admin" etc).
(`SECURITY_USERNAME_BLACKLIST` perhaps).

**Comment by jwag956** [comment]
So actually - this is likely a documentation issue. If you look at UsernameUtil - which is a class you can subclass to provide whatever validation you want - currently it first does bleach, then it calls check_username - which by default only allows unicode letters and numbers.
