### ISSUE TITLE
Flask-security-too =>4 requires internet for login and registration

### ISSUE THREAD

**Issue by spoungebob** [Flask-Middleware/flask-security#514]
The flask-security-too team should consider enabling the login and registration options without the need of internet connection during development.
Without internet options I cannot login to the flask basic application with the flask-security-too=>4. I only get an error "specified used doesn't exist" , so I had to use flask-security-too=<3

**Comment by jwag956** [comment]
This is due to the default email validator - which is good for production but possibly annoying for testing. As documented here: https://flask-security-too.readthedocs.io/en/stable/quickstart.html#unit-testing-your-application

you can easily turn that off.
