### ISSUE TITLE
AttributeError while performing Unit Testing 

### ISSUE THREAD

**Issue by spoungebob** [Flask-Middleware/flask-security#520]
I do get  "AttributeError: 'NoneType' object has no attribute 'send' " with the reqistration link without internet even when configured the app  to "app.config["SECURITY_EMAIL_VALIDATOR_ARGS"] = {"check_deliverability": False}".

**Comment by jwag956** [comment]
I would need more data - such as the actual backtrace. I turned off my wifi and ran the entire flask-security unit test suite w/o issue.
Also - of course you can't get an email registration link when unit testing since it won't actually send email (assuming you have app.config["TESTING"] = True
