### ISSUE TITLE
mongoengine.errors.ValidationError

### ISSUE THREAD

**Issue by spoungebob** [Flask-Middleware/flask-security#522]
I get "mongoengine.errors.ValidationError: ValidationError (User:#################) (StringField only accepts string values: ['last_login_at']  could not be converted to int: ['last_login_ip'] 127.0.0.1 could not be converted to int: ['current_login_ip'])" when the SECURITY_TRACKABLE is set to  True.
Is there any solution to this ??

**Comment by jwag956** [comment]
Not sure where you saw that current_login_ip would be an int... 
As documented here: https://flask-security-too.readthedocs.io/en/stable/models.html

IP addresses of course are strings.

**Comment by spoungebob** [comment]
Thanks
