### ISSUE TITLE
Get rid of Flask-Mail

### ISSUE THREAD

**Issue by sr-verde** [Flask-Middleware/flask-security#531]
Flask-Mail is unmaintained since 2014 (as you know, I think :wink:). Since there are [security related issues](https://github.com/mattupstate/flask-mail/issues/189), I want to suggest to get rid of this dependency. @waynerv has ported Django's email implementation to a Flask extension. So this may be an alternative.

What do you think? I know, this would be a major change. But actually, Flask-Security contains a lot of unmaintained dependencies (Flask-Mail, Flask-Principal, pyqrcode) and I think it would be a chance to improve this project.

Best Pascua

**Comment by sr-verde** [comment]
FYI: There is a new Flask-Mail version. :open_mouth:
 
https://github.com/pallets-eco/flask-mail/releases/tag/0.10.0

**Comment by jwag956** [comment]
Yea - saw that - not a big deal to support it again.... As an aside - I am in the process of working with pallets to move flask-security under their repo and become the 'one' flask-security (including pypi).
