### ISSUE TITLE
Switch from sqlite database to mysql database

### ISSUE THREAD

**Issue by AntonioBlago** [Flask-Middleware/flask-security#545]
Hello,
is it possible to switch from SQLite to MySQL database for handling user authentification, signup ect....?

I have set up my app with  the authentication models like in the example: 
https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-sqlalchemy-application-with-session. 
That worked fine. But now I want to change from a local to a hosted database like MySQL . 
I changed the engine: 

```
engine = create_engine(
   'mysql+pymysql://{0}:{1}@{2}:{3}/{4}'.format(config.us_ssh, config.db_pass,host,port,db),
   connect_args={'connect_timeout': 120},
    pool_pre_ping=True,
   convert_unicode=True )

app.config['SQLALCHEMY_DATABASE_URI'] =   'mysql+pymysql://{0}:{1}@{2}:{3}/{4}'.format(config.us_ssh, config.db_pass,host,port,db)
```
I can access the database via user_datastore (see below) and create users or define roles. But when I want to login, confirm emails or reset the password, the validator does not find the specified users. I don't know where to adjust the script to adjust it. 

```
init_db()
user_datastore.create_user(username=request.form['username'],
                                   fullname=request.form['fullname'],
                                   email=request.form['email'],
                                   password=generate_password_hash("password"))


db_session.commit()
```

It would be awesome if someone can help.
Thanks!

Here my python set up

Flask-Security-Too==4.0.0
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
PyMySQL==1.0.2

Using python 3.8

**Comment by jwag956** [comment]
As they say - it should 'just' work. I might try using something like mysqlworkbench to connect directly to your MySQL instance and verify that the data is in fact stored correctly.
Second - it might be useful to see your models and config (such as SECURITY_USER_IDENTITY_ATTRIBUTES

**Comment by AntonioBlago** [comment]
> As they say - it should 'just' work. I might try using something like mysqlworkbench to connect directly to your MySQL instance and verify that the data is in fact stored correctly. Second - it might be useful to see your models and config (such as SECURITY_USER_IDENTITY_ATTRIBUTES

Thanks, yes the values are saved in the database. I checked that. 

my models
`from database import Base
from flask_security import UserMixin, RoleMixin
from sqlalchemy.orm import relationship, backref
from sqlalchemy import Boolean, DateTime, Column, Integer, \
                       String, ForeignKey


## Define User Models
class RolesUsers(Base):
    __tablename__ = 'roles_users'
    id = Column(Integer(), primary_key=True)
    user_id = Column('user_id', Integer(), ForeignKey('user.id'))
    role_id = Column('role_id', Integer(), ForeignKey('role.id'))

class Role(Base, RoleMixin):
    __tablename__ = 'role'
    id = Column(Integer(), primary_key=True)
    name = Column(String(80), unique=True)
    description = Column(String(255))


class User(Base, UserMixin):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    username = Column(String(15), unique=True)
    password = Column(String(80))
    fullname = Column(String(80))
    email = Column(String(255), unique=True)

    last_login_at = Column(DateTime())
    current_login_at = Column(DateTime())
    last_login_ip = Column(String(100))
    current_login_ip = Column(String(100))
    login_count = Column(Integer)
    active = Column(Boolean())
    fs_uniquifier = Column(String(255))
    confirmed_at = Column(DateTime())
    roles = relationship('Role', secondary='roles_users',
                         backref=backref('User', lazy='dynamic'))

`
my database.py

`import os
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.ext.declarative import declarative_base
import pymysql
import mysql.connector
import config

## Folder Directory
THIS_FOLDER = os.path.dirname(os.path.abspath(__file__))


   string_engine = 'mysql+pymysql://{0}:{1}@{2}:{3}/{4}'.format(config.us_ssh, config.db_pass,host,port,database)

    engine = create_engine(string_engine, connect_args={'connect_timeout': 120},
    pool_pre_ping=True,
    convert_unicode=True )
    db_session = scoped_session(sessionmaker(autocommit=False,
                                             autoflush=False,
                                            bind=engine))
Base = declarative_base()
Base.query = db_session.query_property()

def init_db():
    # import all modules here that might define models so that
    # they will be registered properly on the metadata.  Otherwise
    # you will have to import them first before calling init_db()
    Base.metadata.create_all(bind=engine)

def get_engine():
    return string_engine
`

What exactly do you mean with SECURITY_USER_IDENTITY_ATTRIBUTES like this? 

app.config['SQLALCHEMY_DATABASE_URI'] = get_engine()
app.config["SQLALCHEMY_POOL_RECYCLE"] = 299
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

**Comment by jwag956** [comment]
Please let me know if you haven't figured this out - and if you want additional help - please use the 'Discussions' tab rather than opening an issue.
