### ISSUE TITLE
Cannot log in with .co email (Specified user does not exist)

### ISSUE THREAD

**Issue by WardBenjamin** [Flask-Middleware/flask-security#576]
Hi there,

I set up my test user with a .co email address:

```py
test_user_email = "test@test.co"
test_user = user_datastore.find_user(email=test_user_email)
if test_user is None:
    test_user = user_datastore.create_user(email=test_user_email, password=hash_password("password"))
    print(test_user)
    db.session.commit()
```

This executes successfully, but you're not able to log in as that user:

![image](https://user-images.githubusercontent.com/4739008/153762936-7c7a1bcf-c1f5-4c0c-9bf9-e3d9880e4fc5.png)

Changing the TLD to .com and recreating the test user allows you to log in.

Version info:
```
Flask==2.0.2
Flask-Login==0.5.0
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Security-Too==4.1.2
Flask-SQLAlchemy==2.5.1
flask-talisman==0.8.1
Flask-WTF==1.0.0
```

**Comment by WardBenjamin** [comment]
This looks like it might be related to https://github.com/Flask-Middleware/flask-security/issues/442.

**Comment by jwag956** [comment]
Correct - for testing, as the docs mention, set\:
SECURITY_EMAIL_VALIDATOR_ARGS = { "check_deliverability" : False }
