### ISSUE TITLE
Logging in should not reveal if email is registered

### ISSUE THREAD

**Issue by WAKayser** [Flask-Middleware/flask-security#585]
Currently when entering an email and password, if only the password in invalid. You get a message that return that only the password is invalid. From this an attacker can learn what emails are registered. A more generic "Email or password invalid" message should be used.

**Comment by pemm8** [comment]
+1 Agree this should be fixed, however, it is possible to fix this through the config.

Change the following messages:

`USER_DOES_NOT_EXIST`
From "Specified user does not exist" to "Invalid username, email, or password."

`INVALID_PASSWORD`
From "Invalid password" to "Invalid username, email, or password."

You will likely also need to update the form template, as the message will appear next to email/username field if the email/username does not exist, and the password field if the password is invalid, thus "giving it away".  You can move the messages to a simply "errors" field on the same template and render all errors in `form.errors`
