### ISSUE TITLE
Add support for custom hash options 

### ISSUE THREAD

**Issue by mvanderlee** [Flask-Middleware/flask-security#590]
For issue #205  the `SECURITY_PASSWORD_HASH_PASSLIB_OPTIONS` option was added. 
However, we have no way to customize the data hash options. 

This is resulting in >500ms per request due to the sha256_crypt defaulting to 535,000 rounds, and we have no way to customize this.

Relevant code
https://github.com/Flask-Middleware/flask-security/blob/master/flask_security/core.py#L669

```python
...
    cc = CryptContext(
        schemes=schemes,
        default=pw_hash,
        deprecated=deprecated,
        **cv("PASSWORD_HASH_PASSLIB_OPTIONS", app=app),
    )
    return cc


def _get_hashing_context(app: "flask.Flask") -> CryptContext:
    schemes = cv("HASHING_SCHEMES", app=app)
    deprecated = cv("DEPRECATED_HASHING_SCHEMES", app=app)
    return CryptContext(schemes=schemes, deprecated=deprecated)
...    
```

I propose something like this:
Add `SECURITY_DATA_HASH_PASSLIB_OPTIONS`

```python
def _get_hashing_context(app: "flask.Flask") -> CryptContext:
    schemes = cv("HASHING_SCHEMES", app=app)
    deprecated = cv("DEPRECATED_HASHING_SCHEMES", app=app)
    return CryptContext(
        schemes=schemes, 
        deprecated=deprecated,
        **cv("DATA_HASH_PASSLIB_OPTIONS", app=app),
    )
```

**Comment by mvanderlee** [comment]
As a side note, I've configured it to use `argon2` instead and saw a reduction to about ~50ms per request.

```python
SECURITY_HASHING_SCHEMES = ["argon2"]
SECURITY_DEPRECATED_HASHING_SCHEMES = []
```

**Comment by jwag956** [comment]
So if you are having a per request delay of 500ms then you most likely haven't upgraded to have a fs_uniquifier field that is now used (and required in 4.0) which completely gets rid of all this delay. This was first released in 3.3 and in 4.0 made the default.
Please read the changelog here: https://flask-security-too.readthedocs.io/en/stable/changelog.html#version-3-3-0

**Comment by mvanderlee** [comment]
@jwag956 Thank you for your help, that solved my root problem.

I'll keep this issue open as I still think it's a good addition. But since I have no use-case for it myself, I won't object to it being closed.

**Comment by jwag956** [comment]
I am going to close this until there is a good use case - it's simple enough - but who wants yet another config option!
