### ISSUE TITLE
Will you accept bootstrap templates?

### ISSUE THREAD

**Issue by ser** [Flask-Middleware/flask-security#601]
Hi, would you accept PR of bootstrap templates as additional replacement set of templates? Made utilising https://bootstrap-flask.readthedocs.io/en/stable/

**Comment by jwag956** [comment]
I am not inclined to take this - a few reasons:

1) I expect that MOST users of Flask-Security have their own UX design and don't actually use the exact shipped templates.
2) I would end up having to support 2 sets of templates.
3) Changing completely over to bootstrap based templates would  add yet another dependency which is never good for a middleware package.

If there are changes that would make it EASIER to convert/generate bootstrap compatible templates from the shipped templates - please let me know.

**Comment by acidjunk** [comment]
Idea: This could also be realised by starting a separate pypi package that supplies the bootstrap templates for Flask-Security

**Comment by jwag956** [comment]
Yes - that would work - if it would make things easier - I could host it under my 'flask-middleware' organization..

Also - as I mentioned - if there is any refactoring or other changes to the existing templates that would make it easier to convert/re-implement using flask-bootstrap - please let me know or put up a PR.

Thanks.
