### ISSUE TITLE
question: is it possible to do single sign on for multiple applications

### ISSUE THREAD

**Issue by louking** [Flask-Middleware/flask-security#619]
I read https://flask-security-too.readthedocs.io/en/stable/features.html#unified-sign-in but unless I'm missing something, this doesn't seem to be what I'm looking for.

I have several different vhosts which use the same users database (with user, role, roles_users tables) via sqlalchemy binds. I'd like to be able to have a separate vhost to log in to all of them at once, i.e., single sign-on. Alternately, or in conjunction, I'd like if someone logs into or out of one of these vhost apps, that all of them get logged in/out.

Is this possible with the current implementation? Is this a standard thing, or do we think this will confuse users?

**Comment by jwag956** [comment]
So, once a user is authenticated, a Flask Session cookie is created - and that is used to authorize all future requests (that have a authz decorator!). That session cookie is managed by Flask and Flask-Login. First and foremost - it is signed - so each of your applications will need the same SECRET_KEY - which is what Flask uses to sign the cookie. Second, cookies are scoped to a domain (default SERVER_NAME) - Flask has a config variable SESSION_COOKIE_DOMAIN you can use to change that - assuming you have app1.mywebsite.com, app2.mywebsite.com - then I think you need to change the COOKIE_DOMAIN to be mywebsite.com. There is also SESSION_COOKIE_PATH that might have to be modifed. WIth that I think you can do what you want. In this case, if they log out, the session cookie is destroyed and they won't be able to access any of the websites from that device.

Whether or not this is a good thing (TM) for users - is really your call - I would assume this depends on whether all the apps/vhosts offer basically the same security risk level. If one of your apps allowed a user to trade Bitcoin, and another to search for cat videos - then single sign on would be a really bad thing :-)

**Comment by louking** [comment]
This is great info -- thanks!

The user permissions are controlled by different roles for each application, so the bitcoin/cat video example isn't an issue. Of course some people have roles for multiple applications, so that's why this came up.

The apps are indeed app1.mywebsite.com and app2.mywebsite.com. FWIW google password manager stores all the passwords under mywebsite.com, which is annoying as app3.mywebsite.com hasn't been converted to use the common users database yet.

Closing because I think this has been answered sufficiently.
