### ISSUE TITLE
Flask Mailman: AttributeError: 'NoneType' object has no attribute 'send'

### ISSUE THREAD

**Issue by pateljoel** [Flask-Middleware/flask-security#634]
I'm trying to use the `flask-mailman` package for sending mail on register and I get this error message:

```
AttributeError: 'NoneType' object has no attribute 'send'
```

This happens when `flask-mailman` is installed and after following the mail guide [here](https://flask-security-too.readthedocs.io/en/stable/quickstart.html#mail-configuration). I can also see that [this quickstart](https://github.com/Flask-Middleware/flask-security/blob/e7e5576832023dadcce4c41c924e8d4e67a1cb8e/docs/quickstart.rst) shows Flask Mailman in the mail configuration settings, I also followed this guide to no avail in progress.

Any help will be appreciated.

**Comment by jwag956** [comment]
Support for Flask-Mailman was added to master and will be part of 5.0.0 - it has not been released yet.
The current release on PyPI doesn't support it - though it is a really simple change.

**Comment by pateljoel** [comment]
OK thanks, that answered my question.
