### ISSUE TITLE
ImportError: cannot import name 'hash_password' from 'flask_security'

### ISSUE THREAD

**Issue by rapsli** [Flask-Middleware/flask-security#643]
I have created a new env and downloaded all latest versions from pip, but:

`from flask_security import hash_password`

will through the following error:

`ImportError: cannot import name 'hash_password' from 'flask_security'`

workaround would be from werkzeug.security import generate_password_hash, but in the documentation this is different everywhere, not sure what I'm missing?

**Comment by rapsli** [comment]
possibly the same as https://github.com/Flask-Middleware/flask-security/issues/641 after downgrading werkzeuge everything is working again.

**Comment by jwag956** [comment]
Please update to latest and re-open if still an issue.
