### ISSUE TITLE
Custom ID in Flask Security Too

### ISSUE THREAD

**Issue by pateljoel** [Flask-Middleware/flask-security#651]
I'm looking for a way to use either a custom user ID in Flask Security Too and it's roles but can't seem to do this properly anywhere.

Help is greatly appreciated and thanks for your work on Flask Security Too

Joel.

**Comment by jwag956** [comment]
Could use a bit more information - such as what sort of DB relationships you are trying to put together.FS2 no longer uses the ‘id’ field at all - it uses ‘fs_uniquifier’ for all its lookups.

**Comment by jwag956** [comment]
As I mentioned - FS2 no longer looks at the DB 'id' column - you should be able to change that to whatever you want.
