### ISSUE TITLE
Github/Pypi updates are incomplete

### ISSUE THREAD

**Issue by RajeshIF** [Flask-Middleware/flask-security#656]
I was running into errors during the login process, and finally upon comparing my project source code with the code on Github I noticed that the newer releases do not have all the updates, and some files (such as `forms.py`) contain code from older releases. The newest releases are also missing files, such as `tf_plugin.py`. I tried downloading the code from both the Github releases section and straight from pip, but no luck.

**Comment by jwag956** [comment]
GitHub master contains code for 5.0 which hasn't been released yet - soon hopefully

I would suggest starting with the latest release 4.1.5 unless you need some latest and greatest feature 

Regardless make sure you have one and only one version installed

**Comment by RajeshIF** [comment]
I understand, but it seems as though code meant to be released in the latest versions have somehow not been included with them - I've been trying to implement login functionality using a user's username instead of their email address, which according to both the documentation and the release updates, should be implemented; however, I keep getting email decode errors, which is what led me to checking the code of the release and finding that the code doesn't have the updated parts.
If I'm incorrect and the releases actually shouldn't have that functionality, please do let me know.
