### ISSUE TITLE
flask-security tries to send email to a user without email

### ISSUE THREAD

**Issue by puraminy** [Flask-Middleware/flask-security#671]
if a user changes their password, flask-security tries to send email without checking if user has email or not

**Comment by jwag956** [comment]
flask-security requires an email as part of registration - and in the models documentation it states that email is a required field.

**Comment by puraminy** [comment]
I guess you have an option to just  have username and I used it. So by checking email before sending an email you can keep this flexibility. However, I guess there is an configuration to disable this notification for all.

```
app.config["SECURITY_USER_IDENTITY_ATTRIBUTES"] = [
        {"username": {"mapper": uia_username_mapper, "case_insensitive": True}},
    ]
```

It was just an offer, and it's up to you yet.
