### ISSUE TITLE
Collaboration Request - API Logic Server

### ISSUE THREAD

**Issue by valhuber** [Flask-Middleware/flask-security#672]
Hello...

I am Val Huber, creator of [API Logic Server.](https://valhuber.github.io/ApiLogicServer/).  It an open source Python project that creates (Flask) web apps from a database, including the API and Admin app, including strong support for backend business logic via rules, extensible with Python.

But it does not provide security.

I am writing to see if anyone are interested in collaborating to add flask-security to this project.

Best regards,
Val

**Comment by jwag956** [comment]
Hi -  I am not in a position to be heavily involved - however - please feel free to start any discussions/questions over in the 'discussions' section. If you have specific needs (configuration, overiddable methods/classes, etc) please reach out by filing an issue.
