### ISSUE TITLE
Cannot create_role - permissions trying to save as list

### ISSUE THREAD

**Issue by janpeterka** [Flask-Middleware/flask-security#673]
After updating to 5.0.1 (from 4.1.4), my tests are failing.

I create roles as:
```python
        security.datastore.create_role(
            name="admin",
            permissions="manage-application,manage-users,login-as,see-debug,see-other,edit-other",
        ),
```
but when I print it, it says role.permissions is `['manage-application', 'manage-users', 'login-as', 'see-debug', 'see-other', 'edit-other']
`
and when saving (tried SQLite and MySQL), I get error:
in SQLite:
```
SQLAlchemy: Error binding parameter 0 - probably unsupported type
```
and in MySQL (PyMySQL)
```
ERROR    app:base_mixin.py:98 Save error: (pymysql.err.OperationalError) (1241, 'Operand should contain 1 column(s)')
[SQL: INSERT INTO roles (permissions, name, description) VALUES (%(permissions)s, %(name)s, %(description)s)]
[parameters: {'permissions': ['manage-application', 'manage-users', 'login-as', 'see-debug', 'see-other', 'edit-other'], 'name': 'admin', 'description': None}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

My role model is defined as:
```
from flask_security.models.fsqla_v2 import FsRoleMixin as RoleMixin

class Role(BaseModel, BaseMixin, RoleMixin, BasePresenter):
    __tablename__ = "roles"

    id = db.Column(db.Integer(), primary_key=True)  # type: ignore
    name = db.Column(db.String(80), unique=True)  # type: ignore
    description = db.Column(db.String(255))  # type: ignore
```

I've read v5.0.0 changelog concerning this (https://flask-security-too.readthedocs.io/en/stable/changelog.html#version-5-0-0), but it seems like the permission list should be converted to string when saving to db, shouldn't it?

**Comment by jwag956** [comment]
Bummer - I must have missed some backwards compat - if you can - change your DB models to inherit from models.fsqlav3 and that should get things working. If that isn't practical give me a few days to patch this - I didn't intend to break fsqlav2 projects..

**Comment by janpeterka** [comment]
Thanks, will try that!

**Comment by jwag956** [comment]
I just pushed 5.0.2 - with that, and the fact that you are using fsqla_v2 in your models - you should need NO changes to get permissions working.

Thanks for your patience.
