### ISSUE TITLE
Issue with permissions since 5.0.1

### ISSUE THREAD

**Issue by romanlucas** [Flask-Middleware/flask-security#674]
When upgrading to 5.0.1 from 4.1.5 the use of permissions broke for my usecase. Of course i read in the changelog about permissions now beeing stored as a list, but cant figure out to get things to work like i was used to.

I´m using SQLAlchemy with PostgreSQL and create roles and permissions (for example) via:

`user_datastore.find_or_create_role(
        name="editor", permissions={'editor'}, )`

with 4.1.5 a call of .get_permissions() returns: {'editor'}
after upgrading to 5.0.1 a call of .get_permissions() returns: {'o', 'i', 't', 'e', 'r', 'd'}

As i created role and permissions under 4.1.5, the permission(s) are stored as String (or comma-separated-string) in the database, instead of a list.
I also tried deleting the database, start with a fresh one and creating roles and permissions under 5.0.1.
The result of .get_permissions() stays the same.
I also tried altering the already mentioned .find_or_create_role with permissions as list, string, comma-separated-string, tuple (which shouldn't make any difference regarding the create_role method). With 5.0.1 creating permissions this way leads to permissions actualy beeing stored different from with 4.1.5, but unfortunately doesnt help with the issue.
Maybe i´m missing something here, but cant figure it out...

**Comment by jwag956** [comment]
Looks like some backwards compat issues - note that even in 5.0.1 - permissions are stored (in sql-based DBs) as a comma separated string - in 5.0 where the list is converted changed.
Are you using FS models.fsqlav2? If so - if you update to use models.fsqlav3 things should work.
I didn't mean to break this kind of compatibility and will work on a fix in the next few days.

**Comment by jwag956** [comment]
What is the column type of your permissions field? are you using the provided models.fsqla_v2 or 3?

**Comment by romanlucas** [comment]
Column type of my permissions field is UnicodeText.
I`m not using the models.fsqla.

**Comment by jwag956** [comment]
Duplicate of #673

**Comment by jwag956** [comment]
I just pushed release 5.0.2 - since you aren't using fsqla_vX please look at the change notes to see the 3 lines you need to add to your model to get everything working.

Thanks for your patience.
