### ISSUE TITLE
Typo in Quick Start Documentation

### ISSUE THREAD

**Issue by glnnlhmn** [Flask-Middleware/flask-security#682]
In the Quick Start example for _Basic SQLAlchemy Application with session_ the sample code for app.py has a typo.

Original code:

'if __name__ == '__main__':
    with app.app_context():
        # Create a user to test with
        initdb()    # typo
        if not app.security.datastore.find_user(email="test@me.com"):
            app.security.datastore.create_user(email="test@me.com", password=hash_password("password"))
        db_session.commit()
    app.run()
'

initdb() should be init_db()

**Comment by jwag956** [comment]
fixed with PR #683
