### ISSUE TITLE
Pass full context from utils.send_mail to MailUtil

### ISSUE THREAD

**Issue by patrickyan** [Flask-Middleware/flask-security#689]
MailUtil and the `mail_util_cls` option is meant to let us customize how we send emails from Flask-Security. However, no context  is passed (only the user is passed), so you cannot get things like the confirmation link/token or reset link in MailUtil.

Example use case is using services like Postmark and SendGrid that let you design email templates visually and pass in variables via API. Currently, you can use MailUtil and pass user info (name, etc.) but there's no way to pass confirmation link or reset link. A possible workaround for now is rendering the data into the jinja template and then re-parsing it back into Python in MailUtil, but this could all just be passed directly.

**Comment by jwag956** [comment]
That's a great idea and simple.

**Comment by jwag956** [comment]
Closed with #690
