### ISSUE TITLE
Typo in the documentation regarding Recovery Codes for Two-Factor Authentication

### ISSUE THREAD

**Issue by wildernessfamily** [Flask-Middleware/flask-security#691]
Hi, I came across a typo in the documentation in relation to recovery codes. 

Flask-Security-Too==5.0.2

Documentation v5.0.2 -> Section: models
https://flask-security-too.readthedocs.io/en/stable/models.html#models-topic
Under the section Recovery Codes it states the following:

> If [SECURITY_MULTI_FACTOR_RECOVERY_CODES](https://flask-security-too.readthedocs.io/en/stable/configuration.html#SECURITY_MULTI_FACTOR_RECOVERY_CODES) is set to True then the User model needs the following field:
> 
>     mfa_recovery_codes (list of string/UnicodeText, nullable)
> 
> A recovery code can be used in place of any configured second-factor authenticator (e.g. SMS, WebAuthn, …).

However, the variable `mfa_recovery_codes` is incorrect. It should be `mf_recovery_codes`. If you try to use `mfa_recovery_codes` in your db model, the recovery_codes will not be written and or retrieved. Python returns the following error: `AttributeError: 'str' object has no attribute 'mf_recovery_codes'

In `datastore.py` the method at line 550 `def mf_set_recovery_codes` is putting `mf_recovery_codes`into the db and not `mfa_recovery_codes` per line 559 & 560`user.mf_recovery_codes = rcs` | `self.put(user)`.

The documentation just needs to be changed to show `mf_recovery_codes` and not `mfa_recovery_codes` :)

Also, thank you for such an amazing package for Flask, and all the hard work and time all of the developers that have contributed to this project! It's easy to install, configure, and the documentation is well written! Again, thank you!

**Comment by jwag956** [comment]
Darn those 'a's always sneaking in!

Thanks for the report - if you end up using recovery codes - please let me know how it works out and any suggestions!

**Comment by wildernessfamily** [comment]
Totally understand! I have severe dyslexia, happens to me all the time.
I'm definitely going to be using the recovery codes on four sites. I'm going to make a little tweak and obfuscate the codes before they are placed in the db. I'll keep you posted on it.
Thank you so much for such an awesome, feature rich package. I'm looking forward to using unified sign-in. I really enjoy working with Flask-Security! Thanks again!
