### ISSUE TITLE
fs_uniquifier does not automatically generate

### ISSUE THREAD

**Issue by eneadodi** [Flask-Middleware/flask-security#703]
I have been having issues with fs_uniquifier in an app I have been implementing. 
I get the following message:

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: user.fs_uniquifier
[SQL: INSERT INTO user (tf_primary_method, tf_totp_secret, tf_phone_number, us_totp_secrets, us_phone_number, fs_uniquifier, date_created, email, username, password, clearance, authenticated, last_login_at, current_login_at, last_login_ip, current_login_ip, login_count, active, confirmed_at) VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (None, None, None, None, None, None, 't@email.com', None, '$2b$12$4ZeL1yMtke9V2AfaZe2GSegRZW269EhpaGs4GBl7fveoYkqgqE8bS', None, 0, None, None, None, None, None, 1, None)]

It seems to me that fs_uniquifier is not being automatically generated and the row is being inserted onto the table with 'None' in the place of fs_uniquifier. Any helping hand for this sort of issue?

**Comment by jwag956** [comment]
How are you creating the user - using the CLI? using the register form? following the quickstart example:
`app.security.datastore.create_user(email="test@me.com", password=hash_password("password"))`

**Comment by eneadodi** [comment]
Hello, thank you for the fast response!
I have simply been using the register view provided default by security at the moment (not worried about UI/UX experience at the moment). Therefore I have not inputted any code to create user manually.

**Comment by jwag956** [comment]
Then it should 'just work'. 

Can you post your models (looks like you have extended them from the default fsqlav3). Also useful would be your initialization code...

**Comment by eneadodi** [comment]
Actually, a good night of sleep allowed me to figure out this specific issue. I had redefined fs_uniquifier as a primary_key and not simply a unique column. Simple mistake. Thanks for your help!
