### ISSUE TITLE
404 for base64.js and webauthn.js when registering webauthn device

### ISSUE THREAD

**Issue by nougad** [Flask-Middleware/flask-security#704]
When registering a webauithn device flask-security uses static URLs to get the needed JS files:

https://github.com/Flask-Middleware/flask-security/blob/9c5361cb170ff008e2cd7d6d2886837dadaea9e5/flask_security/templates/security/wan_register.html#L10-L12

This results in a 404 because Flask does not find the files in the app static folder:

```
"GET /static/js/webauthn.js HTTP/1.1" 404 -
"GET /static/js/base64.js HTTP/1.1" 404 -
```

I'm not super familiar with flask but looking at flask-debugtoolbar it registers a separate static route:

https://github.com/pallets-eco/flask-debugtoolbar/blob/b5a7c032ab83e6f2f67cfbb5b121ab52e5caefba/src/flask_debugtoolbar/__init__.py#L107-L108

which sends the file from the static folder:

https://github.com/pallets-eco/flask-debugtoolbar/blob/b5a7c032ab83e6f2f67cfbb5b121ab52e5caefba/src/flask_debugtoolbar/__init__.py#L170-L172

relative to the py files:

https://github.com/pallets-eco/flask-debugtoolbar/blob/b5a7c032ab83e6f2f67cfbb5b121ab52e5caefba/src/flask_debugtoolbar/__init__.py#L59-L60

The path is then passed to the template and used there to link to static files:

https://github.com/pallets-eco/flask-debugtoolbar/search?q=static_path

I'm using Flask-Security-Too==5.0.2 with default templates/forms and Flask==2.2.2

**Comment by jwag956** [comment]
Thanks for the detailed info - looks like debug_toolbar has a good solution.
