### ISSUE TITLE
flask_login.html

### ISSUE THREAD

**Issue by jozekuhar** [Flask-Middleware/flask-security#709]
<input id="wan_signin" name="wan_signin" type="submit" value="{{ _fsdomain('Sign in with WebAuthn') }}"
          formaction="{{ url_for_security(**"wan_signin"**) }}{{ prop_next() }}">

Shouldn't there be **'wan_signin'**?

**Comment by jwag956** [comment]
You mean the file login_user.html?

I don't quite understand what you are asking - that section does POST to the wan_signin endpoint...

**Comment by jozekuhar** [comment]
I wanted to ask if there is any problem that " is inside ", because I am learning flask and all tutorials I watched said you must put ' .. ' if you have " .. " outside of the line. Because it didn't look good in Visual Studio code but it worked fine.

Sorry but I don't yet know how to say in english ' or "

**Comment by jwag956** [comment]
Ahh - single versus double quotes. I have found that jinja2 doesn't really care - even though most other tools (such as bash, python, etc) you have to either use a different style or escape the quote.
In this case I believe it would work either way - there are some templates where I have found we need nested double quotes.

If you find something that isn't working correctly - please feel free to post a new issue.
