### ISSUE TITLE
TypeError: validate() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by hextrim** [Flask-Middleware/flask-security#726]
Hi,

Every time I try to run latest of flask==2.2.2 + flask-security-too==5.0.2 or even diff combinantion of latest minor I get this error and I ran out of idea what is causing it.

I ran Getting Started: https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-sqlalchemy-application - does not work same error.

I ran https://github.com/hrishikeshrt/flask-bootstrap-anywhere.git - does not work neither, same error.

I am wondering what I am doing wrong here that I cannot setup the project and get 500 on POST /login endpoint everytime.

python3.8
python3 -m venv venv
pip3 install -r requirements.txt from the bootstrap project or just latest flask-security-too.
running via python3 app.py or gunicorn.

Regards,
W

**Comment by hextrim** [comment]
Follow up:

On python3.10 I get instead:
TypeError: LoginForm.validate() takes 1 positional argument but 2 were given

**Comment by jwag956** [comment]
This seems to be due to Flask-WTForms release the other day 1.1.0 that breaks virtually every form. Pin FlaskWTF to 1.0.1 and things should start to work.

**Comment by hextrim** [comment]
What a conincidence that the 1.1.0 was released 2 days ago.
In fact you were right, I thought I tried first downgrade flask_wtf to ==1.0.0 and was still having issues but, now testing with 1.0.1 and it works.

Thanks for help! Missed the so obvious.

**Comment by jwag956** [comment]
Flask-WTF released 1.1.1 which should fix this.
