### ISSUE TITLE
Session highjacking when running with gunicorn or uwsgi

### ISSUE THREAD

**Issue by tassinf** [Flask-Middleware/flask-security#727]
### Bug Description
When running my application on gunicorn or uwsgi, the first logged user is used for all subsequent requests. You're not even required to log if someone is already logged. Moreover, you'll get all his accesses.

In my development environment (pycharm) 'g' acts like a request_context, but in production (rhel8) used with gunicorn or uwsgi 'g' acts like an app_context and isn't reset between requests so the current_user is always the last to successfully log. 

I locally fixed the issue modifying the Flask-Login code replacing 'g' by 'session' in login_manager.py (line 341) and in utils.py (lines 371, 374). But I'm not sure this solution is viable. I opened a issue @ Flask-Login but as I'm not directly using their code, it has been refused. 

### Steps to reproduce the behavior

Here is a simplified version of my app. I'm using a virtualenv on RHEL8 with Python 3.9.13

```bash
mkdir /opt/flissue
cp flissue.zip /opt/flissue/
cd /opt/flissue/
unzip flissue.zip
virtualenv -p python3 venv
pip3 install -r requirements.txt
. venv/bin/activate
```

`python3 -m sflask` ==> log on http://your-server/ with [user@test.org](mailto:user@test.org)/user or [admin@test.org](mailto:admin@test.org)/admin from 2 different browsers ex: firefox/chrome and it will be ok.

`gunicorn -b 0.0.0.0:80 sflask:app` ==> Do the same and see how it behaves. 

### Expected behavior
Obviously sessions for different users shouldn't interfere.

### Needed files to reproduce the issue or find where I mess up ;)

[flissue.zip](https://github.com/Flask-Middleware/flask-security/files/10452235/flissue.zip)
[requirements.txt](https://github.com/Flask-Middleware/flask-security/files/10452237/requirements.txt)

**Comment by jwag956** [comment]
Interesting. Would you mind testing with a more recent Flask - most of your packages are latest - but Flask is a bit old.

**Comment by jwag956** [comment]
Whew - took a while to debug. The issue is that in your __init__.py you are doing a: app_context.push() - then doing the DB initialization - but you NEVER pop the app context. Flask will only push an app context if there isn't one already there - and it will pop it at the end of every request if the request caused an app context to be pushed. So - simple fix - instead of doing: app_context.push()
try:

`    with app.app_context():
        db.create_all()
        _admins = user_datastore.find_or_create_role(name='admins', description='Administrators Group')
        _admin = user_datastore.find_user(username='admin')
        _users = user_datastore.find_or_create_role(name='users', description='Registered Users')
        _user = user_datastore.find_user(username='user')
        if not _admin:
            _admin_pwd = 'admin'
            _admin = user_datastore.create_user(email='admin@test.org', password=_admin_pwd, username='admin')
            user_datastore.add_role_to_user(_admin, _admins)
        if not _user:
            _user_pwd = 'user'
            _user = user_datastore.create_user(email='user@test.org', password=_user_pwd, username='user')

        db.session.commit()`

**Comment by tassinf** [comment]
@jwag956 👍: Thank you so much for your time. As a Flask beginner, re-reading the documentation concerning app_context was really needed. I missed a lot of it. I couldn't have found this without you. Thanks again.
