### ISSUE TITLE
Custom LoginForm with single field for Username or Email

### ISSUE THREAD

**Issue by hrishikeshrt** [Flask-Middleware/flask-security#732]
I have an application instance with `SECURITY_USERNAME_ENABLE` and `SECURITY_USERNAME_REQUIRED` both `True`.

However, I feel that giving user two input fields for entering username or email is a bit shabby, so I want to give  a single input field in login form, "Username or Email".

I follow the instructions at,
https://flask-security-too.readthedocs.io/en/stable/customizing.html?highlight=login%20form#customizing-the-login-form

and my custom login form looks as follows,

```
class CustomLoginForm(LoginForm):
    email = StringField('Username or Email', [Required()])

    def validate(self, **kwargs) -> bool:
        self.user = lookup_identity(self.email.data)
        self.ifield = self.email
        return super().validate(**kwargs)

```

However, with this, I am never able to login, using either of username or email.
I checked, that the `self.user` instance does find the correct user, but validate() always evaluates to `False`.

What might I be doing wrong?

Thank you.

**Comment by jwag956** [comment]
Look at the response form - it should have some field's error message filled in.

**Comment by hrishikeshrt** [comment]
I have customized the `login_form` as well to match my application's style.
It does contain these (along with other necessary elements from `security/login_user.html`

```
                {{ render_form_errors(login_user_form) }}
                <div class="form-group">
                    {{ render_field_with_errors(login_user_form.email, class_="form-control font-weight-light", placeholder="Username or Email") }}
                </div>
                <div class="form-group">
                    {{ render_field_with_errors(login_user_form.password, class_="form-control font-weight-light", placeholder="Password") }}
                </div>
```
But I do not see any error being shown after login, just the login form being reloaded.

**Comment by hrishikeshrt** [comment]
Update:

I see that in the when it is executing `form.py` code,

```
        for name in self._fields:
            inline = getattr(self.__class__, f"validate_{name}", None)
            if inline is not None:
                extra.setdefault(name, []).append(inline)
```
All `inline` values (except for `next`) end-up being None. Guessing this is because it does not find validate_username, validate_password etc attributes. But I am not entirely  sure what values should be present there.

**Comment by jwag956** [comment]
Don't worry about the inline validators - WTForms lets you use either/or a validate() method or a per field validator. We mostly use the form validator() method. Upon return from POST /login the response form in the browser should have some errors in the fields - can you try a browser debugger and look at the response data?

Are you running this in an IDE (e.g. pycharm) and can you set a breakpoint and look at the data?

**Comment by hrishikeshrt** [comment]
I am just running using `python server.py`

I added some `print` statements (sorry for crude debugging) in WTForms `form.py`

In the `BaseForm.validate` function,  
under `if not field.validate(self, extra):` clause, 
I am getting a failure in validating `username` field

**Comment by hrishikeshrt** [comment]
Update:

I have updated my LoginForm as follows,

```
class CustomLoginForm(LoginForm):
    email = StringField('Username or Email',
                        validators=[validators.data_required()])

    def validate(self, **kwargs) -> bool:
        self.user = lookup_identity(self.email.data)
        if self.user is None:
            self.email.errors = ["Invalid username or email"]
            return False
        else:
            self.username.data = self.user.username
            self.email.data = self.user.email
        # self.ifield = self.email  # not sure if this is required
        return super().validate(**kwargs)
```

And I get the desired results. Please comment if this is an acceptable / "good" way

**Comment by jwag956** [comment]
Ok - here is what is going on. The documentation example isn't complete.

So - by setting SECURITY_USERNAME_ENABLE, FS (flask-security) is adding a 'username'  field to the LoginForm. When calling super().validate(**kwargs) it is attempting to validate that username field - which of course is None since you don't fill it in - and since SECURITY_USERNAME_REAQUIRED is True - validation is failing!

Setting ifield is important to avoid the LoginForm form re-looking up the user.
You shouldn't need to set self.email.data to self.user.email...

This actually showed a bug in the username configuration/validation - I'll look into that.

**Comment by hrishikeshrt** [comment]
Would this idea of single field where users could enter username or email ac acceptable one to be integrated? with some configuration?
I would be happy to contribute.
