### ISSUE TITLE
Missing requirement bleach

### ISSUE THREAD

**Issue by hrishikeshrt** [Flask-Middleware/flask-security#734]
I realize that this was already pointed out in a past issue (#516).
I am reopening it for discussion for the following reasons.

- I think it has been a while since the username feature is there now.
- The username feature is not a separate module or so, it is a matter of single configuration. So, an app can go from working to not working by changing a flag from False to True. I am not sure if that is a great idea. 

If not, may be part of `bleach` function call can be copied/implemented natively to avoid this dependency.

**Comment by jwag956** [comment]
This is a different issue - that required bleach even if you didn't use the feature.
I will add, as with other features, a configuration check init_app() that checks that bleach is available if USERNAME_ENABLE is set.
