### ISSUE TITLE
SPA - /login - JSON response - How to retrieve user data and its roles after login response

### ISSUE THREAD

**Issue by hextrim** [Flask-Middleware/flask-security#742]
Hi,

I am trying to find out how to receive the roles for the user after authentication from React App via axios call.

I am able to login the user, but the response only includes:
{"meta":{"code":200},"response":{"csrf_token":"ImM3NmZiNDYwNWRiOGZjOTkxN2EwOTY5NWZhYzZmZjNiODgyNDY3ODgi.Y9ZYcg.64Un6_QMHIN2c3btrJbA2sGoL1g","user":{}}}

The user field is blank, and quite frankly would like to retrieve that too.

Can I modify the /login endpoint for API calls (json response) somehow easily to fetch user data and its roles associated ?

Would appreciate any clues how to handle this.

Regards,
hextrim

{{ user.roles|join(', ') }}

**Comment by jwag956** [comment]
Look at get_security_payload in the docs - override that in your User modelSent from my iPhoneOn Jan 29, 2023, at 4:18 AM, jmp_0x1034 ***@***.***> wrote:﻿
Hi,
I am trying to find out how to receive the roles for the user after authentication from React App via axios call.
I am able to login the user, but the response only includes:
{"meta":{"code":200},"response":{"csrf_token":"ImM3NmZiNDYwNWRiOGZjOTkxN2EwOTY5NWZhYzZmZjNiODgyNDY3ODgi.Y9ZYcg.64Un6_QMHIN2c3btrJbA2sGoL1g","user":{}}}
The user field is blank, and quite frankly would like to retrieve that too.
Can I modify the /login endpoint for API calls (json response) somehow easily to fetch user data and its roles associated ?
Would appreciate any clues how to handle this.
Regards,
hextrim
{{ user.roles|join(', ') }}

**Comment by hextrim** [comment]
Hi,

Indeed was able to get the roles by doing:

    def get_security_payload(self):
        rv = super().get_security_payload()
        # :meth:`User.calc_username`
        rv["user"] = self.email
        rv["roles"] = str(self.roles).replace('[','').replace(']','')
        return rv

class Role...
    def __repr__(self):
##        return '<Role %r>' % (self.name)
        return str('%s').replace('[','').replace(']','') % (self.name)

That works for me.

Thanks again.
