### ISSUE TITLE
Forgot Password: username instead of email

### ISSUE THREAD

**Issue by petemarvin** [Flask-Middleware/flask-security#748]
Is it possible to do "forgot password" using username then it will just automatically fetch the email? or for better security username field and email field should match from Users table.

Btw, the purpose of this feature is that I have unique usernames but email address can be use multiple times.  for example I have set all my user to one email only but different usernames. So basically I cannot do the forgot password thru email. I have tried extending the forgotpasswordform by adding username and was able to get identity of the user. But unfortunately the reset password link was sent to the email address but to the wrong username after resetting the password.

**Comment by jwag956** [comment]
I am not certain I understand what you are trying to do - providing username, looking up the user and sending to the email of record for that user isn't supported - but I think with modifying the form, should be doable (which it sounds like you did). However I am confused by your last sentence - 'forgot password' needs some sort of out-of-band way to communicate with the user - email is currently the only supported method - though one could support using phone/SMS. So - what sort of out-of-band method for sending a recovery link are you trying to implement?

**Comment by petemarvin** [comment]
Apologies for the misunderstanding. I am using the method email address to send the link. Say for example this is my DB table for users.

![image](https://user-images.githubusercontent.com/40055959/217126402-94071845-bf88-417f-8b8b-94d2ed4da998.png)

`class ExtendedForgotPasswordForm(ForgotPasswordForm):
    username = StringField('Username', [InputRequired(),username_validator])

    def validate(self, **kwargs):
        if not super().validate(**kwargs):
            return False
        assert self.user is not None
        self.user = lookup_identity(self.username.data)
        if not super().validate(**kwargs):
            return False
        return True`

So I want to reset the password of User 4 using the username myUniqueUser4 having the same email address of user 1,2, and 4. With the method  ExtendedForgotPasswordForm I was able to get the User result using lookup_identity, which return "4". The problem now was when I click the reset link and change the password it was logged in as User 1 (myUniqueUser1).

**Comment by jwag956** [comment]
Looking at the code - this actually should work. One thing I noticed - you are calling super().validate() AFTER looking up the user - I assume that for this test - you are typing in BOTH the email and the username?  The super() validator will call  valid_user_email() which will set form.user. For this test - call super() first - then overwrite the form.user with your username lookup.

**Comment by petemarvin** [comment]
> Looking at the code - this actually should work. One thing I noticed - you are calling super().validate() AFTER looking up the user - I assume that for this test - you are typing in BOTH the email and the username? The super() validator will call valid_user_email() which will set form.user. For this test - call super() first - then overwrite the form.user with your username lookup.

thank you so much @jwag956. It worked, I just called super() first.
