### ISSUE TITLE
how can we make a root user?

### ISSUE THREAD

**Issue by samialfattani** [Flask-Middleware/flask-security#750]
I'm wondering that is there a way to create a **root user** that has all permissions allowed no matter what role he is assigned to nor what permissions he is granted?
I think such an option is important for developers to test the application while adding more roles and persmissions during the development phase.

**Comment by jwag956** [comment]
Not sure I see a real win here - you can easily add a new permission to an existing role - and depending on your test framework - just create the admin role with all permissions.
