### ISSUE TITLE
Reset Password endpoint - (auth) - How it works? Getting /reset/None response in dev.

### ISSUE THREAD

**Issue by hextrim** [Flask-Middleware/flask-security#754]
Hi,

I have implemented FSToo in an SPA "mode" connected to ReactApp.

I have added /auth/reset endpoint inside my react app that calls Flask+FSToo backend /reset endpoint when an email field is provided and form is submit via button.

On the backend I get email sent with:

send: b'Content-Type: multipart/mixed; boundary="===============4017702021748546230=="\r\nMIME-Version: 1.0\r\nSubject: Password reset instructions\r\nFrom: XYZ@XYZ.com\r\nTo: AAAA@AAA.com\r\nDate: Fri, 17 Feb 2023 07:45:36 +0000\r\nMessage-ID: <167661993666.666.9298598013782317699@AAAA.>\r\n\r\n--===============4017702021748546230==\r\nContent-Type: multipart/alternative;\r\n boundary="===============3789412148240192605=="\r\nMIME-Version: 1.0\r\n\r\n--===============3789412148240192605==\r\nContent-Type: text/plain; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\n\r\n\r\nClick the link below to reset your password:\r\n\r\nhttp://localhost:5000/reset/WyJkMzg2ZjRhOGNlMTY0OGM1YTAxNGU2NTUxZDViMjQ4YSIsIiQ1JHJvdW5kcz01MzUwMDAkYnB3RFJGSDNGQXNrMGpFLyRCRUxndGV5eExVRWZGNXdZRUxPSkdKUHlSbWhyNTJPMXNsUVE4OU9iWTkvIl0.Y-8woA.JWRmFBlMyJoz9NXoTcE-3-Z6Deo\r\n--===============3789412148240192605==\r\nContent-Type: text/html; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\n\r\n\r\n<p><a href="http://localhost:5000/reset/WyJkMzg2ZjRhOGNlMTY0OGM1YTAxNGU2NTUxZDViMjQ4YSIsIiQ1JHJvdW5kcz01MzUwMDAkYnB3RFJGSDNGQXNrMGpFLyRCRUxndGV5eExVRWZGNXdZRUxPSkdKUHlSbWhyNTJPMXNsUVE4OU9iWTkvIl0.Y-8woA.JWRmFBlMyJoz9NXoTcE-3-Z6Deo">Click here to reset your password</a></p>\r\n--===============3789412148240192605==--\r\n\r\n--===============4017702021748546230==--\r\n.\r\n'
reply: b'250 2.0.0 Ok: queued as 4DCD12DFA\r\n' 

When I login into my email and click on the link provided I get redirect to:
http://localhost:5000/reset/None

On the backend I see:
127.0.0.1 - - [17/Feb/2023 07:45:53] "GET /reset/WyJkMzg2ZjRhOGNlMTY0OGM1YTAxNGU2NTUxZDViMjQ4YSIsIiQ1JHJvdW5kcz01MzUwMDAkYnB3RFJGSDNGQXNrMGpFLyRCRUxndGV5eExVRWZGNXdZRUxPSkdKUHlSbWhyNTJPMXNsUVE4OU9iWTkvIl0.Y-8woA.JWRmFBlMyJoz9NXoTcE-3-Z6Deo HTTP/1.1" 302 -
127.0.0.1 - - [17/Feb/2023 07:45:53] "GET /reset/None HTTP/1.1" 302 -

What I am missing here from its functionality?

How I suppose to reset password?

I would expect that I would be redirected to flask endpoint where I would be asked to provide new password and confirm new password and submit to change it, but this is not what I see in the /reset endpoint behaviour.

How should I implement such behaviour or use the native /reset endpoint properly to reset password?

Should I somehow send email with custom template that will have this: "WyJkMzg2ZjRhOGNlMTY0OGM1YTAxNGU2NTUxZDViMjQ4YSIsIiQ1JHJvdW5kcz01MzUwMDAkYnB3RFJGSDNGQXNrMGpFLyRCRUxndGV5eExVRWZGNXdZRUxPSkdKUHlSbWhyNTJPMXNsUVE4OU9iWTkvIl0.Y-8woA.JWRmFBlMyJoz9NXoTcE-3-Z6Deo " 
as token and redirect me to React App endpoint where the token is provided and user is expected to provide new password?

How would I do that?

Regards,
W@hextrim

**Comment by jwag956** [comment]
Have you set: https://flask-security-too.readthedocs.io/en/stable/configuration.html#SECURITY_RESET_VIEW

that should be an endpoint/route in your react app that will get the token and should display the appropriate form and do the POST to /reset/token

**Comment by hextrim** [comment]
Hi Chris,

I could not find time over the weekend to reply to you, but if you let me continue on this thread, I have one more thing to confirm if I do things right and by the logic?

I have
backend: localhost:5000/reset
frontend: localhost:3000/recover

If I have 
    SECURITY_REDIRECT_BEHAVIOR = 'spa'
    SECURITY_RESET_VIEW = "/recover"

and I request password reset I get email wiith
http://localhost:5000/reset/WyJkMzg2ZjRhOGNlMTY0OGM1YTAxNGU2NTUxZDViMjQ4YSIsIiQ1JHJvdW5kcz01MzUwMDAkL3V4MEdlbzdSMlFYdGJxVyQ0Q1E4UjFNQUwwbmgzUjZZMGdiSjJKZ2ZuaWUvc29GdHNwU3kvaXdTNDg2Il0.Y_Mwzw.82eJzpjHBhQxE05Xu9LHmLVz76M

This requires me to directly hit the backend from the user, and if that is the normal logic then fine I could put it behind fqdn and route via nginx?

For clarity in development environment the  SECURITY_RESET_VIEW = "localhost:3000/recover" should be set instead, to point at react dev? (for someone who may have struggle in local dev).

If I set this right then in browser after opening reset link I get:

Redirect with response header

Location: localhost:3000/recover?token=WyJkMzg2ZjRhOGNlMTY0OGM1YTAxNGU2NTUxZDViMjQ4YSIsIiQ1JHJvdW5kcz01MzUwMDAkL3V4MEdlbzdSMlFYdGJxVyQ0Q1E4UjFNQUwwbmgzUjZZMGdiSjJKZ2ZuaWUvc29GdHNwU3kvaXdTNDg2Il0.Y_Mwzw.82eJzpjHBhQxE05Xu9LHmLVz76M&email=myemail%40googlemail.com&identity=myemail%40googlemail.com
Server: Werkzeug/2.2.2 Python/3.8.10
Vary: Cookie

and then after another GET I get cancelled response since I do not have anything running yet on frontend on that location.
Request URL: localhost:3000/recover?token=WyJkMzg2ZjRhOGNlMTY0OGM1YTAxNGU2NTUxZDViMjQ4YSIsIiQ1JHJvdW5kcz01MzUwMDAkL3V4MEdlbzdSMlFYdGJxVyQ0Q1E4UjFNQUwwbmgzUjZZMGdiSjJKZ2ZuaWUvc29GdHNwU3kvaXdTNDg2Il0.Y_Mwzw.82eJzpjHBhQxE05Xu9LHmLVz76M&email=myemail%40googlemail.com&identity=myemail%40googlemail.com
Referrer Policy: strict-origin-when-cross-origin

Chris, do I understand this logic right thus far, or I am making mistakes already in SPA setup?

I will focus on the frontend page, and may provide closing comments later if I find any concerns or bugs?

**Comment by jwag956** [comment]
I think you have it - the GET on the link in the email will/must go directly to your application/website (at /reset/{token}). That, in SPA mode will simply verify the token and redirect back to your frontend where you can put up whatever form you need, and then submit that form/json, along with the token, to reset the password (using POST /reset/{token).

For local development, where your react code might be running in a separate process/port - you would set RESET_VIEW="/reset-recover" and set REDIRECTHOST="localhost:3000"
Make sure your endpoint names/routes are different between your application (flask) and frontend (react).

Be sure to read: https://flask-security-too.readthedocs.io/en/stable/spa.html carefully.

**Comment by hextrim** [comment]
Hi Chris,

This is getting more complicated.

When I set
    SECURITY_REDIRECT_BEHAVIOR = 'spa'
    SECURITY_RESET_VIEW = "/auth/recover"
    SECURITY_REDIRECT_HOST = "localhost:3000"

I still can login but I cannot logout anymore and I get this error.

127.0.0.1 - - [20/Feb/2023 18:34:21] "GET /logout HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_security/views.py", line 285, in logout
    return redirect(get_post_logout_redirect())
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_security/utils.py", line 580, in get_post_logout_redirect
    return get_post_action_redirect("SECURITY_POST_LOGOUT_VIEW", declared)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_security/utils.py", line 568, in get_post_action_redirect
    raise ValueError("No valid redirect URL found - configuration error")
ValueError: No valid redirect URL found - configuration error

**Comment by jwag956** [comment]
What is the logout url?? The redirect logic looks at a bunch of variables - including the request ?next parameterAlso it will default to APPLICATION_ROOTSent from my iPhoneOn Feb 20, 2023, at 10:36 AM, jmp_0x1034 ***@***.***> wrote:﻿
Hi Chris,
This is getting more complicated.
When I set
SECURITY_REDIRECT_BEHAVIOR = 'spa'
SECURITY_RESET_VIEW = "/auth/recover"
SECURITY_REDIRECT_HOST = "localhost:3000"
I still can login but I cannot logout anymore and I get this error.
127.0.0.1 - - [20/Feb/2023 18:34:21] "GET /logout HTTP/1.1" 500 -
Traceback (most recent call last):
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 2548, in call
return self.wsgi_app(environ, start_response)
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in call
return self.app(environ, start_response)
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
response = self.handle_exception(e)
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_security/views.py", line 285, in logout
return redirect(get_post_logout_redirect())
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_security/utils.py", line 580, in get_post_logout_redirect
return get_post_action_redirect("SECURITY_POST_LOGOUT_VIEW", declared)
File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_security/utils.py", line 568, in get_post_action_redirect
raise ValueError("No valid redirect URL found - configuration error")
ValueError: No valid redirect URL found - configuration error

**Comment by jwag956** [comment]
For development I would turn off corsThis won’t be an issue in production since both front and backend will be at same host/port. I’ll try to add a comment in the docsSent from my iPhoneOn Feb 20, 2023, at 11:10 AM, jmp_0x1034 ***@***.***> wrote:﻿
The backend logout url is set to default.
I did not use:
SECURITY_URL_PREFIX = '/api/accounts'
Should I?
I get
Access to XMLHttpRequest at 'http://localhost:5000/logout' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
My backend cors:
cors = CORS(resources={r"": {"origins": ""}},
expose_headers=["Content-Type", "X-CSRFToken"],
supports_credentials=True,)
frontend cors:
export const logout = () => dispatch => {
return new Promise(() => {
axios.get("http://localhost:5000/logout", {
headers: { 'Content-Type': 'application/json',
'Access-Control-Allow-Origin': '*',
},
withCredentials: true
});
localStorage.setItem("storetoken", JSON.stringify({}))
dispatch(setUser({roles:"guest", user:null}));
})
}
I can set cors to specific localhost:3000 and localhost:5000 it does not help.
my backend config.py
SECURITY_REDIRECT_ALLOW_SUBDOMAINS = False
SECURITY_CSRF_COOKIE = {"samesite": "Strict", "httponly": False, "secure": False}
REMEMBER_COOKIE_SAMESITE = "strict"
SESSION_COOKIE_SAMESITE = "strict"
SECURITY_CSRF_COOKIE_NAME = "XSRF-TOKEN" # Inject CSRF to Cookie for axios/react
SECURITY_CSRF_HEADER = "X-XSRF-Token"
WTF_CSRF_TIME_LIMIT = None # Invalidate token after logout
WTF_CSRF_CHECK_DEFAULT = False # Is CSRF needed for /login authentication SHOULD be !
SECURITY_CSRF_PROTECT_MECHANISMS = ["session", "basic"]
SECURITY_CSRF_IGNORE_UNAUTH_ENDPOINTS = True # You cannot get a cookie until you are logged in
#Generic Responses - Avoiding User Enumeration
SECURITY_RETURN_GENERIC_RESPONSES = True
SECURITY_REDIRECT_BEHAVIOR = 'spa'
#SECURITY_RESET_VIEW = "localhost:3000/recover"
SECURITY_RESET_VIEW = "/auth/recover"
SECURITY_REDIRECT_HOST = "localhost:3000"
This flag started causing these issues:
SECURITY_REDIRECT_HOST = "localhost:3000"

**Comment by hextrim** [comment]
Hi Chris,

This is still an issue even if a single domain is setup.

I have configured this now as follows:
    SECURITY_REDIRECT_BEHAVIOR = 'spa'
    SECURITY_REDIRECT_HOST = "dmz.hextrim.com"
    SECURITY_URL_PREFIX = "/api/accounts"

As soon as I add SECURITY_REDIRECT_HOST the logout stops working.
It does not matter if I then setup SECURITY_POST_LOGOUT_VIEW = '/' to any path really, I always get this error:

172.28.64.1 - - [20/Feb/2023 22:03:19] "GET /api/accounts/logout HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_security/views.py", line 285, in logout
    return redirect(get_post_logout_redirect())
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_security/utils.py", line 580, in get_post_logout_redirect
    return get_post_action_redirect("SECURITY_POST_LOGOUT_VIEW", declared)
  File "/home/lo3k/git/cod-app-project/dmzfx/venv/lib/python3.8/site-packages/flask_security/utils.py", line 568, in get_post_action_redirect
    raise ValueError("No valid redirect URL found - configuration error")
ValueError: No valid redirect URL found - configuration error


Further more the REDIRECT_URL should have some effect I guess on the email being generated but I get the link with flask backend IP:

http://172.28.75.5:5000/api/accounts/reset/WyJlNTJkZDgwYjM0YmU0NDZjOTEyMmUzODcyODM3OTFhNSIsIiQ1JHJvdW5kcz01MzUwMDAkU0t0U0ZPNWdRTXh0clJveSQzYWtRYnJMUXVEcmRuVE5MN21iWjk4Q09YWXBTV0JWdk9ob0tndGEzOUkwIl0.Y_PuYQ.1INuYx0G3_fGZqNVThjyyF97zXU

I suppose this is an issue otherwise what else I could be doing wrong?

**Comment by hextrim** [comment]
Hi Chris,

Sorry for my lack of understanding of the specific flags, but seems that the SECURITY_REDIRECT_HOST suppose to work in Dev environment but there is literally harder to disable cors in the setup then configure a single domain on nginx and proxy pass to frontend:3000 and backend:5000.

Finally when I remove this flag, things started to work as "expected" with one remaining issues which was the email template that generated the reset_link with fqdn of IP address of app.run(host=0.0.0.0) which in my case was interface of docker image.

I had to manually edit the template inside template/dist/security/email/reset_instruction.html to something like:
FROM:
<p><a href="{{ reset_link }}">{{ _fsdomain('Click here to reset your password') }}</a></p>
TO:
<p><a href="http://dmz.hextrim.com/api/accounts/reset/{{ reset_token }}">{{ _fsdomain('Click here to reset your password') }}</a></p>

To finally generate a link with the desired fqdn and path.

Seems like that is a workaround as the reset_link won't be able to generate an email with fqdn?

Regards,
W
