### ISSUE TITLE
"Invalid reset password token "

### ISSUE THREAD

**Issue by macfire** [Flask-Middleware/flask-security#758]
Issue:
When arriving at "/reset" page by clicking on the link provided in the email received to reset password, the following error is received: "Invalid reset password token" 

Can anyone direct me where to start troubleshooting?

* Flask==2.23
* Flask-Security-Too==5.1.0
* Flask-Login==0.62
* flask-mailman==0.30
* flask-mongoengine==1.0.0
* mongoengine==0.26.0

Thanks for any help.

**Comment by jwag956** [comment]
Let's start with what the url is that you were redirected to i.e. xxx/reset/???

Also a bit of info on your configuration would help

**Comment by macfire** [comment]
- [ ] The URL  for reset form page:  http://127.0.0.1:5000/reset
- [x] Receive email with link: http://127.0.0.1:5000/reset/LONG...TOKEN...HERE
- [x] Arrive at URL with token:  error message displayed is "Invalid reset password token".

The site has been in use for several years, but hasn't been maintained.
It uses Flask-Security, and I am attempting to upgrade using the newer Flask-Security-Too package.

I just checked and see that SECURITY_PASSWORD_HASH is set to 'sha512_crypt'.
In reviewing the current examples, I see the 'argon2' appears to be recommended (or required.) I will test that next.

How is the token generated?
Maybe another package/library that needs to be updated?

**Comment by jwag956** [comment]
A basic question - make absolutely sure you removed the old flask_security package and then install the flask-security-too package (make sure the directory in site-packages is empty). 

sha512_crypt is fine - in the past few years, argon2 has received lots of enthusiastic support.

The token is generated using the itsdangerous package.

That error means that either the 'user' that is looked up with the contents of the token doesn't exist OR something wrong with the token.

I assume you have updated your database models to include the fs_uniquifier in the User model and have made sure you populated that field for any existing records.

**Comment by macfire** [comment]
@jwag956 , thanks for your suggestions.

I'm encountering the same issue on another site where I'm upgrade from Flask-Security to Flask-Security-Too, and went through the checklist:

-[x] the new user field "fs_uniquifier" is added
-[x] the old flask-security files are removed
-[x] the User does exists
-[] f"fs_uniquifier" is NOT empty  <--- This was the error. I filled field with random text and it works.

**Comment by jwag956** [comment]
Glad that worked - 'random text' isn't a great idea :-) It is critical that every user have a UNIQUE fs_uniquifier.

Check out the migration tips:
https://flask-security-too.readthedocs.io/en/stable/changelog.html#id25
