### ISSUE TITLE
Issue while using extended ascii characters in password

### ISSUE THREAD

**Issue by pravesh-sharma** [Flask-Middleware/flask-security#767]
If we try to use extended ascii characters like µ in the password (for example 1234µ) the password hash generated is different each time and does not match.

**Comment by jwag956** [comment]
Please provide more information - versions, if you have examples that would be great. Flask-Security-Too uses python unicodedata.normalize to normalize unicode passwords prior to storing and hashing (unless you've changed configuration values).

**Comment by ChrisBuergi** [comment]
Does this happen when the password is reset? Or in general? 
It happened to our customers when they reset their password and are using extended ascii characters (in our case äöü...). Just checked today with version 5.1.1 and we still have to apply the change in the following pull request #577, that I submitted last year, for the password reset to work properly with extended ascii characters. Maybe that helps somehow.

**Comment by jwag956** [comment]
Hi Chris - very interesting - I assume you are using the stock reset_password_form (you didn't subclass it?). And you didn't subclass password_util...

**Comment by ChrisBuergi** [comment]
I do actually create a new ResetPasswordForm since I needed a length validator in the password. Maybe that is why the reset does not work with the extended ascii characters. Will investigate.

This is how I created the reset form:
```
class NewPasswordFormMixinEx:
    def __init__(self):
        pass

    password = PasswordField(get_form_field_label('password'),
        validators=[password_required,
                    Length(min=8, max=128)])

class ResetPasswordFormEx(Form, NewPasswordFormMixinEx, PasswordConfirmFormMixin):
    submit = SubmitField(get_form_field_label('reset_password'))
```

**Comment by jwag956** [comment]
Ahh yes - for better or worse - most FS forms have a form level validator that does important things - in this case - normalizing and validating the password. In this case at least I think I could move that to a field level validator that would make subclassing much easier.

**Comment by pravesh-sharma** [comment]
> Please provide more information - versions, if you have examples that would be great. Flask-Security-Too uses python unicodedata.normalize to normalize unicode passwords prior to storing and hashing (unless you've changed configuration values).

We are using version 4.1.6 and I've tried with latest version as well.

**Comment by pravesh-sharma** [comment]
> Have you subclassed the ResetPasswordForm? as @ChrisBuergi did?

Well I have not checked the reset password as I am facing the issue in the login page itself

**Comment by jwag956** [comment]
password normalization was added in 4.0.0 - almost 2 years ago and has numerous unit tests. If you have a reproducible test case you can share - please fee free to reopen this issue.

**Comment by pravesh-sharma** [comment]
I tried with the latest version too and it's not working I am attaching a screenshot of password reset page where I have set the password to 12345µ and when trying to login using this password I am not able to login it says wrong password. Please let me know you need any other details.

<img width="1146" alt="Screenshot 2023-05-11 at 3 24 15 PM" src="https://github.com/Flask-Middleware/flask-security/assets/111979571/f156a569-a15b-4cb6-9ef6-0346ab589e79">
<img width="1146" alt="Screenshot 2023-05-11 at 3 23 53 PM" src="https://github.com/Flask-Middleware/flask-security/assets/111979571/4ce37e8d-0c30-4d20-a6df-76aa8ceeaf56">
<img width="1146" alt="Screenshot 2023-05-11 at 3 23 22 PM" src="https://github.com/Flask-Middleware/flask-security/assets/111979571/d3c1d133-0d5d-4237-9224-68a4950ae1ff">

**Comment by pravesh-sharma** [comment]
We have not subclassed the login form, we  have made our custom login form and provided the input using `form = _security.forms.get('login_form').cls(request.form)` also value for `SECURITY_PASSWORD_HASH` is `pbkdf2_sha512`

**Comment by jwag956** [comment]
If you are using a real password hash algorithm - then having the password in plaintext in your DB is wrong. Be sure you create your user /password using the register endpoint, CLI, or create_user API.

**Comment by pravesh-sharma** [comment]
> If you are using a real password hash algorithm - then having the password in plaintext in your DB is wrong. Be sure you create your user /password using the register endpoint, CLI, or create_user API.

Hi,
We are not saving password in plaintext, that I intentionally did to so you what password we have set which is causing the issue.

**Comment by pravesh-sharma** [comment]
Hi @jwag956,

This issue is still reproducible with version 5.4.3. To reproduce just set a password which contains the character µ in it, the password will be set successfully but the user won't be able to log in.

**Comment by jwag956** [comment]
If you have your own login form then you probably are missing quite a few pieces of validation that the normal login form performs. In particular - password normalization. Have you tried adding:
```
self.password.data = _security._password_util.normalize(self.password.data)
if not self.user.verify_and_update_password(self.password.data):
    self.password.errors.append(get_message("INVALID_PASSWORD")[0])
    return False
```
