### ISSUE TITLE
Make _want_json a parameter 

### ISSUE THREAD

**Issue by VakarisZ** [Flask-Middleware/flask-security#770]
Single page applications and other use cases where Security is used for securing API endpoints don't want jinja templates and redirects in responses. 

Example:
```
@auth-token-required
def endpoint():
     pass

resp = requests.get(
            "http://localhost/endpoint",
            verify=False,
        )
```

Even though no authentication token is provided the response is 200 instead of 401(`flask-security-too` thinks assumes it's not JSON and lets Flask-Login do a redirect).
To change this behaviour you need to `app.security._want_json = lambda _request: True`. This is not mentioned in the single-page application documentation and `_want_json` is private. 

The best thing would be to perhaps have default configurations for different modes/use cases? But I understand that this would probably require more refactoring, so a good compromise could be making `_want_json` a parameter for Security and mentioning it in the SPA docs.

**Comment by jwag956** [comment]
If your application wants a JSON response - then it should pass in the HTTP header Accept='application/json'. It is true that Flask and other frameworks will automatically guess json if it is passed as part of a POST - but for GETs with no parameters - your application has to say what it wants.

**Comment by VakarisZ** [comment]
We're making an API that only supports JSON, so we don't need the ability to handle other content types.

**Comment by jwag956** [comment]
That might be - but sending correct HTTP is always the right thing. I think you'll find that when you use packages such as axios for your front-end  it will by default set the Accept header.

**Comment by Zaptrouiyerxi** [comment]
> If your application wants a JSON response - then it should pass in the HTTP header Accept='application/json'. It is true that Flask and other frameworks will automatically guess json if it is passed as part of a POST - but for GETs with no parameters - your application has to say what it wants.

This, for some reason, does not work only on the request for password reset page/form.  With a before and after decorator, I can see that the request has **Accept** and **Content-Type** both at "application/json", as well as a positive return from default_want_json(request), and request.is_json.
The response is rendered as HTML.  

Other pages including those for the rest of the recoverable flow, all work.  They all use the same session object which initializes with these Accept and Content header values.

On v5.4.3

**Comment by Zaptrouiyerxi** [comment]
I may be wrong, if so please correct me, but it does not seem that there's code for returning JSON for the GET /reset/<reset_token> that returns the initial form for the new password.

I've never done this, so I don't know if I should comment here or in a new thread.

**Comment by jwag956** [comment]
If you want to pursue this - please open a new issue.
You are correct - there is no code in that case for returning JSON - since the only known use case is that link being present in an email and the browser will be doing the GET (and therefore need HTML back).
If you have a new use case - please file an issue and describe it. Certainly not difficult to add JSON response
