### ISSUE TITLE
Hungarian translations are not getting compiled in 5.1.1

### ISSUE THREAD

**Issue by martincpt** [Flask-Middleware/flask-security#771]
Hi there, 

Thank you for your work!

I waited for this release since Hungarian translations are important for me and currently I'm loading them manually.

Now I just tried the new release and the Hungarian translations just did not appear. I instantly checked the default translation directory and I noticed there is no compiled version of the Hungarian translations.

Is there some script that compiles translations during package installation?

The rest of them looks good however `is_IS` and `nl_NL` folder contains `messages.po` which looks the wrong filename to me.

**Comment by jwag956** [comment]
#772
