### ISSUE TITLE
Issue with register_form adding fields.

### ISSUE THREAD

**Issue by eneadodi** [Flask-Middleware/flask-security#775]
Hello,
As a quick rundown, I import from extensions, where I declare security = Security() the variable 'security' onto my create_app function.

Within my create_app function I contain the following code:
 security.init_app(app,user_datastore,register_form=ExtendedRegisterForm)

My ExtendedRegisterForm is imported from form.py and contains the following:

 ####basic form extensions
class ExtendedRegisterForm(RegisterForm,PasswordConfirmFormMixin):
    username = StringField('Username',[DataRequired()])
    terms_and_conditions = BooleanField('I agree to all statements in Terms of service and Privacy Policy', [DataRequired(message='You must agree to the terms and conditions.')])
    
    
However, when I try to declare the password_confirm or terms_and_conditions, the if statement fails:
{% if register_user_form.terms_and_conditions %}
         {{ render_field_with_errors_and_css(register_user_form.terms_and_conditions, 'formfields', 'form-control', 'errorfields') }}

Do we have a clue on what may be happening? Checked far and wide and couldn't find a similar issue.

**Comment by jwag956** [comment]
It might be as simple as the confusing fact that if you have SECURITY_CONFIRMABLE set then FS uses ConfirmRegisterForm and you should pass that as part of init_app(confirm_register_form=MyExtendedConfirmRegisterForm).

**Comment by eneadodi** [comment]
It was something very similar to this actually. Thank you for the help! Is there any way I can donate to project?
