### ISSUE TITLE
Confusion on register_user.html changes

### ISSUE THREAD

**Issue by eneadodi** [Flask-Middleware/flask-security#776]
The current register_user.html is as follows:

`{% extends "security/base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, render_form_errors %}

{% block content %}
  {% include "security/_messages.html" %}
  {{ _fsdomain('Register') }}
  <form action="{{ url_for_security('register') }}" method="post" name="register_user_form">
    {{ register_user_form.hidden_tag() }}
    {{ render_form_errors(register_user_form) }}
    {{ render_field_with_errors(register_user_form.email) }}
    {% if security.username_enable %}{{ render_field_with_errors(register_user_form.username) }}{% endif %}
    {{ render_field_with_errors(register_user_form.password) }}
    {% if register_user_form.password_confirm %}
      {{ render_field_with_errors(register_user_form.password_confirm) }}
    {% endif %}
    {{ render_field(register_user_form.submit) }}
  </form>
  {% include "security/_menu.html" %}
{% endblock content %}`

I wanted to add some visual effects on it, so I made a signup.html which I have placed here as a txt.

With Macros simply changed a bit for css styling. That is also placed here as a txt.

The issue:
Get works well. however when it try to post i get a 405 error. When I substitute my code with the original regiser_user.html, post works. Thus I don't know what is causing the issue. What other pieces of information can I provide?
[macros.txt](https://github.com/Flask-Middleware/flask-security/files/11007463/macros.txt)
[signup.txt](https://github.com/Flask-Middleware/flask-security/files/11007465/signup.txt)

**Comment by jwag956** [comment]
You should probably start by going into your browser development tools and actually looking at precisely what was passed to the browser. 405 is 'not allowed' so my guess is you somehow changed where the action POST is going...

**Comment by jwag956** [comment]
If you have additional questions - please start a discussion:
https://github.com/Flask-Middleware/flask-security/discussions
