### ISSUE TITLE
REMEMBER_COOKIE security options

### ISSUE THREAD

**Issue by rengaboy** [Flask-Middleware/flask-security#782]
**Hello everyone!**
@jwag956 Chris, thank you for maintaining this awesome repo.

As i saw in #285 issue, on Mar 6, 2020 there was no opportunity to set options to REMEMBER_COOKIE.

But at July 29, 2021, Max Countryman merged new commits in Flask-Login repo, which added options to REMEMBER_COOKIE variable. One of them is "REMEMBER_COOKIE_SAMESITE", which is None by default, but allows to set cookie to Lax. Is it posiible to add an opportunity to pass this option from Flask-Security to Flask-Login? full list of configurable variables here - [Flask-Login remember me](https://flask-login.readthedocs.io/en/latest/#remember-me)

**Comment by jwag956** [comment]
As is noted in the quickstart doc - simply set the required configuration in the app.config prior to initializing flask_security:
```
    app.config["REMEMBER_COOKIE_SAMESITE"] = "strict"
    app.config["SESSION_COOKIE_SAMESITE"] = "strict"
```
