### ISSUE TITLE
4.1.x still uses JSONEncoder/Decoder and thus incompatible with Flask 2.3

### ISSUE THREAD

**Issue by sr-verde** [Flask-Middleware/flask-security#786]
Hey, I’m still on Flask Security 4.1. Flask 2.3.0 has [now removed](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0) JSONEncoder and JSONDecoder. Because of that, I’ll get the following error running unittests for my app:

```
…
    from flask_security import Security, SQLAlchemyUserDatastore
/root/.cache/pypoetry/virtualenvs/xxx-YYYYYYYY-py3.11/lib/python3.11/site-packages/flask_security/__init__.py:14: in <module>
    from .changeable import admin_change_password
/root/.cache/pypoetry/virtualenvs/xxx-YYYYYYYY-py3.11/lib/python3.11/site-packages/flask_security/changeable.py:19: in <module>
    from .utils import config_value, hash_password, login_user, send_mail
/root/.cache/pypoetry/virtualenvs/xxx-YYYYYYYY-py3.11/lib/python3.11/site-packages/flask_security/utils.py:36: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/root/.cache/pypoetry/virtualenvs/xxx-YYYYYYYY-py3.11/lib/python3.11/site-packages/flask/json/__init__.py)
```

We can either backport #657 or we should change the version constraint of 4.1.x branch. But that would be the beginning of the end of support for 4.1.x, since Flask does not release security fixes for older versions.

**Comment by jwag956** [comment]
It is great that pallets is more aggressively moving their packages forward - even though it does mean more work for the rest of us (with 2.3 flask_Mongoengine no longer works, and a few other packages through warnings). Backporting is a possibility - though one never knows when the next  change will come.

From some threads I've been reading around versioning, Flask-Security really shouldn't be doing any pinning of versions - that is the applications responsibility.
However - in reality, I DID pin flask to <2.3 in the FS release 4.1.6 so not sure how you got conflicting versions..

I would take a PR - my guess is there will be other issues with deprecations (from pytest.ini) but we could silence all those for older releases.

**Comment by sr-verde** [comment]
Okay, yes. You're right. That was because I had `Flask-Security-Too = "^4.1.0"` and poetry downgraded flask-security-too to `4.1.4`. Thanks for your time. I think, we can close that issue here.

> However - in reality, I DID pin flask to <2.3 in the FS release 4.1.6 so not sure how you got conflicting versions..

I think that’s totally okay.
