### ISSUE TITLE
Unable to prevent flask-security to auto login after registration.

### ISSUE THREAD

**Issue by parthjeet** [Flask-Middleware/flask-security#799]
When a user is registered, I do not want the user to log in automatically, instead the page should redirect to the login page. 
Here are my configs:

    app.config['SECURITY_REGISTERABLE'] = True
    app.config['SECURITY_CONFIRMABLE'] = False
    app.config['SECURITY_SEND_REGISTER_EMAIL'] = False
    app.config['USER_ENABLE_CONFIRM_EMAIL'] = False
    app.config['SECURITY_POST_LOGIN_VIEW'] = '/'
    app.config['SECURITY_POST_REGISTER_VIEW'] = '/login_redirect/'

Below is the /login_redirect/ route definition

    @app.route('/login_redirect/')
    @login_required
    def login_redirect():
        return redirect(url_for('security.login'))

**Comment by jwag956** [comment]
Correct - if you don't require confirmation, it automatically logs you in.

**Comment by parthjeet** [comment]
Do you think this can be added in a future release? 
Giving an option to not automatically log in after registration even if email confirmation is not required?

**Comment by parthjeet** [comment]
Also, a StackOverflow user([pjcunningham](https://stackoverflow.com/users/2800058/pjcunningham)), helped with a workaround.

```
from flask_security.utils import logout_user

@app.route('/login_redirect/')
@login_required
def login_redirect():
    logout_user()
    return redirect(url_for('security.login')) 
```
