### ISSUE TITLE
Outdated documentation for permissions field in Quickstart guide

### ISSUE THREAD

**Issue by lliendo** [Flask-Middleware/flask-security#801]
Hi!

I've opened this issue because I had a hard time trying to make the `permissions` field for the `Role` model work. As per the current Quickstart documentation at: https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-sqlalchemy-application-with-session it states that the `permissions` field must be `permissions = Column(UnicodeText)`. Doing so and trying for example something like:

```
from flask_security import SQLAlchemySessionUserDatastore
from flask_app.models.auth import User, Role


user_datastore = SQLAlchemySessionUserDatastore(db_session, User, Role)  # `db_session` is `SQLAlchemy().session`.
admin_role = Role.query.filter(Role.name == 'admin').first()  # Assume the `Role` admin is present in database.
user_datastore.add_permissions_to_role(admin_role, ['create_user', 'edit_user', 'delete_user'])
db_session.commit()
```

produces a similar error like reported in: https://github.com/Flask-Middleware/flask-security/issues/673

It wasn't until digging in the Github issues that I reached this changelog: https://github.com/Flask-Middleware/flask-security/pull/675/commits/cbd047a64858b17f6b685a8e2683b10b52e1d31b where it is stated that `permissions` must be: `Column(MutableList.as_mutable(AsaList()), nullable=True)`.

Given the fact that this is a breaking change and also there's basically no information or examples out there related to the `.add_permissions_to_role` method (or permission(s) handling for the `Role` model in general) it is was really time consuming to find that the documentation was outdated and incorrect.

Thanks,
Lucas.

**Comment by jwag956** [comment]
good catch - thanks.
