### ISSUE TITLE
Timeout on AWS Lambda+API Gateway

### ISSUE THREAD

**Issue by asaarashi** [Flask-Middleware/flask-security#802]
I replaced flask-security with flask-security-too but the tricky timeout issue still persists.

It took 40+ seconds no matter if I use flask-security or flask-security-too. Meanwhile, API gateway max timeout is 29s. 

`[1686717070280] [INFO] 2023-06-14T04:31:10.280Z 72f4653a-41e6-4e50-8927-4d8c6c82cc13 219.137.142.234 - - [14/Jun/2023:04:31:10 +0000] "POST /login HTTP/1.1" 302 189 "https://psy00t4ygj.execute-api.ap-southeast-1.amazonaws.com/dev/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" 0/43937.403000000006`

So sad. Any ideas?

**Comment by asaarashi** [comment]
I dropped bcrypt in favor of sha512_crypt now it works

**Comment by jwag956** [comment]
bcrypt takes on the order of seconds - 40 seconds sounds like maybe your database was idled? Glad it is working now.
