### ISSUE TITLE
Login should not validate email addresses

### ISSUE THREAD

**Issue by immanuel-h** [Flask-Middleware/flask-security#806]
Hi, 

Source defect over in pgadmin4: https://github.com/pgadmin-org/pgadmin4/issues/6504

TL;DR: when updating flas-security-too, it results in previously working logins (eg. foo@bar.baz) failing, because the email validation fails. Based on the discussion there, this seems to be an unitended side effect of #394. While email addresses _should_ be validated when storing them (registration, user details, ...) they should generally _not_ be validated when logging in, as it has an impact of unknown scale on the existing user base.

**Comment by immanuel-h** [comment]
Seems this is not fixed for my special use fase (foo@bar.local) ... but this to me is a bug in email validator. I.e. if deliverability checks are disabled, also checking for special use domains should be disabled. I'll raise a ticket there and link it.

**Comment by immanuel-h** [comment]
Created https://github.com/JoshData/python-email-validator/issues/122. While doing so I also found a problem with the code here though. The `check_deliverability` option actually does a DNS resolution to verify deliverability, but to disable (hopefully once it's fixed) the special domain validation, one needs to set `globally_deliverable` to `False` as well over here: https://github.com/Flask-Middleware/flask-security/blob/1c8062dd6acda6e1e8928df8a991061a705a8d17/flask_security/mail_util.py#L129

**Comment by jwag956** [comment]
I don't see any documentation for `globally_deliverable` - and that doesn't seem like something that should be 'normally' set. You can set that in SECURITY_EMAIL_VALIDATOR_ARGS or set email_validator.TEST_ENVIRONMENT=True
