### ISSUE TITLE
Tests fails after upgrading from FS 4 to 5 ( werkzeug.test.ClientRedirectError: Loop detected: A 302 redirect to / was already made.)

### ISSUE THREAD

**Issue by amkrtchyan-tmp** [Flask-Middleware/flask-security#833]
I have a Flask application which was working fine and the unit tests are passed too. I was using Flask 2.0.3 and FS 4.1.3.

Recently i have decided to upgrade my app with Flask 2.3.3 and FS 5.3.0. After upgrading the app working fine using user interface. But when i am trying to run the tests related to authentication they are fail. The tests are failing, because during authentication i am getting following error:
` werkzeug.test.ClientRedirectError: Loop detected: A 302 redirect to / was already made.`

The simple test function is below:
```
def test_login2(fapp):
    with fapp.test_client() as client:
        rv = client.post('/login', data={'email': 'admin@domain.co', "password": '123'}, follow_redirects=True)
        assert rv.status_code == 200
```
The line `client.post(...` throws following error:
```
>           rv = client.post('/login', data={'email': 'admin@domain.co', "password": '123'}, follow_redirects=True)

tests/func/test_auth.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.cache/pypoetry/virtualenvs/aftdi-kOiPS1-0-py3.11/lib/python3.11/site-packages/werkzeug/test.py:1248: in post
    return self.open(*args, **kw)
../../../.cache/pypoetry/virtualenvs/aftdi-kOiPS1-0-py3.11/lib/python3.11/site-packages/flask/testing.py:232: in open
    response = super().open(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <FlaskClient <Flask 'fapp'>>, buffered = False, follow_redirects = True, args = (<Request 'http://localhost/login' [POST]>,), kwargs = {}
request = <Request 'http://localhost/login' [POST]>, arg = <Request 'http://localhost/login' [POST]>, response = <WrapperTestResponse 189 bytes [302 FOUND]>
redirects = {('/', 302), ('/home', 302), ('/login?next=%2Fhome', 302)}
history = [<WrapperTestResponse 189 bytes [302 FOUND]>, <WrapperTestResponse 197 bytes [302 FOUND]>, <WrapperTestResponse 225 bytes [302 FOUND]>], new_redirect_entry = ('/', 302)

....
E               werkzeug.test.ClientRedirectError: Loop detected: A 302 redirect to / was already made.

```
I have tried to set `SECURITY_POST_LOGIN_VIEW` to different url's, but still getting `ClientRedirectError`.

The only FS parameters i set is following:
```
    SECURITY_REGISTERABLE = True
    SECURITY_CONFIRMABLE = True
    SECURITY_RECOVERABLE = True
    SECURITY_TRACKABLE = True
    SECURITY_CHANGEABLE = True
```
As I mentioned above the app working fine after upgrade and the problem only with unit testing

Could you please advice how to solve the issue?

**Comment by jwag956** [comment]
Need a bit more info - like what your "/home" endpoint looks like. The log line:
redirects = {('/', 302), ('/home', 302), ('/login?next=%2Fhome', 302)}

probably gives a clue - POST login went to "/" - from there you must have a redirect to "/home" which turned around and went to login (which user is now logged in) so it again redirected to "/"...

**Comment by amkrtchyan-tmp** [comment]
my "/home" and "/" endpoints looks like:
```
@main.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('.home'))
    return render_template('home/home.html')

@main.route('/home')
@auth_required()
def home():
    return render_template('front_page.html')

```
I was also thinking that it may cause the issue and for the testing purposes i have set `SECURITY_POST_LOGIN_VIEW=/home` and got same error:

```
...
self = <FlaskClient <Flask 'fapp'>>, buffered = False, follow_redirects = True, args = (<Request 'http://localhost/login' [POST]>,), kwargs = {}
request = <Request 'http://localhost/login' [POST]>, arg = <Request 'http://localhost/login' [POST]>, response = <WrapperTestResponse 197 bytes [302 FOUND]>
redirects = {('/home', 302), ('/login?next=%2Fhome', 302)}, history = [<WrapperTestResponse 197 bytes [302 FOUND]>, <WrapperTestResponse 225 bytes [302 FOUND]>]
new_redirect_entry = ('/home', 302)
...
E               werkzeug.test.ClientRedirectError: Loop detected: A 302 redirect to /home was already made.
```
Also I have set `SECURITY_POST_LOGIN_VIEW=/dashboard`. The /dashboard view is following:
```
@main.route('/dashboard')
@auth_required()
def dashboard():
    return render_template('dashboard.html')
``` 
Error is same too:
```
...
self = <FlaskClient <Flask 'fapp'>>, buffered = False, follow_redirects = True, args = (<Request 'http://localhost/login' [POST]>,), kwargs = {}
request = <Request 'http://localhost/login' [POST]>, arg = <Request 'http://localhost/login' [POST]>, response = <WrapperTestResponse 207 bytes [302 FOUND]>
redirects = {('/dashboard', 302), ('/login?next=%2Fdashboard', 302)}, history = [<WrapperTestResponse 207 bytes [302 FOUND]>, <WrapperTestResponse 235 bytes [302 FOUND]>]
new_redirect_entry = ('/dashboard', 302)
...
E               werkzeug.test.ClientRedirectError: Loop detected: A 302 redirect to /dashboard was already made.
```

I would like to mention also that app logs are shows that user is authenticated.

**Comment by jwag956** [comment]
As a quick test - could you change your test to NOT use a context manager and create the test_client explicitly?

client = fapp.test_client()

rv = client.post(xxxxx)

and see if that changes any behavior?

**Comment by amkrtchyan-tmp** [comment]
I did following:
```
def test_login3(fapp):
    client = fapp.test_client()
    rv = client.post('/login', data={'email': 'admin@domain.co', "password": '123'}, follow_redirects=True)
    assert rv.status_code == 200
```
I have tested with "/", "/home" and "/dashboard" (with `@auth_required()`) and got same error:
```
...
...
    def test_login3(fapp):
        client = fapp.test_client()
>       rv = client.post('/login', data={'email': 'admin@domain.co', "password": '123'}, follow_redirects=True)

...
self = <FlaskClient <Flask 'fapp'>>, buffered = False, follow_redirects = True, args = (<Request 'http://localhost/login' [POST]>,), kwargs = {}
request = <Request 'http://localhost/login' [POST]>, arg = <Request 'http://localhost/login' [POST]>, response = <WrapperTestResponse 207 bytes [302 FOUND]>
redirects = {('/dashboard', 302), ('/login?next=%2Fdashboard', 302)}, history = [<WrapperTestResponse 207 bytes [302 FOUND]>, <WrapperTestResponse 235 bytes [302 FOUND]>]
new_redirect_entry = ('/dashboard', 302)
...
E               werkzeug.test.ClientRedirectError: Loop detected: A 302 redirect to /dashboard was already made.
```
Below is the versions of related installed packages:
```
python = "^3.10"
flask = "^2.3.3"
flask-sqlalchemy = "^3.1.1"
flask-migrate = "^4.0.5"
flask-mail = "^0.9.1"
email-validator = "^2.0.0.post2"
requests = "^2.31.0"
flask-babel = "^3.1.0"
flask-security-too = "^5.3.0"
pytest = "^7.4.2"
```

**Comment by jwag956** [comment]
Hmm - not obvious- it really seems like the @auth_required() decorator for /home is returning False so is redirecting to /login and thus the loop.  This might happen is cookies aren't properly being sent etc - though all that is normally fine with flasks test_client.

If there is any way you can get me a reproducible test case I can debug with - that would be great.

This isn't new - but do you have:
app.config["SECURITY_EMAIL_VALIDATOR_ARGS"] = {"check_deliverability": False}

set for your unit tests?

**Comment by amkrtchyan-tmp** [comment]
I have created small app and able to reproduce the problem.

https://github.com/amkrtchyan-tmp/fs_test_debug

With the UI it works fine, but during the test it throws ClientRedirectError.

> This isn't new - but do you have:
> app.config["SECURITY_EMAIL_VALIDATOR_ARGS"] = {"check_deliverability": False}
> 
> set for your unit tests?

No, I not have

**Comment by jwag956** [comment]
Ok - this is the result of a few things - the biggest one is that in xx Flask-Login followed Flask's lead and move it's authentication context from the request context to 'g' (the app context).

read this: https://github.com/maxcountryman/flask-login/issues/704#issuecomment-1200038100

among many others - the solution is as simple as in your test fixture - simply:

`yield app`

**Comment by amkrtchyan-tmp** [comment]
Thank you for the help! The solution is solved ClientRedirectError.

I still need to modify other tests which need app context.
