### ISSUE TITLE
current_user not set in test with newer version of flask-login

### ISSUE THREAD

**Issue by nhoening** [Flask-Middleware/flask-security#834]
Hello,

we have been using Flask-Security happily for years, but now are struggling to upgrade, as authenticating via auth token does not work anymore. I hope you have a pointer for me.

I use `@auth_token_required()` on my endpoint.

We want to use Flask-Security==5.1.2 and are attempting to upgrade from flask-login==0.6.1 to 0.6.2 (as well as going to Flask 2.2 which goes with that)

(**the issue also persists with smaller versions of Flask-Security, so I understand that the actual reason might be in flask-login. Feel free to close this issue, as I'm probably not pointing out something that is going to improve Flask Security ― unless this happens to others**).

This only seems to be an issue in my automated test. My live tests are going fine.

In my test (I'm running only this one test), I'm logging in with a valid auth token, but when my endpoint code wants to check permissions, `flask_security.current_user.is_anonymous` is `True`.

I'm debugging what happens in `_check_token` and there the `user` object is the one I want. So the problem is to persist this.

When I debug in my app (in the code where I check permissions); I see that flask_principal has set an identity, but flask_security.current_user is not aware:

```
(Pdb) from flask import g
(Pdb) g.identity
<Identity id="c44e488b5ab54fec888be4b9ebb66e72" auth_type="None" provides=set()>
(Pdb) current_user
<flask_security.core.AnonymousUser object at 0x7fb2530126b0>
(Pdb) 
```

I made the following change in `_check_token`, and then it works (`current_user` will be set correctly):

```
def _check_token():
    user = _security.login_manager.request_callback(request)
    if user and user.is_authenticated:
        app = current_app._get_current_object()
        identity_changed.send(app, identity=Identity(user.fs_uniquifier))
        
        from flask_login import login_user  # ADDED BY ME
        login_user(user)  # ADDED BY ME
    return True

    return False
```

Thanks if anyone sees where I should work towards, and apologies if I'm in the wrong place with this.

**Comment by jwag956** [comment]
I am guessing this is the same issue as #833 (still verifying) - how are you initializing your test app - by any chance do you push an app_context as part of the fixture?
Providing more code or a complete small test case would be helpful.

**Comment by nhoening** [comment]
Thanks for replying.

I had seen that comment, and started to play with how my test fixtures are set up. Here is my current attempt:


```
@pytest.fixture(scope="session")
def app():
    print("APP FIXTURE")
    test_app = create_app(env="testing")
    yield test_app
    print("DONE WITH APP FIXTURE")


@pytest.fixture(scope="module")
def db(app):
    """Fresh test db per module."""
    with app.app_context():
        with create_test_db(app) as test_db:
            yield test_db

def test_auth_token(client, setup_api_test_data):
    """Tries to use an auth token to query an endpoint."""
    with UserContext("test_admin_user@seita.nl") as admin:
        auth_token = admin.get_auth_token()
        password = admin.password
    assert isinstance(current_user, AnonymousUser)
    response = client.get(url_for("AssetAPI:index"), headers={"Authorization": auth_token})
    assert response.status_code == 200
    assert response.json == []  # admin has no assets themselves
```

I can try to make this more minimal, but I have no time now. `setup_api_test_data` is another fixture which uses the `db` fixture to create test data.

This test is failing with a 401, as described above (my code throws 401 as `current_user` is None).

Let me know if this helps.

**Comment by jwag956** [comment]
Would need to see entire test - for example the default header for sending auth-tokens is "Authentication-Token" - so presumably you changed that somewhere.

**Comment by nhoening** [comment]
I'll try to add information, not sure what makes an "entire test", short of a full self-contained example.

We have indeed set our own default header name (not sure why, maybe it used to be the default in the old FS days?)

All Flask-Security settings:
```
    SECURITY_REGISTERABLE: bool = False
    SECURITY_LOGIN_USER_TEMPLATE: str = "admin/login_user.html"
    SECURITY_EMAIL_SUBJECT_PASSWORD_RESET: str = (
        "Password reset instructions for your FlexMeasures account."
    )
    SECURITY_EMAIL_SUBJECT_PASSWORD_NOTICE: str = (
        "Your FlexMeasures password has been reset."
    )
    SECURITY_FORGOT_PASSWORD_TEMPLATE: str = "admin/forgot_password.html"
    SECURITY_RECOVERABLE: bool = True
    SECURITY_RESET_PASSWORD_TEMPLATE: str = "admin/reset_password.html"
    SECURITY_TOKEN_AUTHENTICATION_HEADER: str = "Authorization"
    SECURITY_TOKEN_MAX_AGE: int = 60 * 60 * 6  # six hours
    SECURITY_TRACKABLE: bool = False  # this is more in line with modern privacy law
    
    # --------- from here on, only used in tests -------------
    
    SECURITY_PASSWORD_SALT: str = "$2b$19$abcdefghijklmnopqrstuv"

    # These can speed up tests due to less hashing work (I saw ~165s -> ~100s)
    SECURITY_HASHING_SCHEMES: list[str] = ["hex_md5"]
    SECURITY_DEPRECATED_HASHING_SCHEMES: list[str] = []
```

The fixture in the stack I didn't include (`setup_api_test_data`) is only adding things to the database and has "module" scope.

Here are some versions (on Python 3.10):

```
± pip list | grep lask 
Flask                     2.2.5
Flask-Classful            0.16.0
Flask-Cors                4.0.0
Flask-JSON                0.4.0
Flask-Login               0.6.2
Flask-Mail                0.9.1
flask-marshmallow         0.15.0
Flask-Migrate             4.0.4
Flask-Principal           0.4.0
Flask-Security-Too        5.1.2
Flask-SQLAlchemy          3.0.5
Flask-SSLify              0.1.5
Flask-WTF                 1.1.1
pytest-flask              1.2.0
```

I've tried printing `g.__hash__()` in both flask-principal code (after `g.identity` is set) and my code - both have the same hash. 

What else is missing? Thanks again.

**Comment by nhoening** [comment]
I updated/simplified the `db` fixture above, which had been unclear.

**Comment by jwag956** [comment]
If you have a chance to produce a reproducible test - please re-open this or start a new issue.
Thanks!

**Comment by NexPlex** [comment]
I having the same issue. I did a monkey patch like [nhoening](https://github.com/nhoening) recommended. Is there a fix for this I'm not aware of?

Flask-Security-Too==5.4.3

    # Define the new _check_token function
    from flask_security.proxies import _security
    def new_check_token():
        user = _security.login_manager.request_callback(request)
        if is_user_authenticated(user):
            identity_changed.send(
                current_app._get_current_object(),
                _async_wrapper=current_app.ensure_sync,
                identity=Identity(user.fs_uniquifier),
            )
            login_user(user)  # ADDED BY ME
            return True
        return False

    # Monkey patch the original _check_token function
    import flask_security.decorators
    flask_security.decorators._check_token = new_check_token
