### ISSUE TITLE
App won't run after upgrading werkzeug

### ISSUE THREAD

**Issue by Calabashmc** [Flask-Middleware/flask-security#843]
flask-security-too installs flask-login which breaks after an upgrade of werkzeug to verson 3.0

/venv/lib/python3.11/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' 

I also upgraded flask and get this if I downgrade werzeug
ImportError: cannot import name 'Markup' from 'flask'

What is the most recent version of flask and werzeug I can use?

**Comment by jwag956** [comment]
The previous versions! hopefully they will fix flask-login soon - usually it takes about a week or so.
