### ISSUE TITLE
US via email does not respect non-email identities

### ISSUE THREAD

**Issue by NoRePercussions** [Flask-Middleware/flask-security#845]
The Unified Signin system, specifically sending magic links and one-time codes via email, does not respect using non-email identities such as usernames. If multiple users have the same email address registered, only one will be able to sign in using the magic link.

https://github.com/Flask-Middleware/flask-security/blob/dc342d412a246d537fe145ef5089dc20a5172662/flask_security/unified_signin.py#L1002-L1004

This is regardless of `USERNAME_ENABLE` or `USER_IDENTITY_ATTRIBUTES`.

**Comment by NoRePercussions** [comment]
In contrast, the reset password flow a token generated with the user's unique ID instead of any given identity attribute:

https://github.com/Flask-Middleware/flask-security/blob/dc342d412a246d537fe145ef5089dc20a5172662/flask_security/recoverable.py#L67-L74

This seems like a safer and more general way to implement magic link login, perhaps at the cost of the link carrying more legible context for what it does.

**Comment by jwag956** [comment]
good point - and better to not have all those query args as well - let me look into it.
