### ISSUE TITLE
Flask-Security-Too 5.3.0 is not compatible with Werkzeug 3.0.0 and Flask 3.0.0

### ISSUE THREAD

**Issue by fabianmathias** [Flask-Middleware/flask-security#850]
Flask-Security-Too 5.3.0 is not compatible with Werkzeug 3.0.0 / Flask 3.0.0 and raises an import Error

**Comment by nhatdt51** [comment]
@fabianmathias A quick way to escape from this issue is to install the package from GitHub link instead from pypi.

**Comment by jwag956** [comment]
Fixes are in - waiting to release for Flask-Login and possibly a fix for py_webauthn
