### ISSUE TITLE
Authentication token doesn't work with endpoints that require authentication

### ISSUE THREAD

**Issue by lilz-egoto** [Flask-Middleware/flask-security#860]
I'm trying to work with the flask security external API to make flask-security work as an API. After getting the authentication token from /login and trying to use it to access any protected page (both ones I decorate with @auth_required and endpoints implemented automatically by the library such as /change), I get a 401 unauthorized.

```
{
	"meta": {
		"code": 401
	},
	"response": {
		"errors": [
			"You are not authenticated. Please supply the correct credentials."
		]
	}
}
```

I have these config settings set:
```
app.config["WTF_CSRF_CHECK_DEFAULT"] = False
app.config["SECURITY_CSRF_IGNORE_UNAUTH_ENDPOINTS"] = True
```

**Comment by lilz-egoto** [comment]
Do I need to somehow access the session cookie?
<img width="615" alt="image" src="https://github.com/Flask-Middleware/flask-security/assets/114893596/2e612d96-68ce-4c9d-98f7-7aafc89606db">

**Comment by jwag956** [comment]
Using the API (i.e. JSON request and responses) are separate from how you authenticate. For web-based application (such as single-page javascript) it is recommended to use sessions along with JSON request and responses. This is easy to configure - check out: https://flask-security-too.readthedocs.io/en/stable/spa.html#working-with-single-page-applications

For scripting it is recommended to grab the authentication token from a successful login and use that - that must be supplied as a header value 'Authentication-Token' (by default)

**Comment by lilz-egoto** [comment]
Ah ok so I misunderstood then. So we do need the session cookie and the authentication token when accessing protected endpoints? Thank you for your response btw.

**Comment by jwag956** [comment]
No - sorry for the confusion - either session (recommended for web apps) OR authentication token (recommended for scripting)

**Comment by jwag956** [comment]
CSRF doesn't really have anything to do with forms versus JSON. You should protect your application using CSRF anytime your users are using a web browser (which will happily send your apps cookie on every request). If your backend is only used by some other services you can disable CSRF globally.

**Comment by lilz-egoto** [comment]
Ah ok thanks, learned a lot
