### ISSUE TITLE
problem with spa: Reset email link is sent in terms of flask server name

### ISSUE THREAD

**Issue by lilz-egoto** [Flask-Middleware/flask-security#862]
I'm trying to implement the SECURITY_RECOVERABLE feature and I noticed that the reset password link sent to the user's email address is in terms of the flask server's hostname and port. Would it make sense to add a configuration key that allows you to specify/customize this link? Something like `SECURITY_RESET_LINK = "www.hello.com/reset_password/:token"`. I did read [this](https://flask-security-too.readthedocs.io/en/stable/spa.html#working-with-single-page-applications), but did not see anything that would help

**Comment by jwag956** [comment]
The URL/link should point to your application's public-facing domain. You wouldn't want it to point outside your domain. Flask-Security uses: https://flask.palletsprojects.com/en/3.0.x/api/#flask.Flask.url_for to generate the URL - setting _external-True. In production, you would have a load balancer and/or some frontend reverse proxy web server (apache/nginx) that can perform routing as desired - but the WSGI parameters that Flask gets should be the access URL your client used.

The reference you made is specifically for testing locally - where you don't have a front-end webserver/WSGI server.
