### ISSUE TITLE
/register works with multipart/form-data 

### ISSUE THREAD

**Issue by lilz-egoto** [Flask-Middleware/flask-security#868]
/register endpoint works with multipart/form-data mime type. When using the external API, is it possible to reject any request if it isn't application/json?

**Comment by lilz-egoto** [comment]
Closing as I did this on the flask side with app.before_request

```
@app.before_request
def only_json_requests():
    if not flask.request.is_json:
        flask.abort(400)
```

**Comment by jwag956** [comment]
I was going to say - all that happens on the Flask/Werkzeug side - nice easy solution
