### ISSUE TITLE
Can't use authentication token for enabling 2fa as an authenticated user

### ISSUE THREAD

**Issue by lilz-egoto** [Flask-Middleware/flask-security#869]
I'm sorry if this duplicates our previous discussion about the authentication token, but you mentioned that you can use authentication token OR session cookies. I am trying to just use the authentication token returned by flask security's external API when you include `include_auth_token=1` in the query parameters. 

I am having trouble with setting up two factor authentication while authenticated and having the authentication token. 
I am including the authentication token in the header and have set the content type to `application/json`, but I am getting a `401: unauthorized`. 

js side
```
      const URL = `${BASEURL}/2fa_setup`;

      const data = {
        setup: "email",
        email: this.email,
      };

      axios(URL, {
        data: data,
        method: "POST",
        headers: { "Content-Type": "application/json", "Authentication-Token": localStorage.getItem("auth_token") },
      })
```

python side:
```
app.config["WTF_CSRF_TIME_LIMIT"] = None
app.config["WTF_CSRF_CHECK_DEFAULT"] = False
app.config["SECURITY_CSRF_IGNORE_UNAUTH_ENDPOINTS"] = True
app.config["SECURITY_TWO_FACTOR"] = True
app.config["SECURITY_TWO_FACTOR_ENABLED_METHODS"] = ["email"]
app.config["SECURITY_TWO_FACTOR_SETUP_URL"] = "/2fa_setup"
```
Console error:
<img width="440" alt="image" src="https://github.com/Flask-Middleware/flask-security/assets/114893596/78b2ad62-de85-4379-8084-be55d15e4621">
<img width="402" alt="image" src="https://github.com/Flask-Middleware/flask-security/assets/114893596/eb9f6b71-5c83-455b-a81f-36758c05fa9c">

**Comment by lilz-egoto** [comment]
Ah it was due to the default `SECURITY_CSRF_PROTECT_MECHANISMS`

**Comment by jwag956** [comment]
As implemented and documented - currently - the 2FA feature requires session cookies to be sent and received.
I am going to open an issue to improve documentation around sessions and which config variables need to be changed if the application doesn't want to send session contents.

**Comment by jwag956** [comment]
https://flask-security-too.readthedocs.io/en/stable/two_factor_configurations.html#theory-of-operation
