### ISSUE TITLE
change password gives 400 missing CSRF Token with CSRF protection disabled

### ISSUE THREAD

**Issue by lilz-egoto** [Flask-Middleware/flask-security#870]
I'm trying to only use the authentication token acquired from POST /login to change passwords(btw, anyway to get the authentication token another way?).

I've tried three things:
- turning off all CSRF protection, e.g. commenting out CSRFProtect(app), removing any configuration keys related to CSRF and hitting the /login endpoint
- doing CSRFProtect(app), but leaving `SECURITY_CSRF_PROTECT_MECHANISMS` empty, i.e `app.config["SECURITY_CSRF_PROTECT_MECHANISMS"] = []` (which I thought would mean none of the authentication mechanisms require CSRF?)
- putting a CSRF token into the request headers

but all three result in 400 missing CSRF token
<img width="451" alt="image" src="https://github.com/Flask-Middleware/flask-security/assets/114893596/bbc0f72c-2d66-4de1-9054-e86e4185f9dd">

My JS is as follows:
```
      axios(URL, {
        data: data,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authentication-Token": localStorage.getItem("auth_token"),
          "X-XSRF-Token": this.csrf_token },
      })

there's code before this that grabs the csrf token
```

The CSRF keys I have are:
```
app.config["SECURITY_CSRF_HEADER"] = "X-XSRF-Token"
app.config["SECURITY_CSRF_PROTECT_MECHANISMS"] = []
app.config["WTF_CSRF_TIME_LIMIT"] = None
app.config["WTF_CSRF_CHECK_DEFAULT"] = False
app.config["SECURITY_CSRF_IGNORE_UNAUTH_ENDPOINTS"] = True
```

**Comment by jwag956** [comment]
Hmm - yes - SECURITY_CSRF_PROTECT_MECHANISMS=[] should  stop the FS decorator from doing CSRF.
This error message come from flask_wtforms - one thing to try is setting WTF_CSRF_ENABLED=False - this would disable for the entire application and all endpoints - but at least you would know that worked.
And yes - WTF_CSRF_CHECK_DEFAULT should be set to False.

If you aren't calling CSRFProtect then I don't see how you are getting that error....

**Comment by jwag956** [comment]
Ok - doing some debugging here. So far I have found:

1) setting CSRF_PROTECT_MECHANISMS=[] isn't working - easy fix
2) setting the CSRF_HEADER isn't properly setting up WTFforms headers unless one is also setting the CSRF Cookie- another small bug.

Both simple fixes....
