### ISSUE TITLE
Improve unit tests for new 2FA feature

### ISSUE THREAD

**Issue by jwag956** [Flask-Middleware/flask-security#88]
The new 2FA feature has basic unit tests - but coverage isn't up to what we need.
According to @baurt this is mostly around testing JSON request/response.

**Comment by baurt** [comment]
Working on this. Been busy with life, but they are definitely coming.

**Comment by jwag956** [comment]
Thanks - don't work too much - I still have a couple more refactoring iterations to do. Also -at least for some of the 2FA endpoints there is still proper Json support to work out (you saw what I did for login).

**Comment by jwag956** [comment]
closed by #382
