### ISSUE TITLE
Override model ID field to UUID

### ISSUE THREAD

**Issue by mominur-helios** [Flask-Middleware/flask-security#887]
class User(db.Model, fsqla.FsUserMixin):
        __tablename__ = 'user'
        id = Column(String(), primary_key=True, default=str(uuid.uuid4()))

I want to change the `id` to `uuid` but I got this error

![Screenshot from 2023-12-11 12-02-22](https://github.com/Flask-Middleware/flask-security/assets/101915710/2ef8cc97-c11e-47de-b566-78608fe22e3a)

How can I override this field?

**Comment by jwag956** [comment]
You don't say what DB you are using (in memory, disk) or how you are creating the tables. I believe for table create you need  a length - So I would try String(255) and be sure to delete your DB.

**Comment by mominur-helios** [comment]
I'm using `sqlite` for development. BTW, I'm able to create a new field `uuid` along with the `id` but I wanted to replace the `id` with `uuid` as `primary key` but I can't do that. The flask-security `FsUserMixin` always expect an integer in the `id` field. I don't know how to change the `type` of this field.

**Comment by jwag956** [comment]
The models in models/fsqlaxx are for convenience only (and yes use 'id' as the primary key). If you have particular requirements on your tables or 'id' then you probably need to define your own UserModel - just be sure to follow the required naming as documented in 
https://flask-security-too.readthedocs.io/en/stable/models.html#models

Flask-Security-Too  does not reference the primary key anywhere.
