### ISSUE TITLE
passlib no longer maintained

### ISSUE THREAD

**Issue by chrisroat** [Flask-Middleware/flask-security#907]
Neither the [pypi package](https://pypi.org/project/passlib/) nor the [code base](https://foss.heptapod.net/python-libs/passlib/-/wikis/home) has been updated in over 3 years.  Some [code rot is happening](https://github.com/pyca/bcrypt/issues/684) as its dependencies evolve with time.  This may get worse over time.

**Comment by jwag956** [comment]
Looks like help is on the way:

https://foss.heptapod.net/python-libs/passlib/-/issues/187
