### ISSUE TITLE
Translations are broken

### ISSUE THREAD

**Issue by sr-verde** [Flask-Middleware/flask-security#936]
Hey, I’ve updated my project to the current development version of Flask-Security-Too. I lost all the translations. Now, each and every string of Flask Security is in English instead of German. Downgrading Flask-Babel or Babel doesn't help. Downgrading Flask-Security-Too fixes this issue and brings back translations.

This is my config:

```python
    BABEL_DEFAULT_LOCALE = "de"
```

**Comment by jwag956** [comment]
Hmm - any chance you just grabbed the source and didn't compile_catalog?

Release 5.4.0 didn't actually work - am going to try again tonight. Let's see if that works.

**Comment by sr-verde** [comment]
Ahm. Yes but no. My mistake in my development setup. Sorry for that.
