### ISSUE TITLE
API documentation is missing

### ISSUE THREAD

**Issue by mmillmore** [Flask-Middleware/flask-security#946]
The api documentation at https://flask-security-too.readthedocs.io/en/stable/api/_static/openapi_view.html is missing now. I go to https://flask-security-too.readthedocs.io/en/stable/api/ and click on the API link and it takes me to that, and I get Page Not Found

**Comment by jwag956** [comment]
had issues at end of 5.4.1 trying to get RTD building correctly. I think I see the issue.
