### ISSUE TITLE
Add get_api_token endpoint (oauth2?)

### ISSUE THREAD

**Issue by jwag956** [Flask-Middleware/flask-security#97]
Today - an auth_token is returned on login and some other endpoints.
This isn't ideal - UIs shouldn't normally need this - they should use sessions. It is an unnecessary security hole to send the auth_token to a browser if they don't need it.

Furthermore - options such as TTL should be specifiable as part of an API (not to exceed global configurations).

Upon thinking about this - considering moving away from current token mechanism completely and implementing the first pieces of oauth2 (client credential and password grant), along with using JWT to represent the access token.

**Comment by ziedbouf** [comment]
do we envisage to integrate with Flask-JWT and [authlib](https://github.com/lepture/authlib).

**Comment by jwag956** [comment]
Have just done preliminary research - my initial thought was to use oauthlib - it seem more crowd-maintained, is just server implementation.
authlib seems really big and trying to satisfy everybody.

Flask-JWT is basically abandoned. Flask-JTW-Extended has a lot of overlap with Flask-Security - so no - I am looking at: https://github.com/jpadilla/pyjwt as a low-level JWT library.

Would be interested in your thoughts...

**Comment by ziedbouf** [comment]
Thanks @jwag956  i think so far it's clear for me the path. I will be trying the `pyjwt` as i might need to get the JWT tokesn working with flask-security-too

**Comment by jwag956** [comment]
Now that we only return Token when requested - this isn't a security concern any more.
Closing this - and can open a new enhancement if a good use case comes up.
