### ISSUE TITLE
 enable custom role table name when using `fsqla_v3.FsUserMixin`

### ISSUE THREAD

**Issue by NicholasZXT** [Flask-Middleware/flask-security#976]
When using `FsUserMixin` class from `flask_security/models/fsqla_v3.py`，the role model class must be named with `Role`，otherwise it's  not working.
The reason is the source code snippet as follow:
```python
class FsUserMixin(FsUserMixinV2):
    """User information"""
   ...

    @declared_attr
    def roles(cls):
        return FsModels.db.relationship(
            "Role",   # here is the problem, it references role model class with name 'Role'
            secondary=FsModels.roles_users,
            backref=FsModels.db.backref(
                "users", lazy="dynamic", cascade_backrefs=False
            ),
        )
```
Due to the code, role model likes `class SecurityRole(db.Model, fsqla.FsRoleMixin)` will failed to run.
It's a little problem, but I do struggle with it for a while. 
Maybe it's not bad to add some custom for users like me in the future release.

**Comment by jwag956** [comment]
There are 2 different things  here - the DB table name and the class name.

Having your own DB tablename is supported and works as documented here: https://flask-security-too.readthedocs.io/en/stable/api.html#flask_security.models.fsqla.FsModels

You are correct that changing the class isn't currently supported.
