### ISSUE TITLE
can I custom response body from specific endpoint?

### ISSUE THREAD

**Issue by AppleBoiy** [Flask-Middleware/flask-security#985]
Can I custom the default response for a specific endpoint?

normally when login success the response will be like this: 
 
```json
{
    "meta": {
        "code": 200
    },
    "response": {
        "csrf_token": "token",
    }
}
```

so, after login process success, I want to add some user data to the response, like this:

```json
{
    "meta": {
        "code": 200
    },
    "response": {
        "csrf_token": "token",
        "user": {
            "id": 1,
            "name": "John Doe",
            "email": "example@mail.com"
        }
    }
}
```

**Comment by jwag956** [comment]
Check out https://flask-security-too.readthedocs.io/en/stable/models.html#custom-user-payload

Also - in the future - please ask questions over in Discussions (on github). Thanks
