### ISSUE TITLE
Add datastore support for new flask-sqlalchemy-lite

### ISSUE THREAD

**Issue by jwag956** [Flask-Middleware/flask-security#989]

**Comment by peterkronenberg** [comment]
Hi, you answered a question of mine on StackOverflow, https://stackoverflow.com/questions/78675096/how-to-prevent-flask-security-from-using-db-session-query-property/78678324#78678324.
Any thoughts on when this support will be done. I decided to take the plunge and move to Flask-SQLAlchemy-Lite

I posted another question which was closed, https://stackoverflow.com/questions/78678498/sqlalchemy-vs-flask-alechemy, although I'd love to hear your thoughts (I know this isn't really the right place for this)

**Comment by jwag956** [comment]
I am working on it now - unless some other bug shows up - this is the last piece before releasing 5.5 - so hopefully 5.5 will go out before the end of July - and the feature will be in main (so you can develop with it) in the next 2 weeks.

As to your second question - Flask-ALchemy-Lite  - which was just released for the first time a month or 2 ago - I think removes many of the concerns that folks had with Flask-Alchemy - which at the time tried to completely wrap Sqlalchemy models, queries, etc - which made it just different enough that it was very confusing. FAL is a very very thin layer - just providing the necessary glue to easily work with Flask - mostly just adding session management for web requests - all models, queries, etc are done using standard SQLAlchemy 2.x methods and conventions.
